/* ============================================================================
   رودمپ مهندسی کامپیوتر: پایهٔ مشترک، معماری سیستم‌های کامپیوتری،
   هوش مصنوعی و رباتیک، امنیت

   گرایش نرم‌افزار به رودمپ‌های «تخصص هر حوزه» (فرانت، بک، دواپس) وصل
   می‌شود؛ سیستم‌های تعبیه‌شده و شبکه در ce-systems.ts هستند.
   ========================================================================== */
import type { Roadmap } from "./types";

export const CE_ROADMAPS: Roadmap[] = [
  /* ═══════════════════════ پایهٔ مشترک مهندسی کامپیوتر ═══════════════════════ */
  {
    id: "ce-foundations",
    field: "ce",
    accent: "#4F46E5",
    ico: '<path d="M8 4.5H6.6A1.6 1.6 0 0 0 5 6.1v4.1L3.4 12 5 13.8v4.1a1.6 1.6 0 0 0 1.6 1.6H8M16 4.5h1.4A1.6 1.6 0 0 1 19 6.1v4.1l1.6 1.8-1.6 1.8v4.1a1.6 1.6 0 0 1-1.6 1.6H16" stroke-linecap="round" stroke-linejoin="round"/><path d="M9.6 9.4v5.2M13.2 9.4h1.4v5.2" stroke-linecap="round"/>',
    next: ["ce-architecture", "ce-ai", "ce-security", "embedded", "network-engineer", "foundations"],
    fa: {
      name: "پایهٔ مشترک مهندسی کامپیوتر",
      role: "Computer Engineering Core",
      intro:
        "مهندسی کامپیوتر پلی است میان برق و علوم کامپیوتر: از ترانزیستور و مدار منطقی تا سیستم‌عامل، شبکه و نرم‌افزار. همهٔ گرایش‌هایش — نرم‌افزار، معماری سیستم‌های کامپیوتری، هوش مصنوعی، شبکه، امنیت و فناوری اطلاعات — روی یک پایهٔ مشترک ساخته می‌شوند: ریاضیات گسسته، برنامه‌نویسی، ساختمان داده و الگوریتم، معماری کامپیوتر، سیستم‌عامل و شبکه. این رودمپ همان پایه است، با نگاهی به بازار کار.",
    },
    en: {
      name: "Computer engineering core",
      role: "Computer Engineering Core",
      intro:
        "Computer engineering is the bridge between electrical engineering and computer science: from transistors and logic circuits to operating systems, networks and software. All its branches — software, computer architecture, AI, networking, security and IT — rest on one shared foundation: discrete mathematics, programming, data structures and algorithms, computer architecture, operating systems and networks. This roadmap is that foundation, with an eye on the job market.",
    },
    stages: [
      {
        id: "cef-math",
        fa: "ریاضیات",
        en: "Mathematics",
        outcomeFa: "استدلال ریاضی می‌نویسی، مسئلهٔ شمارشی و گراف را حل می‌کنی و ابزار ریاضی یادگیری ماشین و گرافیک را داری.",
        outcomeEn: "You write mathematical arguments, solve counting and graph problems and have the maths of machine learning and graphics.",
        months: [4, 8],
        skills: [
          {
            fa: "ریاضیات گسسته", en: "Discrete mathematics", kind: "hard",
            whyFa: "زبان الگوریتم، پایگاه‌داده و رمزنگاری؛ «اثبات» را اینجا یاد می‌گیری.",
            whyEn: "The language of algorithms, databases and cryptography; this is where you learn to prove things.",
            items: ["Logic & proofs", "Sets, relations & functions", "Combinatorics", "Graph theory", "Recurrence relations"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "حسابان و جبر خطی", en: "Calculus and linear algebra", kind: "hard",
            whyFa: "گرافیک، یادگیری ماشین و پردازش سیگنال بدون جبر خطی ممکن نیستند.",
            whyEn: "Graphics, machine learning and signal processing are impossible without linear algebra.",
            items: ["Calculus I & II", "Matrices", "Eigenvalues", "Vector spaces"],
          },
          {
            fa: "آمار و احتمال", en: "Probability and statistics", kind: "hard",
            whyFa: "تحلیل الگوریتم تصادفی، شبکه، یادگیری ماشین و آزمون A/B همه آماری‌اند.",
            whyEn: "Randomised algorithms, networking, machine learning and A/B testing are all statistical.",
            items: ["Random variables", "Distributions", "Bayes' theorem", "Hypothesis testing"],
          },
          {
            fa: "ریاضی مهندسی و محاسبات عددی", en: "Engineering maths and numerical methods", kind: "hard",
            whyFa: "برای سیگنال، کنترل و شبیه‌سازی لازم است؛ و یادت می‌دهد کامپیوتر با عدد اعشاری چطور خطا می‌کند.",
            whyEn: "Needed for signals, control and simulation — and it teaches you how computers get floating-point arithmetic wrong.",
            items: ["Differential equations", "Fourier transform", "Numerical methods", "Floating-point error"],
          },
        ],
      },
      {
        id: "cef-prog",
        fa: "برنامه‌نویسی و مهندسی نرم‌افزار",
        en: "Programming and software engineering",
        outcomeFa: "برنامهٔ چندفایلی و شیءگرا با تست می‌نویسی، روی Git همکاری می‌کنی و نیازمندی را به طراحی تبدیل می‌کنی.",
        outcomeEn: "You write tested, multi-file object-oriented programs, collaborate on Git and turn requirements into a design.",
        months: [4, 6],
        skills: [
          {
            fa: "مبانی برنامه‌نویسی با C", en: "Programming fundamentals in C", kind: "hard",
            whyFa: "C تو را مجبور می‌کند بفهمی حافظه واقعاً چطور کار می‌کند؛ این فهم در هر زبان دیگری به کار می‌آید.",
            whyEn: "C forces you to understand how memory really works; that understanding pays off in every other language.",
            items: ["Types & variables", "Control flow", "Functions", "Pointers & memory", "Files"],
            tracks: ["43-c"],
          },
          {
            fa: "برنامه‌نویسی پیشرفته و شیءگرا", en: "Advanced and object-oriented programming", kind: "hard",
            whyFa: "برنامهٔ بزرگ بدون انتزاع، کپسوله‌سازی و تست قابل نگه‌داری نیست؛ زبانش C++، Java یا Python باشد فرقی ندارد.",
            whyEn: "A large program is unmaintainable without abstraction, encapsulation and tests — whether in C++, Java or Python.",
            items: ["Classes & objects", "Inheritance & polymorphism", "Exceptions", "Generics", "Unit testing"],
            tracks: ["47-oop", "44-cpp", "71-java", "12-python"],
          },
          {
            fa: "Git و ابزار توسعه", en: "Git and developer tools", kind: "hard",
            whyFa: "کار تیمی بدون کنترل نسخه ممکن نیست؛ دیباگر و خط فرمان هم ابزار روزانه‌اند.",
            whyEn: "Teamwork is impossible without version control; the debugger and command line are daily tools too.",
            items: ["Git", "Command line", "Debugger", "Build tools"],
            tracks: ["28-git", "03-linux-network"],
          },
          {
            fa: "مهندسی نرم‌افزار", en: "Software engineering", kind: "hard",
            whyFa: "بیشتر پروژه‌ها نه به‌خاطر کد بد، که به‌خاطر نیازمندی مبهم و ارتباط ضعیف شکست می‌خورند.",
            whyEn: "Most projects fail not because of bad code but because of vague requirements and poor communication.",
            items: ["Requirements (SRS)", "UML", "Design patterns", "Testing", "Agile / Scrum"],
            tracks: ["22-skills", "64-docs-writing", "63-scrum-agile"],
          },
        ],
      },
      {
        id: "cef-algo",
        fa: "ساختمان داده و الگوریتم",
        en: "Data structures and algorithms",
        outcomeFa: "برای هر مسئله ساختمان دادهٔ مناسب را انتخاب می‌کنی، پیچیدگی را تحلیل می‌کنی و در مسابقه و مصاحبه مسئله حل می‌کنی.",
        outcomeEn: "You choose the right data structure for each problem, analyse complexity and solve problems in contests and interviews.",
        months: [3, 6],
        skills: [
          {
            fa: "ساختمان داده", en: "Data structures", kind: "hard",
            whyFa: "انتخاب ساختمان داده یعنی تفاوت بین برنامه‌ای که در یک ثانیه جواب می‌دهد و برنامه‌ای که یک ساعت.",
            whyEn: "The choice of data structure is the difference between a program that answers in a second and one that takes an hour.",
            items: ["Arrays & linked lists", "Stacks & queues", "Hash tables", "Trees & heaps", "Graphs"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "طراحی الگوریتم", en: "Algorithm design", kind: "hard",
            whyFa: "چند الگوی فکری — تقسیم و حل، حریصانه، برنامه‌ریزی پویا — بیشتر مسئله‌ها را می‌پوشانند.",
            whyEn: "A few patterns of thought — divide and conquer, greedy, dynamic programming — cover most problems.",
            items: ["Sorting & searching", "Divide & conquer", "Greedy", "Dynamic programming", "Graph algorithms"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "پیچیدگی محاسباتی", en: "Computational complexity", kind: "hard",
            whyFa: "دانستن اینکه یک مسئله NP-کامل است، جلوی هفته‌ها تلاش برای الگوریتم کامل و سریع را می‌گیرد.",
            whyEn: "Knowing a problem is NP-complete saves weeks of hunting for a fast exact algorithm.",
            items: ["Big-O", "Amortised analysis", "P vs NP", "NP-completeness"],
          },
          {
            fa: "تمرین حل مسئله", en: "Problem-solving practice", kind: "hard",
            whyFa: "مثل ورزش است: فقط با تمرین منظم بهتر می‌شوی؛ و مصاحبه‌های فنی دقیقاً همین را می‌سنجند.",
            whyEn: "Like sport, you only improve with regular practice — and technical interviews test exactly this.",
            items: ["Quera", "LeetCode", "Codeforces", "ICPC-style contests"],
            tracks: ["58-algorithms"],
          },
        ],
      },
      {
        id: "cef-hw",
        fa: "مدار منطقی و معماری کامپیوتر",
        en: "Digital logic and computer architecture",
        outcomeFa: "می‌دانی یک دستور از کد تا ترانزیستور چطور اجرا می‌شود و چرا حافظهٔ نهان سرعت برنامه را تعیین می‌کند.",
        outcomeEn: "You know how an instruction travels from code to transistors and why caches decide a program's speed.",
        months: [3, 6],
        skills: [
          {
            fa: "مدار منطقی", en: "Digital logic", kind: "hard",
            whyFa: "هر پردازنده از گیت و فلیپ‌فلاپ ساخته شده؛ ماشین حالت را اینجا یاد می‌گیری و در نرم‌افزار هم به کار می‌بری.",
            whyEn: "Every processor is built from gates and flip-flops; you learn state machines here and use them in software too.",
            items: ["Boolean algebra", "Combinational & sequential circuits", "Finite state machines", "Verilog basics"],
          },
          {
            fa: "معماری کامپیوتر", en: "Computer architecture", kind: "hard",
            whyFa: "کدی که حافظهٔ نهان را در نظر بگیرد، می‌تواند ده برابر سریع‌تر از کد هم‌ارزش باشد.",
            whyEn: "Cache-aware code can be ten times faster than equivalent code that ignores the cache.",
            items: ["ISA: RISC-V, ARM, x86", "Datapath & control", "Pipelining", "Cache & memory hierarchy", "Virtual memory"],
            tracks: ["24-hardware"],
          },
          {
            fa: "زبان اسمبلی و ریزپردازنده", en: "Assembly and microprocessors", kind: "hard",
            whyFa: "اسمبلی را برای نوشتن یاد نمی‌گیری، برای فهمیدن؛ دیباگ سطح پایین و امنیت بدون آن ممکن نیست.",
            whyEn: "You learn assembly to understand, not to write; low-level debugging and security are impossible without it.",
            items: ["Assembly language", "Interrupts & I/O", "Microcontrollers"],
            tracks: ["43-c"],
          },
          {
            fa: "مدار و الکترونیک پایه", en: "Circuits and basic electronics", kind: "hard",
            whyFa: "مهندس کامپیوتر باید بداند زیر گیت منطقی چه خبر است؛ همین او را از برنامه‌نویس صرف جدا می‌کند.",
            whyEn: "A computer engineer should know what lies beneath a logic gate; that is what sets them apart from a pure programmer.",
            items: ["Circuit analysis", "Transistors as switches", "Lab work"],
            tracks: ["24-hardware"],
          },
        ],
      },
      {
        id: "cef-systems",
        fa: "سیستم‌عامل، شبکه، پایگاه‌داده و کامپایلر",
        en: "Operating systems, networks, databases and compilers",
        outcomeFa: "می‌فهمی برنامه‌ات روی سیستم‌عامل، شبکه و پایگاه‌داده چطور اجرا می‌شود و یک زبان کوچک را تجزیه می‌کنی.",
        outcomeEn: "You understand how your program runs on an OS, a network and a database, and can parse a small language.",
        months: [4, 6],
        skills: [
          {
            fa: "سیستم‌عامل", en: "Operating systems", kind: "hard",
            whyFa: "بن‌بست، شرایط رقابتی و نشت حافظه همه مفهوم‌های سیستم‌عامل‌اند که در برنامه‌های معمولی ظاهر می‌شوند.",
            whyEn: "Deadlocks, race conditions and memory leaks are operating-system concepts that show up in ordinary programs.",
            items: ["Processes & threads", "Scheduling", "Synchronisation & deadlock", "Memory management", "File systems"],
            tracks: ["03-linux-network", "62-virtualization"],
          },
          {
            fa: "شبکه‌های کامپیوتری", en: "Computer networks", kind: "hard",
            whyFa: "تقریباً هر برنامه‌ای امروز با شبکه حرف می‌زند؛ بدون TCP/IP هر خطای اتصال یک معماست.",
            whyEn: "Almost every program talks over a network today; without TCP/IP every connection error is a riddle.",
            items: ["OSI & TCP/IP", "Routing & switching", "TCP / UDP", "DNS & HTTP", "Socket programming"],
            tracks: ["25-network-foundations", "20-realtime"],
          },
          {
            fa: "پایگاه‌داده", en: "Databases", kind: "hard",
            whyFa: "دادهٔ تقریباً هر نرم‌افزاری در یک پایگاه‌داده است؛ طراحی و کوئری درست مهارت روزانه است.",
            whyEn: "Almost every application's data lives in a database; good design and queries are a daily skill.",
            items: ["Relational model", "SQL", "Normalisation", "Transactions", "Indexes"],
            tracks: ["05-sql"],
          },
          {
            fa: "نظریهٔ زبان‌ها و کامپایلر", en: "Formal languages and compilers", kind: "hard",
            whyFa: "عبارت منظم، تجزیه‌گر و کامپایلر همه‌جا هستند — از اعتبارسنجی فرم تا زبان‌های پیکربندی.",
            whyEn: "Regular expressions, parsers and compilers are everywhere — from form validation to configuration languages.",
            items: ["Automata & regular expressions", "Context-free grammars", "Lexing & parsing", "Code generation"],
          },
        ],
      },
      {
        id: "cef-pro",
        fa: "مهارت‌های حرفه‌ای",
        en: "Professional skills",
        outcomeFa: "نمونه‌کار داری، در تیم کار می‌کنی، گزارش و ارائهٔ خوب می‌دهی و گرایشت را آگاهانه انتخاب می‌کنی.",
        outcomeEn: "You have a portfolio, work in a team, write and present well and choose your branch deliberately.",
        months: [2, 4],
        skills: [
          {
            fa: "لینوکس و خط فرمان", en: "Linux and the command line", kind: "hard",
            whyFa: "سرورها، ابزارهای توسعه و بیشتر سیستم‌های تعبیه‌شده لینوکسی‌اند.",
            whyEn: "Servers, development tools and most embedded systems run Linux.",
            items: ["Shell", "Permissions", "Processes", "SSH"],
            tracks: ["03-linux-network"],
          },
          {
            fa: "پروژه و نمونه‌کار", en: "Projects and portfolio", kind: "soft",
            whyFa: "کارفرما مدرک را می‌بیند ولی نمونه‌کار را می‌خواند؛ چند پروژهٔ واقعی روی GitHub از معدل بیشتر حرف می‌زند.",
            whyEn: "Employers glance at degrees but read portfolios; a few real projects on GitHub say more than a GPA.",
            items: ["GitHub portfolio", "Open-source contributions", "Internship"],
            tracks: ["28-git", "38-projects"],
          },
          {
            fa: "نوشتن و ارائه", en: "Writing and presenting", kind: "soft",
            whyFa: "ایدهٔ خوبی که نتوانی توضیحش بدهی، به جایی نمی‌رسد.",
            whyEn: "A good idea you cannot explain goes nowhere.",
            items: ["Reports & theses", "Presentations", "Reading papers"],
            tracks: ["64-docs-writing", "65-presentation"],
          },
          {
            fa: "کار تیمی", en: "Teamwork", kind: "soft",
            whyFa: "نرم‌افزار واقعی کار تیمی است؛ بازبینی کد و جلسه‌های کوتاه منظم، تیم را هم‌راستا نگه می‌دارند.",
            whyEn: "Real software is teamwork; code review and short regular meetings keep a team aligned.",
            items: ["Code review", "Scrum", "Communication"],
            tracks: ["22-skills", "63-scrum-agile"],
          },
          {
            fa: "انتخاب گرایش", en: "Choosing a branch", kind: "soft",
            whyFa: "گرایش را با علاقه و پروژهٔ واقعی انتخاب کن؛ در هر کدام یک پروژهٔ کوچک انجام بده و ببین کدام تو را سر شوق می‌آورد.",
            whyEn: "Choose a branch through interest and real projects; do a small one in each and see which one excites you.",
            items: ["Software", "Computer architecture", "Artificial intelligence", "Networks & IT", "Security"],
          },
        ],
      },
    ],
  },

  /* ═════════════════════ معماری سیستم‌های کامپیوتری ═════════════════════ */
  {
    id: "ce-architecture",
    field: "ce",
    accent: "#9333EA",
    ico: '<rect x="4" y="4" width="16" height="16" rx="2.4"/><rect x="8" y="8" width="8" height="8" rx="1.2"/><path d="M12 8v8M8 12h8" stroke-linecap="round"/><path d="M9 2.4V4M15 2.4V4M9 20v1.6M15 20v1.6M2.4 9H4M2.4 15H4M20 9h1.6M20 15h1.6" stroke-linecap="round"/>',
    after: ["ce-foundations"],
    next: ["embedded", "ee-electronics"],
    fa: {
      name: "معماری سیستم‌های کامپیوتری",
      role: "Computer Architecture / Hardware Engineer",
      intro:
        "گرایش معماری سیستم‌های کامپیوتری (همان گرایش سخت‌افزار) دربارهٔ ساختن خود کامپیوتر است: پردازنده، حافظه، شتاب‌دهنده و تراشه. حالا که هوش مصنوعی به شتاب‌دهندهٔ اختصاصی نیاز دارد و RISC-V طراحی پردازنده را برای همه باز کرده، این گرایش دوباره یکی از هیجان‌انگیزترین‌هاست. این رودمپ از طراحی دیجیتال و HDL تا ریزمعماری، FPGA، طراحی تراشه، رایانش موازی و امنیت سخت‌افزار می‌رود.",
    },
    en: {
      name: "Computer systems architecture",
      role: "Computer Architecture / Hardware Engineer",
      intro:
        "Computer systems architecture (the old hardware track) is about building the computer itself: processors, memory, accelerators and chips. Now that AI needs dedicated accelerators and RISC-V has opened processor design to everyone, it is once again one of the most exciting branches. This roadmap runs from digital design and HDLs to microarchitecture, FPGA, chip design, parallel computing and hardware security.",
    },
    stages: [
      {
        id: "ca-digital",
        fa: "طراحی دیجیتال پیشرفته",
        en: "Advanced digital design",
        outcomeFa: "مدار همگام را با HDL توصیف و شبیه‌سازی می‌کنی و قیدهای زمانی را می‌فهمی.",
        outcomeEn: "You describe and simulate synchronous circuits in an HDL and understand timing constraints.",
        months: [2, 4],
        skills: [
          {
            fa: "زبان توصیف سخت‌افزار", en: "Hardware description languages", kind: "hard",
            whyFa: "HDL برنامه‌نویسی نیست؛ داری سخت‌افزار موازی توصیف می‌کنی. این تغییر ذهنیت سخت‌ترین قدم است.",
            whyEn: "An HDL is not programming; you are describing parallel hardware. That change of mindset is the hardest step.",
            items: ["Verilog / SystemVerilog", "VHDL", "RTL coding style", "Testbenches"],
          },
          {
            fa: "طراحی همگام", en: "Synchronous design", kind: "hard",
            whyFa: "زمان‌بندی setup و hold قانون بی‌رحم سخت‌افزار است؛ کدی که شبیه‌سازی می‌شود لزوماً روی تراشه کار نمی‌کند.",
            whyEn: "Setup and hold timing is hardware's unforgiving law; code that simulates does not necessarily work on silicon.",
            items: ["Setup & hold", "Clock domain crossing", "Finite state machines", "Pipelining"],
          },
          {
            fa: "ابزار شبیه‌سازی", en: "Simulation tools", kind: "hard",
            whyFa: "باگ سخت‌افزاری را در شبیه‌ساز پیدا کن، نه در آزمایشگاه؛ آنجا صد برابر ارزان‌تر است.",
            whyEn: "Find hardware bugs in the simulator, not the lab; it is a hundred times cheaper there.",
            items: ["Icarus Verilog / Verilator", "Questa / ModelSim", "GTKWave", "Vivado simulator"],
          },
        ],
      },
      {
        id: "ca-uarch",
        fa: "ریزمعماری پردازنده",
        en: "Processor microarchitecture",
        outcomeFa: "یک هستهٔ RISC-V خط‌لوله‌ای می‌سازی و می‌فهمی پردازنده‌های امروزی چطور چند دستور را هم‌زمان اجرا می‌کنند.",
        outcomeEn: "You build a pipelined RISC-V core and understand how modern processors execute several instructions at once.",
        months: [3, 5],
        skills: [
          {
            fa: "طراحی مجموعه‌دستور", en: "Instruction set design", kind: "hard",
            whyFa: "ISA قرارداد بین سخت‌افزار و نرم‌افزار است؛ RISC-V متن‌باز است و یادگیری را آسان کرده است.",
            whyEn: "The ISA is the contract between hardware and software; RISC-V is open and has made learning easy.",
            items: ["RISC vs CISC", "RISC-V", "ARM", "x86-64", "Calling conventions"],
          },
          {
            fa: "خط لوله و مخاطره‌ها", en: "Pipelines and hazards", kind: "hard",
            whyFa: "خط لوله سرعت را چند برابر می‌کند ولی مخاطرهٔ داده و کنترل می‌سازد؛ حل آن‌ها قلب طراحی پردازنده است.",
            whyEn: "Pipelining multiplies speed but creates data and control hazards; resolving them is the heart of processor design.",
            items: ["Five-stage pipeline", "Data & control hazards", "Forwarding", "Branch prediction"],
          },
          {
            fa: "اجرای خارج از ترتیب", en: "Out-of-order and superscalar execution", kind: "hard",
            whyFa: "پردازندهٔ گوشی تو دستورها را بی‌ترتیب اجرا می‌کند و به ترتیب تحویل می‌دهد؛ الگوریتم توماسولو پایهٔ آن است.",
            whyEn: "Your phone's processor executes instructions out of order and retires them in order; Tomasulo's algorithm is the basis.",
            items: ["Tomasulo's algorithm", "Register renaming", "Reorder buffer", "Speculative execution"],
          },
          {
            fa: "سلسله‌مراتب حافظه", en: "The memory hierarchy", kind: "hard",
            whyFa: "دیوار حافظه واقعی است: پردازنده صدها برابر سریع‌تر از DRAM است و حافظهٔ نهان این فاصله را پر می‌کند.",
            whyEn: "The memory wall is real: processors are hundreds of times faster than DRAM, and caches bridge the gap.",
            items: ["Cache organisation", "Replacement & write policies", "Coherence (MESI)", "TLB & virtual memory", "DRAM"],
          },
          {
            fa: "ساختن یک پردازنده", en: "Building a CPU", kind: "hard",
            whyFa: "هیچ کتابی مثل ساختن یک هستهٔ RISC-V ساده روی FPGA معماری را یاد نمی‌دهد.",
            whyEn: "No book teaches architecture like building a simple RISC-V core on an FPGA.",
            items: ["Single-cycle RISC-V core", "Pipelined core", "Running C programs on it"],
            tracks: ["43-c"],
          },
        ],
      },
      {
        id: "ca-fpga",
        fa: "FPGA، SoC و شتاب‌دهنده",
        en: "FPGA, SoC and accelerators",
        outcomeFa: "طرح را روی FPGA پیاده می‌کنی، آن را به پردازنده وصل می‌کنی و یک شتاب‌دهندهٔ ساده می‌سازی.",
        outcomeEn: "You implement designs on an FPGA, connect them to a processor and build a simple accelerator.",
        months: [2, 4],
        skills: [
          {
            fa: "پیاده‌سازی روی FPGA", en: "FPGA implementation", kind: "hard",
            whyFa: "FPGA سریع‌ترین راه از ایده تا سخت‌افزار واقعی است؛ در مخابرات، دفاعی و مالی گسترده به کار می‌رود.",
            whyEn: "The FPGA is the fastest route from idea to real hardware; widely used in telecoms, defence and finance.",
            items: ["Vivado / Quartus", "Timing closure", "IP integration", "AXI buses"],
          },
          {
            fa: "طراحی SoC", en: "SoC design", kind: "hard",
            whyFa: "طرح سخت‌افزاری بدون راه‌انداز نرم‌افزاری به کار نمی‌آید؛ طراحی هم‌زمان سخت‌افزار و نرم‌افزار همین پل است.",
            whyEn: "Hardware without a software driver is useless; hardware/software co-design is that bridge.",
            items: ["Zynq and SoC FPGAs", "Hardware/software co-design", "Drivers for custom IP"],
            tracks: ["43-c"],
          },
          {
            fa: "شتاب‌دهنده‌ها", en: "Accelerators", kind: "hard",
            whyFa: "هوش مصنوعی به سخت‌افزار اختصاصی نیاز دارد؛ آرایهٔ سیستولیک پایهٔ بیشتر شتاب‌دهنده‌های یادگیری عمیق است.",
            whyEn: "AI needs dedicated hardware; the systolic array underlies most deep-learning accelerators.",
            items: ["Systolic arrays", "NPUs & TPUs", "High-level synthesis", "Dataflow architectures"],
            tracks: ["60-deep-learning"],
          },
        ],
      },
      {
        id: "ca-chip",
        fa: "طراحی تراشه",
        en: "Chip design",
        outcomeFa: "جریان طراحی تراشهٔ دیجیتال را از RTL تا چیدمان می‌شناسی و در درستی‌سنجی یا پیاده‌سازی فیزیکی عمیق می‌شوی.",
        outcomeEn: "You know the digital chip flow from RTL to layout and go deep in verification or physical implementation.",
        months: [3, 6],
        skills: [
          {
            fa: "جریان طراحی دیجیتال مجتمع", en: "Digital IC flow", kind: "hard", level: "alt",
            whyFa: "از RTL تا چیدمان نهایی؛ هر مرحله قید زمانی، توان و مساحت خودش را دارد.",
            whyEn: "From RTL to final layout; each step has its own timing, power and area constraints.",
            items: ["Synthesis", "Place & route", "Static timing analysis", "Power analysis"],
          },
          {
            fa: "درستی‌سنجی", en: "Verification", kind: "hard", level: "alt",
            whyFa: "باگی که به سیلیکون برسد میلیون‌ها هزینه دارد؛ برای همین تیم درستی‌سنجی معمولاً بزرگ‌تر از تیم طراحی است.",
            whyEn: "A bug that reaches silicon costs millions; that is why verification teams are usually larger than design teams.",
            items: ["UVM", "Coverage", "Formal verification", "SystemVerilog assertions"],
          },
          {
            fa: "جریان متن‌باز", en: "Open-source flow", kind: "hard", level: "opt",
            whyFa: "با ابزار و PDK متن‌باز می‌توانی تا ساخت تراشهٔ واقعی پیش بروی، بدون مجوزهای گران.",
            whyEn: "With open tools and PDKs you can go all the way to a real chip, without expensive licences.",
            items: ["OpenROAD / OpenLane", "SkyWater PDK", "Tiny Tapeout"],
          },
        ],
      },
      {
        id: "ca-parallel",
        fa: "رایانش موازی و کارایی",
        en: "Parallel computing and performance",
        outcomeFa: "برنامه را روی چند هسته و GPU موازی می‌کنی و گلوگاهش را با ابزار پیدا می‌کنی.",
        outcomeEn: "You parallelise programs across cores and GPUs and find their bottlenecks with tools.",
        months: [2, 4],
        skills: [
          {
            fa: "معماری‌های موازی", en: "Parallel architectures", kind: "hard",
            whyFa: "فرکانس پردازنده سال‌هاست بالا نمی‌رود؛ سرعت امروز از موازی‌سازی می‌آید.",
            whyEn: "Clock speeds stopped rising years ago; today's speed comes from parallelism.",
            items: ["Multicore", "SIMD & vector units", "GPU architecture", "Interconnects"],
          },
          {
            fa: "برنامه‌نویسی موازی", en: "Parallel programming", kind: "hard",
            whyFa: "CUDA زبان عملی GPU است و MPI زبان ابرکامپیوترها.",
            whyEn: "CUDA is the practical language of GPUs and MPI the language of supercomputers.",
            items: ["Threads & OpenMP", "CUDA", "MPI", "Performance counters"],
            tracks: ["44-cpp"],
          },
          {
            fa: "تحلیل کارایی", en: "Performance analysis", kind: "hard",
            whyFa: "مدل roofline در یک نگاه می‌گوید برنامه‌ات گرفتار محاسبه است یا حافظه.",
            whyEn: "The roofline model shows at a glance whether your program is compute-bound or memory-bound.",
            items: ["Roofline model", "Profiling: perf, VTune", "Amdahl's law"],
          },
        ],
      },
      {
        id: "ca-sec",
        fa: "امنیت سخت‌افزار و لایهٔ سیستم",
        en: "Hardware security and the system layer",
        outcomeFa: "حمله‌های سطح سخت‌افزار را می‌شناسی و راه‌انداز و لایهٔ پایین سیستم‌عامل را می‌فهمی.",
        outcomeEn: "You know hardware-level attacks and understand drivers and the lower layers of the OS.",
        months: [1, 3],
        skills: [
          {
            fa: "امنیت سخت‌افزار", en: "Hardware security", kind: "hard",
            whyFa: "Spectre و Meltdown نشان دادند بهینه‌سازی سخت‌افزاری می‌تواند راز را لو بدهد.",
            whyEn: "Spectre and Meltdown showed that hardware optimisations can leak secrets.",
            items: ["Side-channel attacks", "Spectre & Meltdown", "Hardware Trojans", "Secure boot & TPM"],
          },
          {
            fa: "واسط با سیستم‌عامل", en: "The OS interface", kind: "hard",
            whyFa: "سخت‌افزار جدید بدون راه‌انداز و فهم وقفه و DMA، برای سیستم‌عامل وجود ندارد.",
            whyEn: "New hardware does not exist to the OS without a driver and an understanding of interrupts and DMA.",
            items: ["Device drivers", "Interrupts & DMA", "Linux kernel basics"],
            tracks: ["03-linux-network"],
          },
          {
            fa: "تحمل‌پذیری خطا", en: "Fault tolerance", kind: "hard", level: "opt",
            whyFa: "در فضا، خودرو و پزشکی، یک بیت که عوض شود می‌تواند فاجعه باشد؛ افزونگی و کد تصحیح خطا جلویش را می‌گیرند.",
            whyEn: "In space, cars and medicine a single flipped bit can be a disaster; redundancy and error-correcting codes prevent it.",
            items: ["Error-correcting codes", "Redundancy", "Radiation effects"],
          },
        ],
      },
      {
        id: "ca-career",
        fa: "حرفه",
        en: "The profession",
        outcomeFa: "مقاله و مشخصات فنی را از منبع می‌خوانی و مسیر شغلی‌ات را می‌شناسی.",
        outcomeEn: "You read papers and specifications at the source and know your career options.",
        months: [1, 2],
        skills: [
          {
            fa: "خواندن مقاله و مشخصات", en: "Reading papers and specs", kind: "soft",
            whyFa: "معماری با مقاله‌های کنفرانس جلو می‌رود و پیاده‌سازی با متن مشخصات؛ هر دو را باید روان بخوانی.",
            whyEn: "Architecture advances through conference papers and implementation through specifications; you must read both fluently.",
            items: ["ISCA / MICRO / HPCA", "RISC-V specifications", "Datasheets"],
          },
          {
            fa: "مسیرهای شغلی", en: "Career paths", kind: "soft",
            whyFa: "شرکت‌های طراحی تراشه، صنایع FPGA و دفاعی، اینترنت اشیا، سخت‌افزار هوش مصنوعی یا پژوهش — هر کدام بخشی از این رودمپ را پررنگ می‌کند.",
            whyEn: "Chip design houses, FPGA and defence industries, IoT, AI hardware or research — each emphasises a different part of this roadmap.",
            items: ["Chip design", "FPGA & defence", "Embedded & IoT", "HPC & AI hardware", "Graduate study"],
          },
        ],
      },
    ],
  },

  /* ═══════════════════════════ هوش مصنوعی و رباتیک ═══════════════════════════ */
  {
    id: "ce-ai",
    field: "ce",
    accent: "#16A34A",
    ico: '<circle cx="5.5" cy="7" r="2"/><circle cx="5.5" cy="17" r="2"/><circle cx="12" cy="12" r="2.2"/><circle cx="18.5" cy="7" r="2"/><circle cx="18.5" cy="17" r="2"/><path d="m7.2 8.1 3.1 2.6M7.2 15.9l3.1-2.6M13.7 10.7l3.1-2.6M13.7 13.3l3.1 2.6" stroke-linecap="round"/>',
    after: ["ce-foundations"],
    next: ["ee-control", "databases"],
    fa: {
      name: "هوش مصنوعی و رباتیک",
      role: "AI / ML Engineer",
      intro:
        "هوش مصنوعی و رباتیک دربارهٔ ساختن سیستم‌هایی است که یاد می‌گیرند، می‌بینند، می‌فهمند و عمل می‌کنند. موج مدل‌های زبانی بزرگ این رشته را پرطرفدارترین حوزهٔ کامپیوتر کرده، ولی پایه‌اش تغییر نکرده: ریاضیات، آمار، یادگیری ماشین و مهندسی داده. این رودمپ از همان پایه شروع می‌کند و تا یادگیری عمیق، بینایی ماشین، پردازش زبان، یادگیری تقویتی، رباتیک و به‌کارگیری مدل‌ها در تولید پیش می‌رود.",
    },
    en: {
      name: "Artificial intelligence and robotics",
      role: "AI / ML Engineer",
      intro:
        "AI and robotics are about building systems that learn, see, understand and act. The wave of large language models has made this the most popular area of computing, but its foundations have not changed: mathematics, statistics, machine learning and data engineering. This roadmap starts from those foundations and goes on to deep learning, computer vision, language processing, reinforcement learning, robotics and putting models into production.",
    },
    stages: [
      {
        id: "ai-math",
        fa: "ریاضیات هوش مصنوعی",
        en: "The mathematics of AI",
        outcomeFa: "می‌فهمی گرادیان کاهشی چرا کار می‌کند و مدل آماری را با زبان احتمال توصیف می‌کنی.",
        outcomeEn: "You understand why gradient descent works and describe statistical models in the language of probability.",
        months: [3, 5],
        skills: [
          {
            fa: "جبر خطی", en: "Linear algebra", kind: "hard",
            whyFa: "هر شبکهٔ عصبی زنجیره‌ای از ضرب ماتریس است؛ SVD و PCA زیر بسیاری از روش‌ها نشسته‌اند.",
            whyEn: "Every neural network is a chain of matrix multiplications; SVD and PCA sit under many methods.",
            items: ["Vectors & matrices", "Matrix calculus", "SVD & PCA", "Eigendecomposition"],
          },
          {
            fa: "حسابان و بهینه‌سازی", en: "Calculus and optimisation", kind: "hard",
            whyFa: "آموزش مدل یعنی کمینه کردن یک تابع خطا؛ پس‌انتشار چیزی جز قاعدهٔ زنجیره‌ای نیست.",
            whyEn: "Training a model means minimising a loss function; backpropagation is nothing but the chain rule.",
            items: ["Gradients", "Chain rule & backpropagation", "Gradient descent & variants", "Convexity"],
          },
          {
            fa: "آمار و احتمال", en: "Probability and statistics", kind: "hard",
            whyFa: "مدل یادگیری ماشین یک برآوردگر آماری است؛ بدون آمار، نتیجهٔ خوب را از شانس تشخیص نمی‌دهی.",
            whyEn: "A machine-learning model is a statistical estimator; without statistics you cannot tell a good result from luck.",
            items: ["Bayes' rule", "MLE & MAP", "Distributions", "Information theory basics"],
          },
        ],
      },
      {
        id: "ai-tools",
        fa: "پایتون و داده",
        en: "Python and data",
        outcomeFa: "داده را بارگذاری، تمیز و تصویرسازی می‌کنی و آزمایش‌هایت قابل تکرارند.",
        outcomeEn: "You load, clean and visualise data, and your experiments are reproducible.",
        months: [2, 3],
        skills: [
          {
            fa: "پایتون علمی", en: "Scientific Python", kind: "hard",
            whyFa: "زبان عملی هوش مصنوعی پایتون است و ابزارهای اصلی‌اش همین چهار تا.",
            whyEn: "Python is the practical language of AI, and these four are its core tools.",
            items: ["NumPy", "pandas", "Matplotlib / seaborn", "Jupyter"],
            tracks: ["12-python"],
          },
          {
            fa: "کار با داده", en: "Data wrangling", kind: "hard",
            whyFa: "بیشتر زمان یک پروژهٔ واقعی صرف داده می‌شود، نه مدل؛ دادهٔ بد، مدل خوب را هم خراب می‌کند.",
            whyEn: "Most of a real project's time goes into data, not models; bad data ruins even a good model.",
            items: ["Cleaning & missing values", "Feature engineering", "Visualisation", "SQL for data"],
            tracks: ["05-sql"],
          },
          {
            fa: "آزمایش قابل تکرار", en: "Reproducible experiments", kind: "hard",
            whyFa: "نتیجه‌ای که نتوانی دوباره بسازی، نتیجه نیست؛ نسخه‌بندی کد، محیط و آزمایش را جدی بگیر.",
            whyEn: "A result you cannot reproduce is not a result; version your code, environment and experiments.",
            items: ["Git", "uv / conda environments", "MLflow / Weights & Biases"],
            tracks: ["28-git"],
          },
        ],
      },
      {
        id: "ai-ml",
        fa: "یادگیری ماشین کلاسیک",
        en: "Classical machine learning",
        outcomeFa: "برای دادهٔ جدولی مدل می‌سازی، درست ارزیابی‌اش می‌کنی و بیش‌برازش را تشخیص می‌دهی.",
        outcomeEn: "You build models for tabular data, evaluate them properly and spot overfitting.",
        months: [3, 5],
        skills: [
          {
            fa: "یادگیری با ناظر", en: "Supervised learning", kind: "hard",
            whyFa: "روی دادهٔ جدولی، درخت‌های تقویت‌شده هنوز اغلب از شبکهٔ عصبی بهترند.",
            whyEn: "On tabular data, gradient-boosted trees still often beat neural networks.",
            items: ["Linear & logistic regression", "Decision trees & random forests", "Gradient boosting (XGBoost, LightGBM)", "SVM", "k-NN"],
            tracks: ["59-machine-learning"],
          },
          {
            fa: "یادگیری بی‌ناظر", en: "Unsupervised learning", kind: "hard",
            whyFa: "بیشتر داده‌های دنیا برچسب ندارند؛ خوشه‌بندی و کاهش بعد ساختار پنهانشان را نشان می‌دهند.",
            whyEn: "Most of the world's data is unlabelled; clustering and dimensionality reduction reveal its hidden structure.",
            items: ["k-means", "Hierarchical clustering", "PCA", "Anomaly detection"],
            tracks: ["59-machine-learning"],
          },
          {
            fa: "ارزیابی مدل", en: "Model evaluation", kind: "hard",
            whyFa: "دقت بالا روی دادهٔ آموزش هیچ معنایی ندارد؛ نشت داده رایج‌ترین دلیل نتیجه‌های «خیلی خوب برای واقعی بودن» است.",
            whyEn: "High accuracy on training data means nothing; data leakage is the commonest reason for results that are too good to be true.",
            items: ["Train / validation / test", "Cross-validation", "Precision, recall & F1", "Overfitting & regularisation", "Data leakage"],
          },
          {
            fa: "scikit-learn", en: "scikit-learn", kind: "hard",
            whyFa: "کتابخانهٔ استاندارد یادگیری ماشین کلاسیک؛ pipeline جلوی نشت داده بین آموزش و آزمون را می‌گیرد.",
            whyEn: "The standard classical-ML library; pipelines prevent leakage between training and testing.",
            items: ["Estimators", "Pipelines", "Hyperparameter search"],
            tracks: ["59-machine-learning"],
          },
        ],
      },
      {
        id: "ai-dl",
        fa: "یادگیری عمیق",
        en: "Deep learning",
        outcomeFa: "شبکهٔ عصبی را از صفر می‌فهمی و با PyTorch مدل بینایی و ترنسفورمر آموزش می‌دهی.",
        outcomeEn: "You understand neural networks from scratch and train vision models and Transformers in PyTorch.",
        months: [3, 6],
        skills: [
          {
            fa: "شبکهٔ عصبی", en: "Neural networks", kind: "hard",
            whyFa: "پیش از کتابخانه، یک شبکهٔ کوچک را با دست بساز؛ بعد هیچ خطای آموزشی برایت جعبهٔ سیاه نیست.",
            whyEn: "Before any library, build a small network by hand; after that no training failure is a black box.",
            items: ["Perceptron & MLP", "Backpropagation", "Activation functions", "Initialisation & normalisation", "Adam and other optimisers"],
            tracks: ["60-deep-learning"],
          },
          {
            fa: "PyTorch", en: "PyTorch", kind: "hard", level: "alt",
            whyFa: "چارچوب غالب پژوهش و بیشتر پروژه‌های صنعتی امروز.",
            whyEn: "The dominant framework in research and most industrial projects today.",
            items: ["Tensors & autograd", "nn.Module", "DataLoader", "GPU training"],
            tracks: ["60-deep-learning"],
          },
          {
            fa: "TensorFlow و Keras", en: "TensorFlow and Keras", kind: "hard", level: "alt",
            whyFa: "در کدهای موجود و برخی سازمان‌ها هنوز رایج است؛ Keras رابط سطح بالای ساده‌ای دارد.",
            whyEn: "Still common in existing code and some organisations; Keras offers a simple high-level API.",
            items: ["Keras API", "tf.data", "TensorFlow Lite"],
          },
          {
            fa: "شبکهٔ کانولوشنی", en: "Convolutional networks", kind: "hard",
            whyFa: "پایهٔ بینایی ماشین؛ یادگیری انتقالی اجازه می‌دهد با دادهٔ کم هم مدل خوب بسازی.",
            whyEn: "The basis of computer vision; transfer learning lets you build good models even with little data.",
            items: ["Convolutions & pooling", "ResNet", "Transfer learning", "Data augmentation"],
          },
          {
            fa: "مدل‌های دنباله و ترنسفورمر", en: "Sequence models and Transformers", kind: "hard",
            whyFa: "ترنسفورمر معماری پشت همهٔ مدل‌های زبانی بزرگ است؛ و مکانیزم توجه قلب آن.",
            whyEn: "The Transformer is the architecture behind every large language model; attention is its heart.",
            items: ["RNN / LSTM", "Attention", "Transformer architecture", "Positional encoding"],
            tracks: ["60-deep-learning"],
          },
        ],
      },
      {
        id: "ai-apps",
        fa: "حوزه‌های کاربردی",
        en: "Application areas",
        outcomeFa: "در یک حوزه — بینایی، زبان، صوت یا تصمیم‌گیری — پروژهٔ کامل و قابل دفاع می‌سازی.",
        outcomeEn: "You build a complete, defensible project in one area — vision, language, speech or decision-making.",
        months: [3, 6],
        skills: [
          {
            fa: "بینایی ماشین", en: "Computer vision", kind: "hard", level: "alt",
            whyFa: "از کنترل کیفیت در کارخانه تا تصویربرداری پزشکی؛ بازار کار عملی و بزرگی دارد.",
            whyEn: "From factory quality control to medical imaging; a large, practical job market.",
            items: ["Image classification", "Object detection (YOLO)", "Segmentation", "OpenCV"],
          },
          {
            fa: "پردازش زبان طبیعی", en: "Natural language processing", kind: "hard", level: "alt",
            whyFa: "زبان فارسی چالش‌های خودش را دارد — نیم‌فاصله، ریخت‌شناسی، دادهٔ کم — و کار روی آن ارزش ویژه دارد.",
            whyEn: "Persian has its own challenges — zero-width non-joiners, morphology, scarce data — and work on it is especially valuable.",
            items: ["Tokenisation", "Embeddings", "Fine-tuning (LoRA)", "Persian NLP: Hazm, ParsBERT"],
          },
          {
            fa: "یادگیری تقویتی", en: "Reinforcement learning", kind: "hard", level: "opt",
            whyFa: "برای تصمیم‌گیری پی‌درپی — بازی، رباتیک، کنترل — و بخشی از آموزش مدل‌های زبانی امروزی.",
            whyEn: "For sequential decisions — games, robotics, control — and part of how today's language models are trained.",
            items: ["Markov decision processes", "Q-learning", "Policy gradients", "Gymnasium"],
          },
          {
            fa: "مدل‌های مولد", en: "Generative models", kind: "hard", level: "opt",
            whyFa: "مدل‌های پخشی پشت تولید تصویر امروزی‌اند؛ VAE و GAN نیاکان آن‌ها.",
            whyEn: "Diffusion models are behind today's image generation; VAEs and GANs are their ancestors.",
            items: ["VAEs", "GANs", "Diffusion models"],
          },
          {
            fa: "پردازش گفتار", en: "Speech processing", kind: "hard", level: "opt",
            whyFa: "دستیار صوتی، زیرنویس خودکار و تبدیل متن به گفتار — همه برای فارسی هنوز جای کار دارند.",
            whyEn: "Voice assistants, automatic captions and text-to-speech — all still have room to grow for Persian.",
            items: ["Speech recognition", "Text-to-speech", "Whisper"],
          },
        ],
      },
      {
        id: "ai-llm",
        fa: "مهندسی هوش مصنوعی و مدل‌های زبانی",
        en: "AI engineering and language models",
        outcomeFa: "یک اپ مبتنی بر مدل زبانی با بازیابی اطلاعات می‌سازی، ارزیابی‌اش می‌کنی و در تولید اجرایش می‌کنی.",
        outcomeEn: "You build a retrieval-augmented language-model app, evaluate it and run it in production.",
        months: [2, 4],
        skills: [
          {
            fa: "اپ‌های مبتنی بر LLM", en: "LLM applications", kind: "hard",
            whyFa: "بیشتر شرکت‌ها مدل نمی‌سازند، مدل را به کار می‌گیرند؛ RAG و ارزیابی مهارت اصلی این کار است.",
            whyEn: "Most companies do not build models, they apply them; RAG and evaluation are the core skills.",
            items: ["Prompt engineering", "RAG", "Vector databases", "Tool use & agents", "Evaluation"],
            tracks: ["61-ai-engineering"],
          },
          {
            fa: "استقرار و MLOps", en: "Serving and MLOps", kind: "hard",
            whyFa: "مدلی که فقط در نوت‌بوک کار کند، محصول نیست؛ مدل در تولید باید پایش شود چون داده عوض می‌شود.",
            whyEn: "A model that only works in a notebook is not a product; production models must be monitored because data drifts.",
            items: ["Model serving (FastAPI, vLLM)", "Docker", "Monitoring & drift", "CI/CD for ML"],
            tracks: ["56-fastapi", "01-docker", "61-ai-engineering"],
          },
          {
            fa: "بهینه‌سازی مدل", en: "Model efficiency", kind: "hard", level: "opt",
            whyFa: "برای اجرای مدل روی گوشی یا سرور ارزان، کوانتیزه کردن و تقطیر حجم و هزینه را چند برابر کم می‌کنند.",
            whyEn: "To run models on phones or cheap servers, quantisation and distillation cut size and cost several times over.",
            items: ["Quantisation", "Distillation", "ONNX", "Edge deployment"],
          },
        ],
      },
      {
        id: "ai-robot",
        fa: "هوش مصنوعی کلاسیک و رباتیک",
        en: "Classical AI and robotics",
        outcomeFa: "مسئلهٔ جستجو و برنامه‌ریزی را حل می‌کنی و یک ربات را در شبیه‌ساز با درک محیط هدایت می‌کنی.",
        outcomeEn: "You solve search and planning problems and guide a simulated robot using perception.",
        months: [2, 4],
        skills: [
          {
            fa: "هوش مصنوعی کلاسیک", en: "Classical AI", kind: "hard",
            whyFa: "جستجو و برنامه‌ریزی هنوز در مسیریابی، زمان‌بندی و بازی‌ها حرف اول را می‌زنند.",
            whyEn: "Search and planning still lead in routing, scheduling and games.",
            items: ["Search (A*)", "Constraint satisfaction", "Planning", "Knowledge representation"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "رباتیک", en: "Robotics", kind: "hard",
            whyFa: "ربات جایی است که هوش مصنوعی باید با دنیای فیزیکی و نامطمئن کنار بیاید.",
            whyEn: "Robots are where AI must cope with the physical, uncertain world.",
            items: ["ROS 2", "SLAM", "Motion planning", "Perception"],
          },
          {
            fa: "سیستم‌های چندعاملی", en: "Multi-agent systems", kind: "hard", level: "opt",
            whyFa: "از رباتیک گروهی تا عامل‌های نرم‌افزاری که با هم همکاری می‌کنند.",
            whyEn: "From swarm robotics to software agents that cooperate.",
            items: ["Game theory basics", "Coordination", "Multi-agent RL"],
          },
        ],
      },
      {
        id: "ai-pro",
        fa: "پژوهش، اخلاق و حرفه",
        en: "Research, ethics and the profession",
        outcomeFa: "مقاله می‌خوانی و بازتولید می‌کنی، پیامد اخلاقی مدلت را می‌سنجی و نتیجه را برای غیرمتخصص توضیح می‌دهی.",
        outcomeEn: "You read and reproduce papers, weigh your model's ethical impact and explain results to non-experts.",
        months: [1, 3],
        skills: [
          {
            fa: "خواندن و بازتولید مقاله", en: "Reading and reproducing papers", kind: "soft",
            whyFa: "این رشته هر ماه عوض می‌شود؛ کسی جلو می‌ماند که مقاله را بخواند و نتیجه‌اش را خودش بسازد.",
            whyEn: "The field changes every month; those who read papers and rebuild their results stay ahead.",
            items: ["arXiv", "Reproducing results", "Ablation studies"],
          },
          {
            fa: "اخلاق و هوش مصنوعی مسئولانه", en: "Ethics and responsible AI", kind: "soft",
            whyFa: "مدلی که روی دادهٔ سوگیرانه آموزش ببیند، تبعیض را خودکار می‌کند؛ قانون‌گذاری هم دارد سخت‌گیرتر می‌شود.",
            whyEn: "A model trained on biased data automates discrimination; regulation is also getting stricter.",
            items: ["Bias & fairness", "Privacy", "Explainability", "EU AI Act"],
          },
          {
            fa: "توضیح نتیجه", en: "Communicating results", kind: "soft",
            whyFa: "مدیر عدد F1 نمی‌خواهد؛ می‌خواهد بداند مدل چه تصمیمی را بهتر می‌کند و کجا اشتباه می‌کند.",
            whyEn: "Managers do not want an F1 score; they want to know which decision the model improves and where it fails.",
            items: ["Visualising results", "Writing reports", "Presenting to non-experts"],
            tracks: ["65-presentation"],
          },
          {
            fa: "مسیرهای شغلی", en: "Career paths", kind: "soft",
            whyFa: "مهندس یادگیری ماشین، دانشمند داده، پژوهشگر یا مهندس محصول هوش مصنوعی — هر کدام ترکیب متفاوتی از این رودمپ است.",
            whyEn: "ML engineer, data scientist, researcher or AI product engineer — each is a different mix of this roadmap.",
            items: ["ML engineer", "Data scientist", "Research scientist", "AI product engineer", "Graduate study"],
          },
        ],
      },
    ],
  },

  /* ════════════════════════════════ امنیت ════════════════════════════════ */
  {
    id: "ce-security",
    field: "ce",
    accent: "#DC2626",
    ico: '<path d="M12 2.8 4.4 5.8v5.6c0 4.6 3.2 8.4 7.6 9.8 4.4-1.4 7.6-5.2 7.6-9.8V5.8z" stroke-linejoin="round"/><rect x="9" y="11" width="6" height="4.8" rx="1"/><path d="M10.2 11V9.6a1.8 1.8 0 0 1 3.6 0V11"/>',
    after: ["ce-foundations"],
    next: ["devops", "network-engineer"],
    fa: {
      name: "امنیت سایبری",
      role: "Security Engineer",
      intro:
        "امنیت یعنی مثل مهاجم فکر کنی تا بتوانی مثل مدافع بسازی. این رشته روی شبکه، سیستم‌عامل، برنامه‌نویسی و رمزنگاری سوار است — پس میان‌بر ندارد. این رودمپ از همان پایه‌ها شروع می‌کند و دو شاخهٔ اصلی را باز می‌کند: تیم قرمز (تست نفوذ و تحقیقات آسیب‌پذیری) و تیم آبی (پایش، پاسخ به رخداد و امن‌سازی)، به‌اضافهٔ امنیت ابر، توسعهٔ امن، و مهم‌تر از همه: اخلاق و قانون.",
    },
    en: {
      name: "Cyber security",
      role: "Security Engineer",
      intro:
        "Security means thinking like an attacker so you can build like a defender. The field rides on networking, operating systems, programming and cryptography — so there are no shortcuts. This roadmap starts from those foundations and opens the two main branches: red team (penetration testing and vulnerability research) and blue team (monitoring, incident response and hardening), plus cloud security, secure development and, above all, ethics and law.",
    },
    stages: [
      {
        id: "sec-base",
        fa: "پایه‌ها",
        en: "Foundations",
        outcomeFa: "ترافیک شبکه را می‌خوانی، در لینوکس و ویندوز راحتی و اسکریپت خودکارسازی می‌نویسی.",
        outcomeEn: "You read network traffic, are at home on Linux and Windows and write automation scripts.",
        months: [3, 5],
        skills: [
          {
            fa: "شبکه", en: "Networking", kind: "hard",
            whyFa: "بیشتر حمله‌ها از شبکه می‌آیند؛ کسی که بسته را در Wireshark نخواند، حمله را نمی‌بیند.",
            whyEn: "Most attacks arrive over the network; someone who cannot read packets in Wireshark will not see them.",
            items: ["TCP/IP", "DNS, HTTP & TLS", "Subnetting", "Wireshark"],
            tracks: ["25-network-foundations"],
          },
          {
            fa: "درونیات لینوکس و ویندوز", en: "Linux and Windows internals", kind: "hard",
            whyFa: "ارتقای دسترسی یعنی سوءاستفاده از جزئیات سیستم‌عامل؛ و Active Directory قلب شبکهٔ هر سازمان است.",
            whyEn: "Privilege escalation means abusing operating-system details; Active Directory is the heart of every organisation's network.",
            items: ["Linux CLI", "Permissions & processes", "Active Directory basics", "PowerShell"],
            tracks: ["03-linux-network"],
          },
          {
            fa: "برنامه‌نویسی و اسکریپت", en: "Programming and scripting", kind: "hard",
            whyFa: "ابزار آماده همیشه کافی نیست؛ متخصص امنیت باید کد بخواند، باگ پیدا کند و ابزار خودش را بنویسد.",
            whyEn: "Ready-made tools are never enough; a security specialist must read code, find bugs and write their own tools.",
            items: ["Python", "Bash", "C and memory", "Reading code"],
            tracks: ["12-python", "43-c"],
          },
          {
            fa: "مبانی وب", en: "Web fundamentals", kind: "hard",
            whyFa: "بزرگ‌ترین سطح حملهٔ امروز، اپ‌های وب و APIها هستند.",
            whyEn: "Web apps and APIs are today's largest attack surface.",
            items: ["HTTP", "Cookies & sessions", "Same-origin policy", "REST APIs"],
            tracks: ["26-web-foundations"],
          },
        ],
      },
      {
        id: "sec-crypto",
        fa: "رمزنگاری کاربردی",
        en: "Applied cryptography",
        outcomeFa: "می‌دانی کدام الگوریتم برای چه کاری است، TLS را از درون می‌فهمی و خطاهای رایج رمزنگاری را می‌شناسی.",
        outcomeEn: "You know which algorithm is for what, understand TLS from the inside and recognise common crypto mistakes.",
        months: [1, 3],
        skills: [
          {
            fa: "رمزنگاری متقارن و نامتقارن", en: "Symmetric and asymmetric crypto", kind: "hard",
            whyFa: "هر اتصال امن ترکیبی از این دو است: نامتقارن برای توافق کلید، متقارن برای داده.",
            whyEn: "Every secure connection combines both: asymmetric for key agreement, symmetric for data.",
            items: ["AES", "RSA & ECC", "Diffie–Hellman", "Hashes & MACs", "Digital signatures"],
          },
          {
            fa: "PKI و TLS", en: "PKI and TLS", kind: "hard",
            whyFa: "گواهی اشتباه یعنی حملهٔ مرد میانی؛ باید بدانی زنجیرهٔ اعتماد چطور کار می‌کند.",
            whyEn: "A wrong certificate means a man-in-the-middle; you must know how the chain of trust works.",
            items: ["Certificates", "TLS handshake", "Certificate pinning", "Let's Encrypt"],
            tracks: ["02-nginx"],
          },
          {
            fa: "خطاهای رایج رمزنگاری", en: "Common crypto mistakes", kind: "hard",
            whyFa: "رمزنگاری را خودت اختراع نکن؛ بیشتر نشت‌ها از استفادهٔ اشتباه الگوریتم درست است، نه از شکستن ریاضی.",
            whyEn: "Never roll your own crypto; most leaks come from misusing sound algorithms, not from breaking the maths.",
            items: ["Rolling your own crypto", "ECB mode", "Password hashing (Argon2, bcrypt)", "Key management"],
          },
        ],
      },
      {
        id: "sec-web",
        fa: "امنیت وب و توسعهٔ امن",
        en: "Web security and secure development",
        outcomeFa: "آسیب‌پذیری‌های رایج وب را پیدا و اصلاح می‌کنی و امنیت را در چرخهٔ توسعه جا می‌دهی.",
        outcomeEn: "You find and fix common web vulnerabilities and build security into the development cycle.",
        months: [2, 4],
        skills: [
          {
            fa: "OWASP Top 10", en: "OWASP Top 10", kind: "hard",
            whyFa: "فهرست پرتکرارترین خطاهای امنیتی وب؛ از کنترل دسترسی شکسته تا تزریق.",
            whyEn: "The list of the most frequent web security failures; from broken access control to injection.",
            items: ["Broken access control", "Injection", "XSS", "SSRF", "Security misconfiguration"],
          },
          {
            fa: "ابزار تست وب", en: "Web testing tools", kind: "hard",
            whyFa: "Burp Suite ابزار روزمرهٔ هر متخصص امنیت وب است.",
            whyEn: "Burp Suite is every web security specialist's daily tool.",
            items: ["Burp Suite", "OWASP ZAP", "sqlmap"],
          },
          {
            fa: "توسعهٔ امن", en: "Secure development", kind: "hard",
            whyFa: "باگ امنیتی که در طراحی گرفته شود، صد برابر ارزان‌تر از باگی است که در تولید پیدا شود.",
            whyEn: "A security bug caught in design is a hundred times cheaper than one found in production.",
            items: ["Threat modelling (STRIDE)", "Security code review", "SAST / DAST", "Dependency scanning"],
            tracks: ["04-devops"],
          },
          {
            fa: "امنیت API", en: "API security", kind: "hard",
            whyFa: "API مستقیم به داده دسترسی دارد؛ JWT پیاده‌سازی‌شده با اشتباه، در را برای همه باز می‌کند.",
            whyEn: "APIs reach data directly; a badly implemented JWT opens the door to everyone.",
            items: ["JWT pitfalls", "Rate limiting", "OWASP API Top 10"],
          },
        ],
      },
      {
        id: "sec-red",
        fa: "تیم قرمز: تست نفوذ",
        en: "Red team: penetration testing",
        outcomeFa: "با مجوز، یک تست نفوذ کامل از شناسایی تا گزارش انجام می‌دهی.",
        outcomeEn: "With authorisation, you run a complete penetration test from reconnaissance to report.",
        months: [3, 6],
        skills: [
          {
            fa: "روش‌شناسی تست نفوذ", en: "Penetration testing methodology", kind: "hard",
            whyFa: "تست نفوذ بدون روش، فقط بازی با ابزار است؛ روش است که نتیجه را کامل و قابل تکرار می‌کند.",
            whyEn: "Pentesting without a method is just playing with tools; the method makes results complete and repeatable.",
            items: ["Reconnaissance", "Scanning (Nmap)", "Exploitation", "Post-exploitation", "Reporting"],
          },
          {
            fa: "حمله به شبکه و Active Directory", en: "Network and Active Directory attacks", kind: "hard",
            whyFa: "در بیشتر نفوذهای واقعی به سازمان‌ها، مسیر مهاجم از Active Directory می‌گذرد.",
            whyEn: "In most real breaches of organisations, the attacker's path runs through Active Directory.",
            items: ["Metasploit", "Active Directory attacks", "Privilege escalation", "Lateral movement"],
          },
          {
            fa: "آزمایشگاه تمرین", en: "Practice labs", kind: "hard",
            whyFa: "مهارت نفوذ فقط با تمرین روی ماشین‌هایی ساخته می‌شود که مجاز به حمله‌شان هستی.",
            whyEn: "Offensive skill is only built by practising on machines you are allowed to attack.",
            items: ["Hack The Box", "TryHackMe", "CTF competitions"],
            tracks: ["62-virtualization"],
          },
          {
            fa: "مهندسی معکوس", en: "Reverse engineering", kind: "hard", level: "opt",
            whyFa: "برای تحلیل بدافزار و کشف آسیب‌پذیری در نرم‌افزار بدون کد منبع.",
            whyEn: "For analysing malware and finding vulnerabilities in software without source code.",
            items: ["x86 assembly", "Ghidra / IDA", "Buffer overflows", "Malware analysis basics"],
          },
        ],
      },
      {
        id: "sec-blue",
        fa: "تیم آبی: دفاع و پاسخ",
        en: "Blue team: defence and response",
        outcomeFa: "حمله را در لاگ‌ها تشخیص می‌دهی، به رخداد پاسخ می‌دهی و سیستم را امن‌سازی می‌کنی.",
        outcomeEn: "You detect attacks in logs, respond to incidents and harden systems.",
        months: [3, 6],
        skills: [
          {
            fa: "پایش و SIEM", en: "Monitoring and SIEM", kind: "hard",
            whyFa: "مهاجم دیر یا زود وارد می‌شود؛ مهم این است که چقدر زود ببینی‌اش.",
            whyEn: "Attackers get in sooner or later; what matters is how soon you see them.",
            items: ["Logging", "SIEM (Wazuh, Elastic, Splunk)", "Sigma detection rules", "SOC workflow"],
            tracks: ["19-elasticsearch"],
          },
          {
            fa: "پاسخ به رخداد", en: "Incident response", kind: "hard",
            whyFa: "در ساعت اول یک رخداد، دستورالعمل آماده از هر مهارت فنی ارزشمندتر است.",
            whyEn: "In the first hour of an incident, a ready playbook is worth more than any technical skill.",
            items: ["IR lifecycle", "Triage", "Forensics basics", "Playbooks"],
          },
          {
            fa: "امن‌سازی", en: "Hardening", kind: "hard",
            whyFa: "بیشتر نفوذها از پیکربندی پیش‌فرض و وصلهٔ نصب‌نشده‌اند، نه از حملهٔ پیچیده.",
            whyEn: "Most breaches come from default configurations and missing patches, not sophisticated attacks.",
            items: ["CIS benchmarks", "Patch management", "Least privilege", "Segmentation & firewalls"],
            tracks: ["03-linux-network", "21-proxy-vpn"],
          },
          {
            fa: "هوش تهدید", en: "Threat intelligence", kind: "hard", level: "opt",
            whyFa: "MITRE ATT&CK زبان مشترک توصیف رفتار مهاجم است؛ شکار تهدید یعنی پیدا کردن مهاجم پیش از هشدار.",
            whyEn: "MITRE ATT&CK is the shared language for attacker behaviour; threat hunting means finding attackers before any alert.",
            items: ["MITRE ATT&CK", "Indicators of compromise", "Threat hunting"],
          },
        ],
      },
      {
        id: "sec-cloud",
        fa: "امنیت ابر و زیرساخت",
        en: "Cloud and infrastructure security",
        outcomeFa: "کانتینر، Kubernetes و خط انتشار را امن می‌کنی و زنجیرهٔ تأمین نرم‌افزار را می‌پایی.",
        outcomeEn: "You secure containers, Kubernetes and pipelines and watch the software supply chain.",
        months: [2, 3],
        skills: [
          {
            fa: "امنیت ابر", en: "Cloud security", kind: "hard",
            whyFa: "بیشتر نشت‌های ابری از پیکربندی اشتباه‌اند، مثل یک مخزن ذخیره‌سازی عمومی.",
            whyEn: "Most cloud leaks come from misconfiguration, such as a storage bucket left public.",
            items: ["IAM", "Misconfigurations", "Shared responsibility model"],
          },
          {
            fa: "امنیت کانتینر و Kubernetes", en: "Container and Kubernetes security", kind: "hard",
            whyFa: "کانتینری که با root اجرا شود و ایمیجی که اسکن نشده، در باز هستند.",
            whyEn: "A container running as root and an unscanned image are open doors.",
            items: ["Image scanning", "Pod security", "Secrets management", "RBAC"],
            tracks: ["01-docker", "06-kubernetes"],
          },
          {
            fa: "DevSecOps", en: "DevSecOps", kind: "hard",
            whyFa: "حمله به زنجیرهٔ تأمین — پکیج آلوده، خط انتشار نفوذشده — از خطرناک‌ترین تهدیدهای امروز است.",
            whyEn: "Supply-chain attacks — poisoned packages, compromised pipelines — are among today's most dangerous threats.",
            items: ["Security in CI/CD", "SBOM & signing", "IaC scanning"],
            tracks: ["04-devops", "36-packaging"],
          },
        ],
      },
      {
        id: "sec-pro",
        fa: "اخلاق، قانون و حرفه",
        en: "Ethics, law and the profession",
        outcomeFa: "فقط با مجوز کتبی کار می‌کنی، گزارش قابل فهم برای مدیر و فنی می‌نویسی و مسیر شغلی‌ات را می‌شناسی.",
        outcomeEn: "You work only with written authorisation, write reports for both managers and engineers and know your career paths.",
        months: [1, 3],
        skills: [
          {
            fa: "اخلاق و قانون", en: "Ethics and law", kind: "soft",
            whyFa: "تست نفوذ بدون مجوز کتبی جرم است — در ایران هم طبق قانون جرایم رایانه‌ای. همیشه محدوده و مجوز را مکتوب بگیر.",
            whyEn: "Testing without written authorisation is a crime almost everywhere, including under Iran's Computer Crimes Law. Always get scope and permission in writing.",
            items: ["Written authorisation & scope", "Responsible disclosure", "Bug bounty rules", "قانون جرایم رایانه‌ای"],
          },
          {
            fa: "گزارش‌نویسی", en: "Report writing", kind: "soft",
            whyFa: "مشتری تست نفوذ فقط گزارش را می‌بیند؛ یافته‌ای که روشن نوشته نشود، انگار پیدا نشده.",
            whyEn: "A pentest client only ever sees the report; a finding not written clearly might as well not exist.",
            items: ["Pentest reports", "Executive summaries", "CVSS risk ratings"],
            tracks: ["64-docs-writing"],
          },
          {
            fa: "مدرک‌های حرفه‌ای", en: "Certifications", kind: "hard", level: "opt",
            whyFa: "مدرک جای مهارت را نمی‌گیرد، ولی در استخدام به‌خصوص در شرکت‌های بزرگ در را باز می‌کند.",
            whyEn: "Certificates do not replace skill, but they open doors in hiring, especially at large companies.",
            items: ["CompTIA Security+", "CEH", "OSCP", "CISSP (later)"],
          },
          {
            fa: "حاکمیت و مدیریت ریسک", en: "Governance and risk", kind: "hard", level: "opt",
            whyFa: "در سطح ارشد، امنیت کمتر فنی و بیشتر مدیریت ریسک و سیاست‌گذاری است.",
            whyEn: "At senior level, security is less technical and more about risk management and policy.",
            items: ["ISO 27001", "Risk assessment", "Security policies"],
          },
          {
            fa: "مسیرهای شغلی", en: "Career paths", kind: "soft",
            whyFa: "تحلیلگر مرکز عملیات امنیت، کارشناس تست نفوذ، مهندس امنیت، امنیت اپلیکیشن یا پاسخ به رخداد — هر کدام شاخهٔ متفاوتی از این رودمپ است.",
            whyEn: "SOC analyst, penetration tester, security engineer, application security or incident response — each is a different branch of this roadmap.",
            items: ["SOC analyst", "Penetration tester", "Security engineer", "Application security", "Incident responder"],
          },
        ],
      },
    ],
  },
];
