/* ============================================================================
   رودمپ تکنولوژی‌های داده: پایگاه‌داده (کلی) و SQL

   «پایگاه‌داده» مفهوم‌محور است و بین موتورها مشترک؛ «SQL» زبان‌محور است
   و تا T-SQL و PL/pgSQL می‌رود. هر دو به مسیر ۰۵ کدنامه وصل‌اند.
   ========================================================================== */
import type { Roadmap } from "./types";

export const TECH_DATA_ROADMAPS: Roadmap[] = [
  /* ═════════════════════════════ پایگاه‌داده ═════════════════════════════ */
  {
    id: "databases",
    field: "tech",
    accent: "#336791",
    ico: '<ellipse cx="12" cy="5.6" rx="7.6" ry="2.8"/><path d="M4.4 5.6v12.8c0 1.5 3.4 2.8 7.6 2.8s7.6-1.3 7.6-2.8V5.6M4.4 12c0 1.5 3.4 2.8 7.6 2.8s7.6-1.3 7.6-2.8"/>',
    after: ["foundations"],
    next: ["sql", "backend"],
    fa: {
      name: "پایگاه‌داده",
      role: "Database Engineer / DBA",
      intro:
        "تقریباً هر نرم‌افزاری در نهایت یک پایگاه‌داده است با یک رابط کاربری رویش. این رودمپ فقط یک محصول را یاد نمی‌دهد؛ مدل‌سازی داده، تراکنش، ایندکس، تکثیر و مقیاس را یاد می‌دهد — مفاهیمی که بین PostgreSQL، SQL Server و MongoDB مشترک‌اند — و بعد نشان می‌دهد کِی سراغ کدام نوع پایگاه‌داده بروی.",
    },
    en: {
      name: "Databases",
      role: "Database Engineer / DBA",
      intro:
        "Almost every piece of software is ultimately a database with a user interface on top. This roadmap does not teach one product; it teaches data modelling, transactions, indexes, replication and scale — ideas shared by PostgreSQL, SQL Server and MongoDB — and then shows when to reach for which kind of database.",
    },
    stages: [
      {
        id: "db-found",
        fa: "مبانی",
        en: "Foundations",
        outcomeFa: "برای یک کسب‌وکار واقعی طرح‌وارهٔ نرمال‌شده با کلید و قید درست طراحی می‌کنی.",
        outcomeEn: "You design a normalised schema with correct keys and constraints for a real business.",
        months: [1, 2],
        skills: [
          {
            fa: "مدل رابطه‌ای", en: "The relational model", kind: "hard",
            whyFa: "مدل رابطه‌ای پنجاه سال دوام آورده چون ریاضی محکمی پشتش است؛ کلید و قید درستی داده را تضمین می‌کنند، نه کد برنامه.",
            whyEn: "The relational model has lasted fifty years because solid mathematics backs it; keys and constraints guarantee correctness, not application code.",
            items: ["Tables, rows, columns", "Primary & foreign keys", "Constraints", "Relational algebra basics"],
            tracks: ["05-sql"],
          },
          {
            fa: "SQL", en: "SQL", kind: "hard",
            whyFa: "زبان مشترک همهٔ پایگاه‌داده‌های رابطه‌ای — و خیلی از غیررابطه‌ای‌ها. رودمپ جدای خودش را دارد.",
            whyEn: "The common language of every relational database — and many non-relational ones. It has its own roadmap.",
            items: ["SELECT / JOIN / GROUP BY", "INSERT / UPDATE / DELETE", "CTEs", "Window functions"],
            tracks: ["05-sql"],
          },
          {
            fa: "مدل‌سازی داده", en: "Data modelling", kind: "hard",
            whyFa: "طرح‌وارهٔ بد را بعداً با هیچ ایندکسی نمی‌شود نجات داد.",
            whyEn: "No index can later rescue a bad schema.",
            items: ["ER diagrams", "Cardinality", "Normalisation: 1NF → 3NF, BCNF", "Denormalisation trade-offs", "Naming conventions"],
            tracks: ["05-sql"],
          },
          {
            fa: "نوع داده", en: "Data types", kind: "hard",
            whyFa: "پول را با float ذخیره کنی، ریال‌ها گم می‌شوند؛ تاریخ را بدون منطقهٔ زمانی ذخیره کنی، ساعت‌ها جابه‌جا می‌شوند.",
            whyEn: "Store money as a float and cents go missing; store dates without a time zone and hours shift.",
            items: ["Integer vs decimal vs float", "Text & collation", "Dates, times & time zones", "UUID vs identity", "JSON columns"],
          },
        ],
      },
      {
        id: "db-engine",
        fa: "یک موتور رابطه‌ای، عمیق",
        en: "One relational engine, deeply",
        outcomeFa: "یک موتور را نصب، پیکربندی و مدیریت می‌کنی و ابزارهای اصلی‌اش را می‌شناسی.",
        outcomeEn: "You install, configure and manage one engine and know its main tools.",
        months: [2, 3],
        skills: [
          {
            fa: "PostgreSQL", en: "PostgreSQL", kind: "hard", level: "alt",
            whyFa: "پرطرفدارترین پایگاه‌دادهٔ متن‌باز امروز؛ رایگان، بسیار توانمند و با افزونه‌هایی مثل PostGIS.",
            whyEn: "Today's most popular open-source database; free, extremely capable, with extensions such as PostGIS.",
            items: ["psql", "Schemas & roles", "MVCC", "JSONB", "Extensions (PostGIS, pg_trgm)", "VACUUM"],
          },
          {
            fa: "SQL Server", en: "SQL Server", kind: "hard", level: "alt",
            whyFa: "در سامانه‌های سازمانی و بانکی بسیار رایج است و با .NET یکپارچه است.",
            whyEn: "Very common in enterprise and banking systems and tightly integrated with .NET.",
            items: ["SSMS", "T-SQL", "Clustered vs non-clustered indexes", "Execution plans", "SQL Server Agent"],
            tracks: ["05-sql"],
          },
          {
            fa: "MySQL / MariaDB", en: "MySQL / MariaDB", kind: "hard", level: "alt",
            whyFa: "پشت بخش بزرگی از وب — از وردپرس تا اپ‌های PHP؛ فرق‌هایش با PostgreSQL را باید بدانی.",
            whyEn: "Behind a large part of the web — from WordPress to PHP apps; you should know how it differs from PostgreSQL.",
            items: ["InnoDB", "Replication", "Differences from PostgreSQL"],
            tracks: ["53-mysql-mariadb"],
          },
          {
            fa: "Oracle", en: "Oracle", kind: "hard", level: "opt",
            whyFa: "در بانک‌ها و شرکت‌های بزرگ مخابراتی هنوز پرکاربرد است.",
            whyEn: "Still widespread in large banks and telecom companies.",
            items: ["PL/SQL", "Tablespaces", "RAC"],
            tracks: ["55-oracle"],
          },
          {
            fa: "SQLite", en: "SQLite", kind: "hard", level: "opt",
            whyFa: "پرنصب‌ترین پایگاه‌دادهٔ دنیا — در هر گوشی و مرورگر؛ برای اپ موبایل و ابزار محلی عالی است.",
            whyEn: "The most deployed database in the world — in every phone and browser; excellent for mobile apps and local tools.",
            items: ["Embedded database", "WAL mode", "Mobile & edge"],
          },
        ],
      },
      {
        id: "db-internals",
        fa: "ایندکس و اجرای کوئری",
        en: "Indexes and query execution",
        outcomeFa: "برنامهٔ اجرا را می‌خوانی و با ایندکس درست کوئری ده‌ثانیه‌ای را به ده میلی‌ثانیه می‌رسانی.",
        outcomeEn: "You read execution plans and turn a ten-second query into ten milliseconds with the right index.",
        months: [1, 2],
        skills: [
          {
            fa: "ایندکس", en: "Indexes", kind: "hard",
            whyFa: "ایندکس سریع‌ترین بهبود کارایی است — و ایندکس اضافه، کندترین نوشتن.",
            whyEn: "An index is the quickest performance win — and an unnecessary one is the slowest write.",
            items: ["B-tree", "Hash", "Composite index & column order", "Covering index", "Partial / filtered index", "GIN / GiST"],
            tracks: ["05-sql"],
          },
          {
            fa: "برنامهٔ اجرا", en: "Execution plans", kind: "hard",
            whyFa: "SQL می‌گوید چه می‌خواهی؛ برنامهٔ اجرا نشان می‌دهد موتور واقعاً چطور انجامش داده است.",
            whyEn: "SQL says what you want; the execution plan shows how the engine actually did it.",
            items: ["EXPLAIN / EXPLAIN ANALYZE", "Seek vs scan", "Nested loop, hash & merge joins", "Statistics & cardinality estimates"],
          },
          {
            fa: "بهینه‌سازی کوئری", en: "Query tuning", kind: "hard",
            whyFa: "بیشتر کندی‌ها چند الگوی تکراری‌اند؛ آن‌ها را که بشناسی، در بازبینی کد می‌گیری‌شان.",
            whyEn: "Most slowness comes from a handful of recurring patterns; learn them and you catch them in code review.",
            items: ["Sargable predicates", "Avoiding SELECT *", "N+1 from ORMs", "Parameter sniffing", "Offset vs keyset pagination"],
          },
          {
            fa: "درونیات ذخیره‌سازی", en: "Storage internals", kind: "hard", level: "opt",
            whyFa: "وقتی بدانی داده در صفحه و WAL چطور نوشته می‌شود، رفتار دیسک و بازیابی بعد از خرابی معنا پیدا می‌کند.",
            whyEn: "Once you know how data is written to pages and the WAL, disk behaviour and crash recovery make sense.",
            items: ["Pages & heap", "WAL / transaction log", "Buffer pool", "Fill factor"],
          },
        ],
      },
      {
        id: "db-tx",
        fa: "تراکنش و همروندی",
        en: "Transactions and concurrency",
        outcomeFa: "می‌دانی سطح‌های ایزولاسیون چه ناهنجاری‌هایی را جلو می‌گیرند و بن‌بست را تحلیل می‌کنی.",
        outcomeEn: "You know which anomalies each isolation level prevents and can analyse a deadlock.",
        months: [1, 2],
        skills: [
          {
            fa: "ACID", en: "ACID", kind: "hard",
            whyFa: "انتقال پول یا کامل انجام می‌شود یا اصلاً؛ ACID همین قول است.",
            whyEn: "A money transfer happens completely or not at all; ACID is that promise.",
            items: ["Atomicity", "Consistency", "Isolation", "Durability"],
            tracks: ["05-sql"],
          },
          {
            fa: "سطح‌های ایزولاسیون", en: "Isolation levels", kind: "hard",
            whyFa: "پیش‌فرض بیشتر موتورها Read Committed است؛ یعنی بعضی ناهنجاری‌ها مجازند و باید بدانی کدام.",
            whyEn: "Most engines default to Read Committed, which means some anomalies are allowed — and you need to know which.",
            items: ["Read uncommitted / committed", "Repeatable read", "Serializable", "Snapshot isolation", "Dirty read, lost update, phantom, write skew"],
          },
          {
            fa: "قفل و MVCC", en: "Locks and MVCC", kind: "hard",
            whyFa: "بن‌بست باگ نیست، رویداد است؛ برنامه باید آماده باشد تراکنش را دوباره اجرا کند.",
            whyEn: "A deadlock is not a bug but an event; the application must be ready to retry the transaction.",
            items: ["Row vs table locks", "MVCC", "Deadlocks", "SELECT … FOR UPDATE", "Optimistic concurrency"],
          },
          {
            fa: "تراکنش توزیع‌شده", en: "Distributed transactions", kind: "hard", level: "opt",
            whyFa: "وقتی داده در چند سرویس است، تراکنش ACID دیگر در دسترس نیست؛ Saga و Outbox جایگزین‌اند.",
            whyEn: "Once data spans several services, ACID transactions are gone; Saga and Outbox are the replacements.",
            items: ["Two-phase commit", "Saga pattern", "Outbox pattern", "Idempotency"],
            tracks: ["08-microservices"],
          },
        ],
      },
      {
        id: "db-nosql",
        fa: "پایگاه‌داده‌های غیررابطه‌ای",
        en: "Non-relational databases",
        outcomeFa: "برای هر الگوی دسترسی نوع درست پایگاه‌داده را می‌شناسی و کِی رابطه‌ای کافی است را هم می‌دانی.",
        outcomeEn: "You know the right database type for each access pattern — and when relational is enough.",
        months: [2, 3],
        skills: [
          {
            fa: "کلید-مقدار: Redis", en: "Key-value: Redis", kind: "hard",
            whyFa: "کش، نشست، صف و شمارنده — Redis تقریباً در هر سامانهٔ پرترافیکی کنار پایگاه‌دادهٔ اصلی نشسته است.",
            whyEn: "Caches, sessions, queues and counters — Redis sits beside the main database in almost every high-traffic system.",
            items: ["Strings, hashes, sets, sorted sets", "TTL & eviction", "Caching patterns", "Pub/Sub & streams", "RDB / AOF persistence"],
            tracks: ["52-redis"],
          },
          {
            fa: "سندمحور: MongoDB", en: "Document: MongoDB", kind: "hard", level: "alt",
            whyFa: "برای داده‌ای که شکلش مدام عوض می‌شود یا طبیعتاً سلسله‌مراتبی است؛ ولی نبود JOIN را باید با طراحی جبران کنی.",
            whyEn: "For data whose shape keeps changing or is naturally hierarchical; but you must design around the lack of joins.",
            items: ["Documents & collections", "Embedding vs referencing", "Aggregation pipeline", "Indexes", "Replica sets"],
            tracks: ["51-mongodb"],
          },
          {
            fa: "جستجو: Elasticsearch", en: "Search: Elasticsearch", kind: "hard", level: "alt",
            whyFa: "جستجوی متنی با LIKE کند و بی‌کیفیت است؛ ایندکس معکوس و تحلیلگر فارسی نتیجهٔ مرتبط می‌دهند.",
            whyEn: "Full-text search with LIKE is slow and poor; an inverted index with a Persian analyser returns relevant results.",
            items: ["Inverted index", "Analysers (Persian)", "BM25 relevance", "Aggregations"],
            tracks: ["19-elasticsearch"],
          },
          {
            fa: "ستون‌گسترده: Cassandra", en: "Wide-column: Cassandra", kind: "hard", level: "opt",
            whyFa: "برای نوشتن بسیار زیاد و توزیع جغرافیایی؛ طرح‌واره را از روی کوئری‌ها می‌سازی، نه از روی موجودیت‌ها.",
            whyEn: "For huge write volumes and geographic distribution; you design the schema from the queries, not the entities.",
            items: ["Partition keys", "Query-first modelling", "Tunable consistency", "Compaction"],
            tracks: ["54-cassandra"],
          },
          {
            fa: "گراف و سری زمانی", en: "Graph and time series", kind: "hard", level: "opt",
            whyFa: "شبکهٔ اجتماعی و توصیه‌گر در گراف طبیعی‌اند؛ داده‌های حسگر و متریک در پایگاه‌دادهٔ سری زمانی.",
            whyEn: "Social networks and recommenders are natural in a graph; sensor data and metrics in a time-series database.",
            items: ["Neo4j & Cypher", "TimescaleDB", "InfluxDB"],
          },
          {
            fa: "پایگاه‌دادهٔ برداری", en: "Vector databases", kind: "hard", level: "opt",
            whyFa: "پایهٔ جستجوی معنایی و RAG در اپ‌های هوش مصنوعی.",
            whyEn: "The basis of semantic search and RAG in AI applications.",
            items: ["Embeddings", "pgvector", "HNSW indexes", "Qdrant / Milvus"],
            tracks: ["61-ai-engineering"],
          },
        ],
      },
      {
        id: "db-scale",
        fa: "تکثیر، مقیاس و دسترس‌پذیری",
        en: "Replication, scale and availability",
        outcomeFa: "پایگاه‌داده‌ای طراحی می‌کنی که با خرابی یک سرور نخوابد و با رشد داده کند نشود.",
        outcomeEn: "You design a database that survives a server failure and does not slow down as data grows.",
        months: [2, 3],
        skills: [
          {
            fa: "تکثیر", en: "Replication", kind: "hard",
            whyFa: "نسخهٔ خواندنی بار را پخش می‌کند؛ ولی تأخیر تکثیر یعنی کاربر ممکن است نوشتهٔ خودش را نبیند.",
            whyEn: "Read replicas spread load; but replication lag means users may not see their own writes.",
            items: ["Primary / replica", "Synchronous vs asynchronous", "Read replicas", "Replication lag", "Failover"],
          },
          {
            fa: "پارتیشن‌بندی و شاردینگ", en: "Partitioning and sharding", kind: "hard",
            whyFa: "کلید شارد را اشتباه انتخاب کنی، یک سرور داغ می‌شود و بقیه بیکار می‌مانند — و عوض کردنش سخت است.",
            whyEn: "Pick the wrong shard key and one server runs hot while the rest idle — and changing it is hard.",
            items: ["Table partitioning", "Horizontal sharding", "Shard keys", "Citus / Vitess"],
          },
          {
            fa: "CAP و سازگاری", en: "CAP and consistency", kind: "hard",
            whyFa: "در سامانهٔ توزیع‌شده، هنگام قطعی شبکه باید بین سازگاری و در دسترس بودن انتخاب کنی.",
            whyEn: "In a distributed system, during a network partition you must choose between consistency and availability.",
            items: ["CAP theorem", "PACELC", "Eventual consistency", "Quorum reads & writes"],
          },
          {
            fa: "Connection pooling", en: "Connection pooling", kind: "hard",
            whyFa: "هر اتصال PostgreSQL یک پروسه است؛ هزار اتصال مستقیم سرور را از پا می‌اندازد.",
            whyEn: "Every PostgreSQL connection is a process; a thousand direct connections will bring the server down.",
            items: ["PgBouncer", "Pool sizing", "Serverless connection limits"],
          },
          {
            fa: "دسترس‌پذیری بالا", en: "High availability", kind: "hard",
            whyFa: "RPO و RTO را با کسب‌وکار توافق کن: چقدر داده و چقدر زمان را می‌توانید از دست بدهید؟",
            whyEn: "Agree RPO and RTO with the business: how much data and how much time can you afford to lose?",
            items: ["Patroni", "Always On availability groups", "RPO & RTO"],
          },
        ],
      },
      {
        id: "db-ops",
        fa: "عملیات و امنیت",
        en: "Operations and security",
        outcomeFa: "پشتیبان می‌گیری و بازیابی را تمرین می‌کنی، طرح‌واره را بدون قطعی تغییر می‌دهی و دسترسی‌ها را حداقلی نگه می‌داری.",
        outcomeEn: "You take backups and rehearse restores, change schemas without downtime and keep access minimal.",
        months: [1, 2],
        skills: [
          {
            fa: "پشتیبان و بازیابی", en: "Backup and recovery", kind: "hard",
            whyFa: "پشتیبانی که هرگز بازیابی‌اش را تمرین نکرده‌ای، پشتیبان نیست — امید است.",
            whyEn: "A backup you have never practised restoring is not a backup — it is a hope.",
            items: ["Full / differential / log backups", "Point-in-time recovery", "Restore drills", "pg_dump / pg_basebackup"],
          },
          {
            fa: "مهاجرت طرح‌واره", en: "Schema migrations", kind: "hard",
            whyFa: "افزودن ستون NOT NULL به جدول صدمیلیونی می‌تواند جدول را دقیقه‌ها قفل کند؛ الگوی expand و contract این را حل می‌کند.",
            whyEn: "Adding a NOT NULL column to a hundred-million-row table can lock it for minutes; expand-and-contract solves that.",
            items: ["Versioned migrations", "Zero-downtime changes", "Expand & contract", "Flyway / Liquibase / EF migrations"],
          },
          {
            fa: "امنیت", en: "Security", kind: "hard",
            whyFa: "کاربر برنامه نباید اجازهٔ DROP داشته باشد؛ و هر کوئری باید پارامتری باشد.",
            whyEn: "The application user should never be allowed to DROP; and every query should be parameterised.",
            items: ["Least-privilege roles", "Row-level security", "Encryption at rest & in transit", "SQL injection", "Auditing"],
          },
          {
            fa: "پایش", en: "Monitoring", kind: "hard",
            whyFa: "کوئری کند را قبل از کاربر پیدا کن؛ ابزارش در خود موتور هست.",
            whyEn: "Find the slow query before the user does; the tools are built into the engine.",
            items: ["Slow query log", "pg_stat_statements / Query Store", "Wait statistics", "Disk & connection metrics"],
          },
          {
            fa: "پایگاه‌داده در کانتینر", en: "Databases in containers", kind: "hard", level: "opt",
            whyFa: "برای توسعه عالی است؛ در تولید، ذخیره‌سازی و پشتیبان را جدی بگیر.",
            whyEn: "Great for development; in production, take storage and backups seriously.",
            items: ["Docker volumes", "StatefulSets", "Operators (CloudNativePG)"],
            tracks: ["01-docker", "06-kubernetes"],
          },
        ],
      },
      {
        id: "db-analytics",
        fa: "دادهٔ تحلیلی و تصمیم‌گیری",
        en: "Analytical data and decisions",
        outcomeFa: "فرق پایگاه‌دادهٔ عملیاتی و تحلیلی را می‌دانی و برای یک نیاز واقعی، پایگاه‌داده را با دلیل انتخاب می‌کنی.",
        outcomeEn: "You know operational from analytical databases and choose a database for a real need, with reasons.",
        months: [1, 3],
        skills: [
          {
            fa: "OLTP در برابر OLAP", en: "OLTP vs OLAP", kind: "hard",
            whyFa: "گزارش سنگین روی پایگاه‌دادهٔ عملیاتی، فروشگاه را کند می‌کند؛ دادهٔ تحلیلی جای جدا و ساختار جدا می‌خواهد.",
            whyEn: "Heavy reports on the operational database slow the shop down; analytical data needs its own place and structure.",
            items: ["Row vs column stores", "Star & snowflake schemas", "Fact & dimension tables"],
          },
          {
            fa: "انبار داده و موتور ستونی", en: "Warehouses and columnar engines", kind: "hard", level: "alt",
            whyFa: "موتور ستونی کوئری تجمیعی روی میلیاردها ردیف را در چند ثانیه اجرا می‌کند.",
            whyEn: "A columnar engine runs aggregate queries over billions of rows in seconds.",
            items: ["ClickHouse", "DuckDB", "BigQuery / Snowflake", "Materialised views"],
          },
          {
            fa: "ETL، ELT و CDC", en: "ETL, ELT and CDC", kind: "hard", level: "opt",
            whyFa: "CDC تغییرات را از لاگ پایگاه‌داده برمی‌دارد، پس بدون بار اضافه روی پایگاه‌دادهٔ اصلی داده را جابه‌جا می‌کند.",
            whyEn: "CDC reads changes from the database log, so it moves data without extra load on the main database.",
            items: ["ETL vs ELT", "dbt", "Debezium", "Kafka Connect"],
          },
          {
            fa: "انتخاب پایگاه‌داده", en: "Choosing a database", kind: "soft",
            whyFa: "«بهترین پایگاه‌داده» وجود ندارد؛ فقط الگوی دسترسی، حجم، تیم و بودجه وجود دارد. انتخاب را با دلیل مکتوب کن.",
            whyEn: "There is no “best database”; only access patterns, volume, team and budget. Write the choice down with reasons.",
            items: ["Access patterns", "Operational cost", "Team skills", "ADRs"],
            tracks: ["64-docs-writing"],
          },
          {
            fa: "گفت‌وگو با مصرف‌کنندهٔ داده", en: "Talking with data consumers", kind: "soft",
            whyFa: "تحلیلگر، حسابدار و مدیر هر کدام از داده سؤال متفاوتی دارند؛ طرح‌وارهٔ مستند و قرارداد داده جلوی سوءبرداشت را می‌گیرد.",
            whyEn: "Analysts, accountants and managers each ask the data different questions; documented schemas and data contracts prevent misreadings.",
            items: ["Schema documentation", "Data contracts", "Data dictionaries"],
          },
        ],
      },
    ],
  },

  /* ════════════════════════════════ SQL ════════════════════════════════ */
  {
    id: "sql",
    field: "tech",
    accent: "#E38C00",
    ico: '<rect x="3" y="4" width="18" height="16" rx="2.2"/><path d="M3 9.4h18M3 14.7h18M9 4v16"/>',
    next: ["databases", "backend"],
    fa: {
      name: "SQL",
      role: "SQL Developer",
      intro:
        "SQL زبانی بیش از چهل‌ساله است که هنوز هر روز میلیون‌ها برنامه‌نویس، تحلیلگر و مدیر داده با آن کار می‌کنند. فرقش با زبان‌های دیگر این است که «چه می‌خواهی» را می‌گویی، نه «چطور به دست بیاوری» — و همین طرز فکر اعلانی است که باید یاد بگیری. این رودمپ از یک SELECT ساده تا توابع پنجره‌ای، CTE بازگشتی، برنامهٔ اجرا و T-SQL و PL/pgSQL می‌رود.",
    },
    en: {
      name: "SQL",
      role: "SQL Developer",
      intro:
        "SQL is a language over forty years old that millions of programmers, analysts and data managers still use every day. What sets it apart is that you state what you want, not how to get it — and that declarative way of thinking is what you have to learn. This roadmap goes from a simple SELECT to window functions, recursive CTEs, execution plans, T-SQL and PL/pgSQL.",
    },
    stages: [
      {
        id: "sq-basics",
        fa: "پایه",
        en: "Basics",
        outcomeFa: "از یک جدول هر ردیف و ستونی را که بخواهی، فیلترشده و مرتب بیرون می‌کشی و تلهٔ NULL را می‌شناسی.",
        outcomeEn: "You pull any rows and columns you want from a table, filtered and sorted, and you know the NULL trap.",
        months: [1, 1],
        skills: [
          {
            fa: "اولین کوئری‌ها", en: "First queries", kind: "hard",
            whyFa: "نود درصد کار روزانه با SQL همین SELECT و WHERE است؛ باید بی‌فکر بنویسی‌شان.",
            whyEn: "Ninety percent of daily SQL work is SELECT and WHERE; you should write them without thinking.",
            items: ["SELECT … FROM", "WHERE", "ORDER BY", "LIMIT / TOP / FETCH FIRST", "DISTINCT", "Aliases"],
            tracks: ["05-sql"],
          },
          {
            fa: "فیلتر کردن", en: "Filtering", kind: "hard",
            whyFa: "اولویت AND بر OR بی‌صدا نتیجه را عوض می‌کند؛ پرانتز بگذار.",
            whyEn: "AND binding tighter than OR silently changes results; use parentheses.",
            items: ["= <> < >", "AND / OR / NOT", "IN / BETWEEN / LIKE", "IS NULL", "CASE"],
            tracks: ["05-sql"],
          },
          {
            fa: "NULL و منطق سه‌ارزشی", en: "NULL and three-valued logic", kind: "hard",
            whyFa: "NOT IN روی فهرستی که یک NULL دارد، هیچ ردیفی برنمی‌گرداند — از بدترین تله‌های SQL.",
            whyEn: "NOT IN against a list that contains a NULL returns no rows at all — one of SQL's nastiest traps.",
            items: ["NULL is not equal to NULL", "IS NULL vs = NULL", "COALESCE / ISNULL", "NULLs in aggregates", "NOT IN with NULLs"],
            tracks: ["05-sql"],
          },
          {
            fa: "محیط کار", en: "Your environment", kind: "hard",
            whyFa: "یک موتور نصب کن و یک پایگاه‌دادهٔ نمونه بارگذاری کن؛ SQL را فقط با اجرا کردن یاد می‌گیری.",
            whyEn: "Install an engine and load a sample database; you only learn SQL by running it.",
            items: ["SQL Server + SSMS", "PostgreSQL + psql / pgAdmin", "DBeaver", "Sample databases"],
          },
          {
            fa: "خواندن درست سؤال", en: "Reading the question", kind: "soft",
            whyFa: "بیشتر کوئری‌های غلط از فهم غلط سؤال می‌آیند؛ اول بپرس «هر ردیف خروجی نمایندهٔ چیست؟»",
            whyEn: "Most wrong queries come from misreading the question; first ask “what does each output row represent?”",
            items: ["Row grain", "Write the expected output first", "Edge cases"],
          },
        ],
      },
      {
        id: "sq-agg",
        fa: "تجمیع و گروه‌بندی",
        en: "Aggregation and grouping",
        outcomeFa: "گزارش خلاصه می‌سازی: جمع فروش هر ماه، تعداد سفارش هر مشتری، میانگین هر دسته.",
        outcomeEn: "You build summary reports: sales per month, orders per customer, averages per category.",
        months: [1, 1],
        skills: [
          {
            fa: "توابع تجمیعی", en: "Aggregate functions", kind: "hard",
            whyFa: "COUNT(*) و COUNT(ستون) فرق دارند: دومی NULLها را نمی‌شمارد.",
            whyEn: "COUNT(*) and COUNT(column) differ: the second skips NULLs.",
            items: ["COUNT(*) vs COUNT(col)", "SUM / AVG / MIN / MAX", "COUNT(DISTINCT)", "Integer division pitfall"],
          },
          {
            fa: "GROUP BY و HAVING", en: "GROUP BY and HAVING", kind: "hard",
            whyFa: "ترتیب منطقی اجرا (FROM، WHERE، GROUP BY، HAVING، SELECT، ORDER BY) توضیح می‌دهد چرا alias در WHERE کار نمی‌کند.",
            whyEn: "The logical order (FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY) explains why an alias does not work in WHERE.",
            items: ["GROUP BY", "HAVING vs WHERE", "Logical order of execution", "GROUPING SETS / ROLLUP / CUBE"],
            tracks: ["05-sql"],
          },
          {
            fa: "تاریخ و رشته", en: "Dates and strings", kind: "hard",
            whyFa: "گزارش‌ها تقریباً همیشه بر اساس زمان‌اند؛ و توابع تاریخ در هر موتور کمی فرق دارند.",
            whyEn: "Reports are almost always time-based; and date functions differ slightly between engines.",
            items: ["Date arithmetic", "DATE_TRUNC / DATEPART", "String functions", "CAST / CONVERT", "Time zones"],
          },
        ],
      },
      {
        id: "sq-joins",
        fa: "Join و زیرکوئری",
        en: "Joins and subqueries",
        outcomeFa: "داده را از چند جدول کنار هم می‌گذاری و می‌دانی هر نوع join با ردیف‌های بی‌جفت چه می‌کند.",
        outcomeEn: "You combine data from several tables and know what each join does with unmatched rows.",
        months: [1, 2],
        skills: [
          {
            fa: "انواع Join", en: "Joins", kind: "hard",
            whyFa: "شرط روی جدول سمت راست در WHERE، یک LEFT JOIN را بی‌صدا به INNER JOIN تبدیل می‌کند.",
            whyEn: "A condition on the right-hand table in WHERE silently turns a LEFT JOIN into an INNER JOIN.",
            items: ["INNER JOIN", "LEFT / RIGHT JOIN", "FULL OUTER JOIN", "CROSS JOIN", "Self join", "ON vs WHERE on outer joins"],
            tracks: ["05-sql"],
          },
          {
            fa: "زیرکوئری", en: "Subqueries", kind: "hard",
            whyFa: "EXISTS معمولاً روشن‌ترین راه گفتن «آیا چنین ردیفی هست؟» است و با NULL هم مشکل ندارد.",
            whyEn: "EXISTS is usually the clearest way to say “is there such a row?”, and it has no trouble with NULLs.",
            items: ["Scalar subqueries", "IN / EXISTS", "Correlated subqueries", "Derived tables", "NOT EXISTS vs NOT IN"],
          },
          {
            fa: "عملگرهای مجموعه", en: "Set operations", kind: "hard",
            whyFa: "UNION تکراری‌ها را حذف می‌کند و برای این کار باید مرتب یا هش کند؛ اگر لازم نیست، UNION ALL سریع‌تر است.",
            whyEn: "UNION removes duplicates and must sort or hash to do it; if you do not need that, UNION ALL is faster.",
            items: ["UNION vs UNION ALL", "INTERSECT", "EXCEPT / MINUS"],
          },
          {
            fa: "APPLY و LATERAL", en: "APPLY and LATERAL", kind: "hard", level: "opt",
            whyFa: "برای «سه سفارش آخر هر مشتری» و مسئله‌هایی که زیرکوئری باید به ردیف بیرونی دسترسی داشته باشد.",
            whyEn: "For “each customer's last three orders” and problems where a subquery needs the outer row.",
            items: ["CROSS APPLY / OUTER APPLY", "LATERAL joins", "Top-N per group"],
          },
        ],
      },
      {
        id: "sq-ddl",
        fa: "طراحی جدول و تغییر داده",
        en: "Table design and data changes",
        outcomeFa: "جدول با قید درست می‌سازی و داده را امن درج، به‌روز و ادغام می‌کنی.",
        outcomeEn: "You create tables with the right constraints and insert, update and merge data safely.",
        months: [1, 2],
        skills: [
          {
            fa: "DDL", en: "DDL", kind: "hard",
            whyFa: "طرح‌واره قرارداد داده است؛ نوع و طول ستون را با فکر انتخاب کن، چون تغییرش روی جدول بزرگ گران است.",
            whyEn: "The schema is the data's contract; choose column types and lengths carefully, because changing them on a large table is expensive.",
            items: ["CREATE / ALTER / DROP TABLE", "Data types", "Identity & sequences", "Computed columns", "Schemas"],
            tracks: ["05-sql"],
          },
          {
            fa: "قیدها", en: "Constraints", kind: "hard",
            whyFa: "قید آخرین خط دفاع درستی داده است؛ کد برنامه عوض می‌شود، قید می‌ماند.",
            whyEn: "Constraints are the last line of defence for correct data; application code changes, constraints stay.",
            items: ["PRIMARY KEY", "FOREIGN KEY & ON DELETE", "UNIQUE", "CHECK", "DEFAULT", "NOT NULL"],
          },
          {
            fa: "DML", en: "DML", kind: "hard",
            whyFa: "UPDATE بدون WHERE مشهورترین فاجعهٔ SQL است؛ اول همان شرط را با SELECT امتحان کن.",
            whyEn: "An UPDATE without WHERE is SQL's most famous disaster; try the same condition with a SELECT first.",
            items: ["INSERT … SELECT", "UPDATE with JOIN", "DELETE vs TRUNCATE", "MERGE", "Upsert (ON CONFLICT / MERGE)", "OUTPUT / RETURNING"],
          },
          {
            fa: "نرمال‌سازی", en: "Normalisation", kind: "hard",
            whyFa: "دادهٔ تکراری دیر یا زود ناسازگار می‌شود؛ نرمال‌سازی جلوی این را می‌گیرد و denormalize آگاهانه جای خودش را دارد.",
            whyEn: "Duplicated data becomes inconsistent sooner or later; normalisation prevents that, and deliberate denormalisation has its place.",
            items: ["1NF, 2NF, 3NF", "Functional dependencies", "When to denormalise"],
            tracks: ["05-sql"],
          },
        ],
      },
      {
        id: "sq-adv",
        fa: "SQL پیشرفته",
        en: "Advanced SQL",
        outcomeFa: "مسئله‌های گزارشی سخت را با CTE و توابع پنجره‌ای در یک کوئری خوانا حل می‌کنی.",
        outcomeEn: "You solve hard reporting problems with CTEs and window functions in one readable query.",
        months: [2, 3],
        skills: [
          {
            fa: "CTE", en: "CTEs", kind: "hard",
            whyFa: "کوئری بزرگ را به قدم‌های نام‌دار می‌شکند؛ نسخهٔ بازگشتی درخت و سلسله‌مراتب را پیمایش می‌کند.",
            whyEn: "Breaks a big query into named steps; the recursive form walks trees and hierarchies.",
            items: ["WITH", "Multiple CTEs", "Recursive CTEs", "Hierarchies & trees"],
            tracks: ["05-sql"],
          },
          {
            fa: "توابع پنجره‌ای", en: "Window functions", kind: "hard",
            whyFa: "مهارتی که SQL متوسط را از SQL حرفه‌ای جدا می‌کند؛ مسئله‌هایی که با self-join زشت می‌شوند، با پنجره یک خط‌اند.",
            whyEn: "The skill that separates intermediate from professional SQL; problems that turn ugly with self-joins become one line with windows.",
            items: ["OVER (PARTITION BY … ORDER BY …)", "ROW_NUMBER / RANK / DENSE_RANK", "LAG / LEAD", "Running totals", "ROWS vs RANGE frames", "NTILE"],
            tracks: ["05-sql"],
          },
          {
            fa: "الگوهای کلاسیک", en: "Classic problem patterns", kind: "hard",
            whyFa: "چند الگو بارها در کار و مصاحبه تکرار می‌شوند؛ شناختنشان یعنی حل در چند دقیقه به‌جای چند ساعت.",
            whyEn: "A few patterns recur again and again at work and in interviews; recognising them means minutes instead of hours.",
            items: ["Top-N per group", "Gaps and islands", "Running balances", "Deduplication", "Pivot / unpivot"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "View", en: "Views", kind: "hard",
            whyFa: "view منطق تکراری را یک‌جا نگه می‌دارد و دسترسی را محدود می‌کند؛ نسخهٔ مادی‌شده نتیجه را هم ذخیره می‌کند.",
            whyEn: "Views keep repeated logic in one place and restrict access; materialised views store the result too.",
            items: ["Views", "Materialised / indexed views", "Security via views"],
          },
          {
            fa: "JSON در SQL", en: "JSON in SQL", kind: "hard", level: "opt",
            whyFa: "موتورهای امروزی JSON را خوب می‌فهمند؛ ولی دادهٔ ساخت‌یافته را در ستون JSON پنهان نکن.",
            whyEn: "Modern engines handle JSON well; but do not hide structured data inside a JSON column.",
            items: ["JSONB operators (PostgreSQL)", "OPENJSON / JSON_VALUE (SQL Server)", "Indexing JSON"],
          },
        ],
      },
      {
        id: "sq-perf",
        fa: "کارایی کوئری",
        en: "Query performance",
        outcomeFa: "کوئری کند را با برنامهٔ اجرا تشخیص می‌دهی و با بازنویسی یا ایندکس درستش می‌کنی.",
        outcomeEn: "You diagnose a slow query with its execution plan and fix it by rewriting or indexing.",
        months: [1, 2],
        skills: [
          {
            fa: "ایندکس", en: "Indexes", kind: "hard",
            whyFa: "ترتیب ستون‌ها در ایندکس ترکیبی مهم است؛ ایندکس (A, B) به کوئری‌ای که فقط B را فیلتر می‌کند کمکی نمی‌کند.",
            whyEn: "Column order in a composite index matters; an index on (A, B) does not help a query that only filters on B.",
            items: ["Clustered vs non-clustered", "Composite key order", "Covering / INCLUDE", "Filtered indexes", "Index maintenance"],
            tracks: ["05-sql"],
          },
          {
            fa: "برنامهٔ اجرا", en: "Execution plans", kind: "hard",
            whyFa: "برنامهٔ اجرا دقیقاً می‌گوید زمان کجا رفته؛ حدس زدن جایش را نمی‌گیرد.",
            whyEn: "The execution plan tells you exactly where the time went; guessing is no substitute.",
            items: ["Estimated vs actual plan", "Seek vs scan", "Key lookups", "Join operators", "Statistics"],
          },
          {
            fa: "نوشتن SQL سریع", en: "Writing fast SQL", kind: "hard",
            whyFa: "WHERE YEAR(created_at) = 2025 ایندکس را بی‌استفاده می‌کند؛ یک بازهٔ تاریخ همان نتیجه را با seek می‌دهد.",
            whyEn: "WHERE YEAR(created_at) = 2025 makes the index useless; a date range gives the same result with a seek.",
            items: ["Sargability", "Functions on indexed columns", "Implicit conversions", "Parameter sniffing", "Keyset pagination"],
          },
        ],
      },
      {
        id: "sq-tx",
        fa: "تراکنش و همروندی",
        en: "Transactions and concurrency",
        outcomeFa: "چند تغییر را اتمی انجام می‌دهی و می‌دانی دو کاربر هم‌زمان چه چیزی از هم می‌بینند.",
        outcomeEn: "You make several changes atomically and know what two concurrent users see of each other.",
        months: [1, 1],
        skills: [
          {
            fa: "تراکنش", en: "Transactions", kind: "hard",
            whyFa: "بدون تراکنش، خطا وسط کار داده را نیمه‌کاره رها می‌کند.",
            whyEn: "Without a transaction, an error halfway through leaves data half-done.",
            items: ["BEGIN / COMMIT / ROLLBACK", "Savepoints", "XACT_ABORT", "Autocommit"],
            tracks: ["05-sql"],
          },
          {
            fa: "ایزولاسیون و قفل", en: "Isolation and locking", kind: "hard",
            whyFa: "خواندن گزارش نباید فروش را قفل کند؛ row versioning همین را ممکن می‌کند.",
            whyEn: "Reading a report should not block sales; row versioning makes that possible.",
            items: ["Isolation levels", "Row versioning (RCSI)", "Reading deadlock graphs", "Lock escalation", "FOR UPDATE / UPDLOCK"],
          },
        ],
      },
      {
        id: "sq-proc",
        fa: "برنامه‌نویسی در پایگاه‌داده",
        en: "Programming in the database",
        outcomeFa: "رویه و تابع ذخیره‌شده می‌نویسی و می‌دانی کِی منطق باید در پایگاه‌داده باشد و کِی نه.",
        outcomeEn: "You write stored procedures and functions and know when logic belongs in the database and when it does not.",
        months: [1, 2],
        skills: [
          {
            fa: "T-SQL", en: "T-SQL", kind: "hard", level: "alt",
            whyFa: "زبان رویه‌ای SQL Server؛ در سامانه‌های سازمانی قدیمی، منطق کسب‌وکار زیادی در همین رویه‌هاست.",
            whyEn: "SQL Server's procedural language; in older enterprise systems a lot of business logic lives in these procedures.",
            items: ["Variables & control flow", "Stored procedures", "Table-valued parameters", "TRY…CATCH", "Temp tables vs table variables"],
            tracks: ["05-sql"],
          },
          {
            fa: "PL/pgSQL", en: "PL/pgSQL", kind: "hard", level: "alt",
            whyFa: "زبان رویه‌ای PostgreSQL، با تابع‌هایی که می‌توانند جدول برگردانند.",
            whyEn: "PostgreSQL's procedural language, with functions that can return tables.",
            items: ["Functions & procedures", "DO blocks", "Exceptions", "RETURNS TABLE"],
          },
          {
            fa: "تابع", en: "Functions", kind: "hard",
            whyFa: "تابع اسکالر در WHERE برای هر ردیف اجرا می‌شود و می‌تواند کوئری را صد برابر کند کند.",
            whyEn: "A scalar function in WHERE runs once per row and can make a query a hundred times slower.",
            items: ["Scalar functions and their cost", "Inline table-valued functions", "Deterministic functions"],
          },
          {
            fa: "Trigger", en: "Triggers", kind: "hard", level: "opt",
            whyFa: "برای ممیزی مفید است، ولی منطق پنهانی می‌سازد که همه را غافلگیر می‌کند؛ کم و مستند استفاده کن.",
            whyEn: "Useful for auditing, but it creates hidden logic that surprises everyone; use sparingly and document it.",
            items: ["AFTER / INSTEAD OF", "Audit tables", "Why triggers surprise people"],
          },
        ],
      },
      {
        id: "sq-sec",
        fa: "امنیت و کار از داخل برنامه",
        en: "Security and use from applications",
        outcomeFa: "SQL را امن از داخل برنامه صدا می‌زنی و دسترسی‌ها را حداقلی تعریف می‌کنی.",
        outcomeEn: "You call SQL safely from applications and define minimal permissions.",
        months: [1, 1],
        skills: [
          {
            fa: "SQL injection", en: "SQL injection", kind: "hard",
            whyFa: "چسباندن ورودی کاربر به رشتهٔ کوئری هنوز هم یکی از رایج‌ترین راه‌های نفوذ است؛ پارامتر تنها راه درست است.",
            whyEn: "Concatenating user input into a query string is still one of the most common ways in; parameters are the only right answer.",
            items: ["Parameterised queries", "Dynamic SQL with sp_executesql", "ORM raw SQL pitfalls", "Least privilege"],
          },
          {
            fa: "دسترسی‌ها", en: "Permissions", kind: "hard",
            whyFa: "هر برنامه کاربر خودش را با کمترین دسترسی لازم داشته باشد؛ نشت یک رمز نباید کل پایگاه‌داده را ببرد.",
            whyEn: "Give each application its own user with the least access it needs; one leaked password should not cost the whole database.",
            items: ["Logins vs users", "Roles", "GRANT / DENY / REVOKE", "Row-level security"],
          },
          {
            fa: "SQL از داخل کد", en: "SQL from code", kind: "hard",
            whyFa: "ORM برای بیشتر کارها خوب است؛ ولی باید بدانی زیرش چه SQL‌ای اجرا می‌شود و کِی خودت بنویسی.",
            whyEn: "An ORM is fine for most work; but you should know what SQL it runs underneath and when to write your own.",
            items: ["ADO.NET / psycopg / JDBC", "ORMs vs raw SQL", "Connection pooling", "Migrations"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "توضیح دادن داده", en: "Explaining data", kind: "soft",
            whyFa: "کوئری‌ای که همکارت نتواند بخواند، کوئری‌ای است که کسی جرئت تغییرش را ندارد.",
            whyEn: "A query your colleague cannot read is a query nobody dares to change.",
            items: ["Readable formatting", "Comments on intent", "Sharing results clearly"],
            tracks: ["64-docs-writing"],
          },
        ],
      },
    ],
  },
];
