/* ============================================================================
   رودمپ تکنولوژی‌های فرانت‌اند: React، Angular، Next.js

   هر رودمپ از پیش‌نیاز شروع می‌کند و تا سطح ارشد می‌رود. موضوع‌های برگ
   (items) عمداً نام فنی انگلیسی‌اند — همان چیزی که در مستندات و آگهی شغلی
   می‌بینی. هر جا نسخهٔ خاصی مهم است (مثل proxy در Next 16 یا Signals در
   Angular)، در متن «چرا» گفته شده.
   ========================================================================== */
import type { Roadmap } from "./types";

export const TECH_WEB_ROADMAPS: Roadmap[] = [
  /* ═══════════════════════════════ React ═══════════════════════════════ */
  {
    id: "react",
    field: "tech",
    accent: "#61DAFB",
    ico: '<circle cx="12" cy="12" r="1.9"/><ellipse cx="12" cy="12" rx="9.6" ry="3.8"/><ellipse cx="12" cy="12" rx="9.6" ry="3.8" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="9.6" ry="3.8" transform="rotate(120 12 12)"/>',
    after: ["foundations"],
    next: ["nextjs", "frontend"],
    fa: {
      name: "React",
      role: "React Developer",
      intro:
        "React کتابخانه‌ای برای ساختن رابط کاربری از قطعه‌های کوچک و قابل‌ترکیب است. ایده‌اش ساده است — رابط کاربری تابعی از حالت است — ولی تسلط بر آن یعنی بدانی حالت کجا بنشیند، اثر جانبی کِی اجرا شود و چه چیزی دوباره رندر می‌شود. این رودمپ از جاوااسکریپت شروع می‌کند و تا Server Components و معماری پروژه‌های بزرگ می‌رود.",
    },
    en: {
      name: "React",
      role: "React Developer",
      intro:
        "React is a library for building user interfaces out of small, composable pieces. The idea is simple — UI is a function of state — but mastering it means knowing where state should live, when an effect runs and what re-renders. This roadmap starts from JavaScript and goes all the way to Server Components and the architecture of large projects.",
    },
    stages: [
      {
        id: "re-pre",
        fa: "پیش‌نیازها",
        en: "Prerequisites",
        outcomeFa: "جاوااسکریپت مدرن را راحت می‌خوانی و می‌نویسی و یک پروژهٔ Vite را از صفر بالا می‌آوری.",
        outcomeEn: "You read and write modern JavaScript comfortably and can scaffold a Vite project from scratch.",
        months: [1, 3],
        skills: [
          {
            fa: "HTML و CSS", en: "HTML and CSS", kind: "hard",
            whyFa: "React در نهایت HTML و CSS تولید می‌کند. اگر Flexbox و Grid را نفهمی، هیچ کتابخانه‌ای نجاتت نمی‌دهد.",
            whyEn: "React ultimately emits HTML and CSS. If you do not understand Flexbox and Grid, no library will save you.",
            items: ["Semantic HTML", "Forms", "Flexbox", "CSS Grid", "Media queries", "Logical properties (RTL)"],
            tracks: ["66-html", "67-css"],
          },
          {
            fa: "جاوااسکریپت مدرن", en: "Modern JavaScript", kind: "hard",
            whyFa: "نیمی از «باگ‌های React» در واقع نفهمیدن closure، ارجاع شیء یا async است.",
            whyEn: "Half of all “React bugs” are really misunderstandings of closures, object references or async code.",
            items: ["let / const", "Arrow functions", "Destructuring", "Spread / rest", "ES modules", "map / filter / reduce", "Closures", "Promises & async/await", "Event loop"],
            tracks: ["41-javascript"],
          },
          {
            fa: "TypeScript", en: "TypeScript", kind: "hard",
            whyFa: "در پروژهٔ تیمی عملاً استاندارد است؛ props تایپ‌دار یعنی کامپوننت را بدون خواندن کدش درست استفاده می‌کنی.",
            whyEn: "It is effectively standard on teams; typed props mean you can use a component correctly without reading its code.",
            items: ["Types & interfaces", "Union & literal types", "Generics", "Narrowing", "Utility types", "Typing props & events"],
            tracks: ["42-typescript"],
          },
          {
            fa: "ابزار: npm، Vite، ESLint", en: "Tooling: npm, Vite, ESLint", kind: "hard",
            whyFa: "باید بدانی dev server چه می‌کند و bundle از کجا می‌آید، وگرنه اولین خطای build متوقفت می‌کند.",
            whyEn: "You need to know what the dev server does and where the bundle comes from, or the first build error stops you cold.",
            items: ["npm / pnpm", "package.json scripts", "Vite", "ESLint", "Prettier"],
            tracks: ["36-packaging"],
          },
          {
            fa: "Git", en: "Git", kind: "hard",
            whyFa: "هر پروژهٔ واقعی روی Git است؛ بدون شاخه و Pull Request نمی‌توانی در تیم کار کنی.",
            whyEn: "Every real project lives in Git; without branches and pull requests you cannot work on a team.",
            items: ["commit / branch / merge", "Pull requests", "rebase", ".gitignore"],
            tracks: ["28-git"],
          },
          {
            fa: "خواندن مستندات رسمی", en: "Reading the official docs", kind: "soft",
            whyFa: "مستندات react.dev بازنویسی شده و بهترین منبع است؛ خیلی از آموزش‌های قدیمی هنوز کامپوننت کلاسی و الگوهای منسوخ یاد می‌دهند.",
            whyEn: "The react.dev docs were rewritten and are the best source; many older tutorials still teach class components and outdated patterns.",
            items: ["react.dev", "MDN", "Release notes"],
          },
        ],
      },
      {
        id: "re-core",
        fa: "هستهٔ React",
        en: "React fundamentals",
        outcomeFa: "یک اپ کوچک چندکامپوننتی می‌سازی و می‌دانی داده چطور از بالا به پایین جریان دارد.",
        outcomeEn: "You build a small multi-component app and know how data flows from top to bottom.",
        months: [1, 2],
        skills: [
          {
            fa: "JSX و کامپوننت", en: "JSX and components", kind: "hard",
            whyFa: "کامپوننت واحد فکر کردن در React است؛ JSX فقط شکر نحوی برای فراخوانی تابع است.",
            whyEn: "The component is React's unit of thought; JSX is just syntax sugar for function calls.",
            items: ["JSX rules", "Function components", "Fragments", "Composition over inheritance", "children prop"],
            tracks: ["15-react"],
          },
          {
            fa: "Props و State", en: "Props and state", kind: "hard",
            whyFa: "تمایز این دو پایهٔ همه‌چیز است: props از بیرون می‌آید و فقط‌خواندنی است؛ state مال خود کامپوننت است.",
            whyEn: "The distinction underlies everything: props come from outside and are read-only; state belongs to the component.",
            items: ["Read-only props", "useState", "Lifting state up", "Immutable updates", "Derived values"],
            tracks: ["15-react"],
          },
          {
            fa: "رندر شرطی و فهرست‌ها", en: "Conditional rendering and lists", kind: "hard",
            whyFa: "کلید (key) اشتباه یکی از رایج‌ترین باگ‌هاست: ورودی‌ها جای هم را می‌گیرند و حالت به ردیف اشتباه می‌چسبد.",
            whyEn: "A wrong key is one of the most common bugs: inputs swap places and state sticks to the wrong row.",
            items: ["&& and ternaries", "Early return", "Lists & keys", "Why not the index as key"],
          },
          {
            fa: "رویدادها و فرم‌ها", en: "Events and forms", kind: "hard",
            whyFa: "بیشتر تعامل کاربر فرم است؛ ورودی کنترل‌شده و ارسال فرم را باید بی‌فکر بنویسی.",
            whyEn: "Most user interaction is forms; you should write controlled inputs and submissions without thinking.",
            items: ["Synthetic events", "Controlled vs uncontrolled inputs", "onSubmit & preventDefault", "Form actions (React 19)", "useActionState", "useFormStatus"],
          },
          {
            fa: "چرخهٔ رندر", en: "The render cycle", kind: "hard",
            whyFa: "وقتی فرق render و commit را بدانی، می‌فهمی چرا console.log دو بار چاپ می‌شود و چرا تغییر مستقیم state کار نمی‌کند.",
            whyEn: "Once you know render from commit, you understand why console.log prints twice and why mutating state does nothing.",
            items: ["Trigger → render → commit", "Reconciliation", "StrictMode double invoke", "State as a snapshot", "Batching"],
          },
          {
            fa: "فکر کردن به سبک React", en: "Thinking in React", kind: "hard",
            whyFa: "تبدیل یک طرح به درخت کامپوننت و پیدا کردن کمترین حالت لازم، مهارتی است که کد تمیز از آن بیرون می‌آید.",
            whyEn: "Turning a mockup into a component tree and finding the minimal state is the skill clean code comes from.",
            items: ["Break the UI into a hierarchy", "Minimal state", "Where state lives", "One-way data flow"],
          },
        ],
      },
      {
        id: "re-hooks",
        fa: "هوک‌ها، عمیق",
        en: "Hooks in depth",
        outcomeFa: "اثر جانبی را فقط وقتی لازم است می‌نویسی، منطق را در هوک سفارشی بیرون می‌کشی و رندر اضافه را پیدا می‌کنی.",
        outcomeEn: "You write effects only when needed, extract logic into custom hooks and track down unnecessary renders.",
        months: [1, 2],
        skills: [
          {
            fa: "useEffect", en: "useEffect", kind: "hard",
            whyFa: "پرخطاترین هوک React. قاعدهٔ طلایی: effect برای همگام شدن با سیستم بیرونی است، نه برای محاسبهٔ داده.",
            whyEn: "React's most error-prone hook. Golden rule: effects synchronise with external systems; they are not for computing data.",
            items: ["Dependency array", "Cleanup", "You might not need an effect", "Race conditions & AbortController", "useLayoutEffect"],
          },
          {
            fa: "useRef و DOM", en: "useRef and the DOM", kind: "hard",
            whyFa: "برای مقداری که باید بماند ولی رندر نگیرد، و برای دسترسی مستقیم به DOM: فوکوس، اندازه‌گیری، پخش ویدیو.",
            whyEn: "For values that persist without causing renders, and for direct DOM access: focus, measuring, playing video.",
            items: ["useRef", "ref as a prop (React 19)", "useImperativeHandle", "createPortal"],
          },
          {
            fa: "useContext", en: "useContext", kind: "hard",
            whyFa: "راه‌حل prop drilling؛ ولی هر تغییر مقدار، همهٔ مصرف‌کننده‌ها را رندر می‌کند — پس برای دادهٔ پرتغییر مناسب نیست.",
            whyEn: "The fix for prop drilling; but every value change re-renders all consumers, so it suits rarely-changing data.",
            items: ["createContext", "Provider", "Splitting contexts", "Context + reducer"],
          },
          {
            fa: "useReducer", en: "useReducer", kind: "hard",
            whyFa: "وقتی چند state با هم عوض می‌شوند، reducer منطق را یک‌جا و قابل تست نگه می‌دارد.",
            whyEn: "When several pieces of state change together, a reducer keeps the logic in one testable place.",
            items: ["Reducer function", "Actions", "Immer", "Reducer + context"],
          },
          {
            fa: "Memoization", en: "Memoisation", kind: "hard",
            whyFa: "بهینه‌سازی است نه پیش‌فرض. اول اندازه بگیر؛ React Compiler هم بخش زیادی از این کار را خودکار انجام می‌دهد.",
            whyEn: "An optimisation, not a default. Measure first; the React Compiler now automates much of it.",
            items: ["useMemo", "useCallback", "React.memo", "React Compiler"],
          },
          {
            fa: "هوک سفارشی", en: "Custom hooks", kind: "hard",
            whyFa: "راه اصلی استفادهٔ دوباره از منطق در React؛ جای mixin و HOC را گرفته است.",
            whyEn: "React's main way to reuse logic; it replaced mixins and higher-order components.",
            items: ["use* naming", "Rules of Hooks", "eslint-plugin-react-hooks", "Composing hooks"],
          },
          {
            fa: "ویژگی‌های همروند", en: "Concurrent features", kind: "hard",
            whyFa: "رابط کاربری را زیر کار سنگین پاسخ‌گو نگه می‌دارد و پایهٔ Suspense و Server Components است.",
            whyEn: "Keeps the UI responsive under heavy work and underpins Suspense and Server Components.",
            items: ["useTransition", "useDeferredValue", "Suspense", "use()", "useOptimistic"],
          },
        ],
      },
      {
        id: "re-style",
        fa: "استایل‌دهی",
        en: "Styling",
        outcomeFa: "یک روش استایل را برای تیم انتخاب می‌کنی و می‌توانی دلیلش را توضیح بدهی.",
        outcomeEn: "You pick a styling approach for a team and can explain why.",
        months: [1, 1],
        skills: [
          {
            fa: "CSS Modules", en: "CSS Modules", kind: "hard",
            whyFa: "همان CSS معمولی با کلاس‌های محلی؛ بدون هزینهٔ زمان اجرا و بدون تداخل نام.",
            whyEn: "Plain CSS with locally scoped classes; no runtime cost and no name clashes.",
            items: ["*.module.css", "Scoped class names", "composes", "CSS variables for theming"],
            tracks: ["67-css"],
          },
          {
            fa: "Tailwind CSS", en: "Tailwind CSS", kind: "hard", level: "alt",
            whyFa: "سریع‌ترین راه از طرح تا صفحه، و رایج‌ترین انتخاب پروژه‌های جدید.",
            whyEn: "The fastest path from mockup to page, and the most common choice for new projects.",
            items: ["Utility classes", "Responsive & state variants", "Dark mode", "Theme tokens", "clsx / tailwind-merge"],
            tracks: ["69-tailwind"],
          },
          {
            fa: "Sass", en: "Sass", kind: "hard", level: "alt",
            whyFa: "در پروژه‌های قدیمی‌تر و سازمانی زیاد می‌بینی‌اش: متغیر، mixin و تودرتویی.",
            whyEn: "Common in older and enterprise codebases: variables, mixins and nesting.",
            items: ["@use", "Nesting", "Mixins", "Partials"],
            tracks: ["68-sass"],
          },
          {
            fa: "CSS-in-JS", en: "CSS-in-JS", kind: "hard", level: "opt",
            whyFa: "styled-components و Emotion هنوز در کدهای موجود هستند، ولی هزینهٔ زمان اجرا دارند و با Server Components جور نیستند.",
            whyEn: "styled-components and Emotion still live in existing code, but they cost runtime and do not fit Server Components.",
            items: ["styled-components", "Emotion", "Zero-runtime: vanilla-extract, Linaria"],
          },
          {
            fa: "کتابخانهٔ کامپوننت", en: "Component libraries", kind: "hard", level: "opt",
            whyFa: "برای پنل مدیریت و ابزار داخلی وقت زیادی می‌خرد؛ محصول مصرفی معمولاً طراحی سفارشی می‌خواهد.",
            whyEn: "Buys a lot of time for admin panels and internal tools; consumer products usually want a custom design.",
            items: ["shadcn/ui", "Radix UI", "MUI", "Ant Design", "Headless UI"],
          },
        ],
      },
      {
        id: "re-data",
        fa: "مسیریابی، فرم و دادهٔ سرور",
        en: "Routing, forms and server data",
        outcomeFa: "یک اپ چندصفحه‌ای با داده از API، حالت بارگذاری و خطا و فرم اعتبارسنجی‌شده می‌سازی.",
        outcomeEn: "You build a multi-page app with API data, loading and error states and validated forms.",
        months: [1, 2],
        skills: [
          {
            fa: "React Router", en: "React Router", kind: "hard",
            whyFa: "استاندارد مسیریابی سمت کلاینت؛ نسخهٔ ۷ loader و action هم دارد و به یک فریم‌ورک نزدیک شده است.",
            whyEn: "The standard client-side router; v7 adds loaders and actions and is close to a framework.",
            items: ["Nested routes & layouts", "Route params", "useNavigate", "Loaders & actions", "Protected routes"],
          },
          {
            fa: "TanStack Router", en: "TanStack Router", kind: "hard", level: "alt",
            whyFa: "مسیرها و پارامترهای جستجوی کاملاً تایپ‌دار؛ انتخاب خوبی برای اپ‌های پیچیدهٔ سمت کلاینت.",
            whyEn: "Fully type-safe routes and search params; a strong choice for complex client-side apps.",
            items: ["Type-safe links", "Search params as state", "File-based routes"],
          },
          {
            fa: "دریافت داده", en: "Data fetching", kind: "hard",
            whyFa: "حالت سرور با حالت کلاینت فرق دارد: کش، تازه‌سازی و همگام‌سازی می‌خواهد. TanStack Query دقیقاً همین را حل کرده است.",
            whyEn: "Server state is not client state: it needs caching, refetching and syncing. TanStack Query solves exactly that.",
            items: ["fetch + AbortController", "Loading / error / empty states", "TanStack Query", "Cache invalidation", "Optimistic updates", "Infinite queries"],
            tracks: ["48-state-management"],
          },
          {
            fa: "SWR یا RTK Query", en: "SWR or RTK Query", kind: "hard", level: "alt",
            whyFa: "هم‌ارز TanStack Query؛ اگر پروژه Redux دارد، RTK Query طبیعی‌تر است.",
            whyEn: "Equivalents of TanStack Query; if the project already uses Redux, RTK Query fits more naturally.",
            items: ["SWR", "RTK Query", "stale-while-revalidate"],
          },
          {
            fa: "فرم و اعتبارسنجی", en: "Forms and validation", kind: "hard",
            whyFa: "فرم بزرگ با useState کند و شلوغ می‌شود؛ React Hook Form و Zod یک طرح‌واره را هم برای تایپ و هم برای اعتبارسنجی به کار می‌برند.",
            whyEn: "Large forms get slow and messy with useState; React Hook Form plus Zod use one schema for both types and validation.",
            items: ["React Hook Form", "Zod", "Field arrays", "Accessible error messages", "Validate on the server too"],
          },
          {
            fa: "GraphQL", en: "GraphQL", kind: "hard", level: "opt",
            whyFa: "وقتی بک‌اند GraphQL حرف می‌زند لازم می‌شود؛ وگرنه REST کافی است.",
            whyEn: "Needed when the backend speaks GraphQL; otherwise REST is enough.",
            items: ["Queries & mutations", "Apollo Client", "urql", "GraphQL Codegen"],
          },
        ],
      },
      {
        id: "re-state",
        fa: "مدیریت حالت سراسری",
        en: "Global state management",
        outcomeFa: "می‌دانی کِی کتابخانهٔ حالت لازم نیست، و وقتی لازم است درست انتخابش می‌کنی.",
        outcomeEn: "You know when a state library is unnecessary — and when it is, you pick well.",
        months: [1, 2],
        skills: [
          {
            fa: "اول حالت محلی", en: "Local state first", kind: "hard",
            whyFa: "بیشتر اپ‌ها با state محلی، context و یک کتابخانهٔ دادهٔ سرور تمام می‌شوند. کتابخانهٔ سراسری را آخر اضافه کن.",
            whyEn: "Most apps are done with local state, context and a server-data library. Add a global store last.",
            items: ["Colocation", "Derived state", "URL as state", "Server state vs client state"],
            tracks: ["48-state-management"],
          },
          {
            fa: "Zustand", en: "Zustand", kind: "hard", level: "alt",
            whyFa: "کوچک، بدون Provider و بدون کد تکراری؛ رایج‌ترین انتخاب پروژه‌های جدید.",
            whyEn: "Tiny, no provider, no boilerplate; the most common pick for new projects.",
            items: ["create()", "Selectors", "persist middleware", "devtools", "Slices pattern"],
            tracks: ["48-state-management"],
          },
          {
            fa: "Redux Toolkit", en: "Redux Toolkit", kind: "hard", level: "alt",
            whyFa: "در کدهای سازمانی موجود همه‌جا هست؛ RTK همان Redux امروزی است، بدون کد تکراری قدیمی.",
            whyEn: "Everywhere in existing enterprise code; RTK is modern Redux without the old boilerplate.",
            items: ["configureStore", "createSlice", "Immer", "createAsyncThunk", "Redux DevTools"],
            tracks: ["48-state-management"],
          },
          {
            fa: "Jotai", en: "Jotai", kind: "hard", level: "opt",
            whyFa: "حالت اتمی: هر تکه جداست و فقط مصرف‌کنندهٔ همان تکه دوباره رندر می‌شود.",
            whyEn: "Atomic state: each piece is separate and only that piece's consumers re-render.",
            items: ["atom", "Derived atoms", "Async atoms"],
          },
          {
            fa: "ماشین حالت", en: "State machines", kind: "hard", level: "opt",
            whyFa: "برای جریان‌های پیچیده مثل پرداخت یا ویزارد چندمرحله‌ای، حالت‌های ناممکن را واقعاً ناممکن می‌کند.",
            whyEn: "For complex flows like checkout or multi-step wizards, it makes impossible states truly impossible.",
            items: ["Finite state machines", "Statecharts", "XState"],
          },
        ],
      },
      {
        id: "re-test",
        fa: "تست",
        en: "Testing",
        outcomeFa: "برای رفتار کاربر تست می‌نویسی نه برای جزئیات پیاده‌سازی، و تست‌ها در CI اجرا می‌شوند.",
        outcomeEn: "You test user behaviour rather than implementation details, and tests run in CI.",
        months: [1, 2],
        skills: [
          {
            fa: "تست واحد و کامپوننت", en: "Unit and component tests", kind: "hard",
            whyFa: "Testing Library مجبورت می‌کند مثل کاربر فکر کنی: دکمه را با نقشش پیدا کن، نه با کلاس CSS.",
            whyEn: "Testing Library forces you to think like a user: find the button by its role, not its CSS class.",
            items: ["Vitest", "Jest", "React Testing Library", "user-event", "Queries by role", "jsdom"],
          },
          {
            fa: "شبیه‌سازی شبکه", en: "Mocking the network", kind: "hard",
            whyFa: "با MSW درخواست را در سطح شبکه جواب می‌دهی؛ همان mockها در تست، Storybook و توسعه کار می‌کنند.",
            whyEn: "MSW answers requests at the network level; the same mocks work in tests, Storybook and development.",
            items: ["MSW", "Fixtures", "Error & slow responses"],
          },
          {
            fa: "تست سرتاسری", en: "End-to-end tests", kind: "hard",
            whyFa: "چند تست E2E روی مسیرهای حیاتی مثل ورود و پرداخت، از صد تست واحد اطمینان بیشتری می‌دهد.",
            whyEn: "A few E2E tests on critical paths like login and checkout give more confidence than a hundred unit tests.",
            items: ["Playwright", "Cypress", "Locators", "Trace viewer", "Running in CI"],
            tracks: ["04-devops"],
          },
          {
            fa: "Storybook", en: "Storybook", kind: "hard", level: "opt",
            whyFa: "کامپوننت را جدا از اپ می‌سازی و مستند می‌کنی؛ پایهٔ خوبی برای design system.",
            whyEn: "Build and document components in isolation; a solid base for a design system.",
            items: ["Stories", "Controls", "Interaction tests", "Visual regression"],
          },
        ],
      },
      {
        id: "re-perf",
        fa: "کارایی و دسترس‌پذیری",
        en: "Performance and accessibility",
        outcomeFa: "کندی را با Profiler پیدا می‌کنی نه با حدس، و اپ با کیبورد و صفحه‌خوان کار می‌کند.",
        outcomeEn: "You find slowness with the Profiler rather than guesses, and the app works with a keyboard and a screen reader.",
        months: [1, 2],
        skills: [
          {
            fa: "پروفایل کردن", en: "Profiling", kind: "hard",
            whyFa: "بدون اندازه‌گیری، بهینه‌سازی فقط جابه‌جا کردن مشکل است.",
            whyEn: "Without measurement, optimisation just moves the problem around.",
            items: ["React DevTools Profiler", "Highlight updates", "Chrome Performance panel", "why-did-you-render"],
          },
          {
            fa: "تقسیم کد", en: "Code splitting", kind: "hard",
            whyFa: "کاربر نباید کد صفحهٔ مدیریت را برای دیدن صفحهٔ اول دانلود کند.",
            whyEn: "A user should not download the admin page's code to see the home page.",
            items: ["React.lazy", "Suspense boundaries", "Dynamic import()", "Bundle analyzer"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "فهرست‌های بزرگ", en: "Large lists", kind: "hard",
            whyFa: "رندر ده هزار ردیف مرورگر را قفل می‌کند؛ مجازی‌سازی فقط ردیف‌های قابل‌دید را می‌سازد.",
            whyEn: "Rendering ten thousand rows locks up the browser; virtualisation only builds the visible ones.",
            items: ["Virtualisation", "TanStack Virtual", "react-window", "Pagination vs infinite scroll"],
          },
          {
            fa: "Core Web Vitals", en: "Core Web Vitals", kind: "hard",
            whyFa: "همان معیارهایی که گوگل با آن رتبه می‌دهد؛ INP مستقیماً به رندرهای سنگین React حساس است.",
            whyEn: "The metrics Google ranks by; INP is directly sensitive to heavy React renders.",
            items: ["LCP", "INP", "CLS", "Lighthouse", "web-vitals library"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "دسترس‌پذیری", en: "Accessibility", kind: "hard",
            whyFa: "div قابل‌کلیک دکمه نیست. دسترس‌پذیری در خیلی از کشورها الزام قانونی است و موتور جستجو هم از آن سود می‌برد.",
            whyEn: "A clickable div is not a button. Accessibility is a legal requirement in many countries, and search engines benefit too.",
            items: ["Semantic elements", "ARIA roles & labels", "Focus management", "Keyboard navigation", "axe DevTools"],
            tracks: ["66-html"],
          },
        ],
      },
      {
        id: "re-server",
        fa: "رندر سمت سرور و اکوسیستم",
        en: "Server rendering and the ecosystem",
        outcomeFa: "فرق CSR، SSR و RSC را می‌دانی و یک اپ Next.js را منتشر می‌کنی.",
        outcomeEn: "You know CSR from SSR from RSC and can ship a Next.js app.",
        months: [2, 3],
        skills: [
          {
            fa: "حالت‌های رندر", en: "Rendering modes", kind: "hard",
            whyFa: "این تصمیم روی سرعت بار اول، SEO و هزینهٔ سرور اثر مستقیم دارد.",
            whyEn: "This decision directly affects first-load speed, SEO and server cost.",
            items: ["CSR", "SSR", "SSG", "ISR", "Streaming", "Hydration"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "Server Components", en: "Server Components", kind: "hard",
            whyFa: "بزرگ‌ترین تغییر React از زمان هوک‌ها: کامپوننتی که فقط روی سرور اجرا می‌شود و صفر بایت جاوااسکریپت به مرورگر می‌فرستد.",
            whyEn: "React's biggest change since hooks: components that run only on the server and ship zero JavaScript to the browser.",
            items: ["'use client'", "'use server'", "Server Actions", "Serialisable props", "Suspense streaming"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "Next.js", en: "Next.js", kind: "hard",
            whyFa: "پرکاربردترین فریم‌ورک React و مرجع پیاده‌سازی Server Components — رودمپ جدای خودش را دارد.",
            whyEn: "The most used React framework and the reference implementation of Server Components — it has its own roadmap.",
            items: ["App Router", "Layouts", "Data fetching & caching", "Route handlers", "Deployment"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "React Router v7 / Remix", en: "React Router v7 / Remix", kind: "hard", level: "alt",
            whyFa: "جایگزین Next با تکیه بر استانداردهای وب: Request، Response و فرم.",
            whyEn: "An alternative to Next built on web standards: Request, Response and forms.",
            items: ["Framework mode", "Loaders", "Actions", "Progressive enhancement"],
          },
          {
            fa: "React Native", en: "React Native", kind: "hard", level: "opt",
            whyFa: "همان مفاهیم React برای اپ موبایل بومی؛ با Expo شروعش ساده است.",
            whyEn: "The same React concepts for native mobile apps; Expo makes starting easy.",
            items: ["Expo", "Core components", "React Navigation", "EAS Build"],
            tracks: ["37-mobile-release"],
          },
        ],
      },
      {
        id: "re-arch",
        fa: "معماری و کار تیمی",
        en: "Architecture and teamwork",
        outcomeFa: "ساختاری طراحی می‌کنی که با ده توسعه‌دهنده و صد صفحه هم قابل نگه‌داری بماند.",
        outcomeEn: "You design a structure that stays maintainable with ten developers and a hundred pages.",
        months: [2, 4],
        skills: [
          {
            fa: "ساختار پروژه", en: "Project structure", kind: "hard",
            whyFa: "پوشه‌بندی بر اساس ویژگی، نه نوع فایل. وقتی چیزی را حذف می‌کنی باید بدانی دقیقاً کدام فایل‌ها می‌روند.",
            whyEn: "Organise by feature, not file type. When you delete something you should know exactly which files go.",
            items: ["Feature folders", "A public API per feature", "Path aliases", "Barrel-file pitfalls"],
            tracks: ["07-architecture"],
          },
          {
            fa: "Design system", en: "Design systems", kind: "hard",
            whyFa: "یکدستی رابط کاربری در مقیاس بزرگ فقط با توکن‌های طراحی و کامپوننت‌های پایهٔ مشترک ممکن است.",
            whyEn: "UI consistency at scale is only possible with design tokens and shared base components.",
            items: ["Design tokens", "Component API design", "Theming & dark mode", "Documentation"],
          },
          {
            fa: "Monorepo", en: "Monorepos", kind: "hard", level: "opt",
            whyFa: "وقتی چند اپ یک کتابخانهٔ کامپوننت مشترک دارند، monorepo نسخه‌بندی را ساده می‌کند.",
            whyEn: "When several apps share a component library, a monorepo simplifies versioning.",
            items: ["pnpm workspaces", "Turborepo", "Nx", "Changesets"],
            tracks: ["36-packaging"],
          },
          {
            fa: "Micro-frontends", en: "Micro-frontends", kind: "hard", level: "opt",
            whyFa: "برای سازمان‌های بزرگ با تیم‌های مستقل؛ برای تیم کوچک، پیچیدگی بی‌دلیل است.",
            whyEn: "For large organisations with independent teams; for a small team it is needless complexity.",
            items: ["Module Federation", "single-spa", "Shared dependencies", "When not to"],
            tracks: ["08-microservices"],
          },
          {
            fa: "بازبینی کد", en: "Code review", kind: "soft",
            whyFa: "بیشترین یادگیری در تیم از بازبینی کد می‌آید — به شرطی که نقد به کد باشد نه به آدم.",
            whyEn: "Most learning on a team comes through code review — provided the critique targets the code, not the person.",
            items: ["Small PRs", "Actionable comments", "Review checklists"],
            tracks: ["22-skills"],
          },
          {
            fa: "همکاری با طراح و محصول", en: "Working with design and product", kind: "soft",
            whyFa: "«منظورم این نبود» بیشتر مشکل گفت‌وگوست تا مشکل فنی؛ طرح را پیش از کد با طراح مرور کن.",
            whyEn: "“That is not what I meant” is more often a conversation problem than a technical one; review the design with the designer before coding.",
            items: ["Figma handoff", "Edge cases & empty states", "Estimating"],
            tracks: ["22-skills", "63-scrum-agile"],
          },
        ],
      },
    ],
  },

  /* ══════════════════════════════ Angular ══════════════════════════════ */
  {
    id: "angular",
    field: "tech",
    accent: "#DD0031",
    ico: '<path d="M12 2.8 3.6 5.8l1.3 11.1L12 21.2l7.1-4.3 1.3-11.1z" stroke-linejoin="round"/><path d="m8.6 16 3.4-8.4 3.4 8.4M9.8 13.2h4.4" stroke-linecap="round" stroke-linejoin="round"/>',
    after: ["foundations"],
    next: ["frontend", "architect"],
    fa: {
      name: "Angular",
      role: "Angular Developer",
      intro:
        "Angular یک فریم‌ورک کامل و «باسلیقه» است: مسیریاب، فرم، HTTP، تزریق وابستگی و ابزار تست را خودش دارد و برای هر کدام یک راه مشخص پیشنهاد می‌کند. به همین دلیل در پروژه‌های سازمانی بزرگ محبوب است. نسخه‌های اخیر با Signals، کامپوننت‌های standalone و حالت بدون Zone.js آن را سبک‌تر و سریع‌تر کرده‌اند — این رودمپ Angular امروزی را یاد می‌دهد، نه نسخهٔ ده سال پیش را.",
    },
    en: {
      name: "Angular",
      role: "Angular Developer",
      intro:
        "Angular is a complete, opinionated framework: routing, forms, HTTP, dependency injection and testing come built in, each with one recommended way. That is why large enterprise projects love it. Recent versions made it lighter and faster with Signals, standalone components and zoneless mode — this roadmap teaches today's Angular, not the one from ten years ago.",
    },
    stages: [
      {
        id: "ng-pre",
        fa: "پیش‌نیازها",
        en: "Prerequisites",
        outcomeFa: "با TypeScript راحتی و با Angular CLI پروژه می‌سازی، اجرا می‌کنی و ارتقا می‌دهی.",
        outcomeEn: "You are at home in TypeScript and can create, run and upgrade a project with the Angular CLI.",
        months: [1, 3],
        skills: [
          {
            fa: "HTML و CSS", en: "HTML and CSS", kind: "hard",
            whyFa: "قالب Angular در نهایت HTML است؛ بدون چیدمان و فرم معنایی، هر کامپوننتی شکننده می‌شود.",
            whyEn: "An Angular template is HTML in the end; without layout and semantic forms, every component turns fragile.",
            items: ["Semantic HTML", "Forms", "Flexbox & Grid", "Responsive design"],
            tracks: ["66-html", "67-css"],
          },
          {
            fa: "جاوااسکریپت", en: "JavaScript", kind: "hard",
            whyFa: "this، کلاس، ماژول و Promise را باید بشناسی، چون Angular روی همه‌شان ساخته شده است.",
            whyEn: "You need this, classes, modules and Promises, because Angular is built on all of them.",
            items: ["Classes", "this binding", "ES modules", "Promises & async/await", "Array methods"],
            tracks: ["41-javascript"],
          },
          {
            fa: "TypeScript، عمیق", en: "TypeScript, deeply", kind: "hard",
            whyFa: "Angular بدون TypeScript نوشته نمی‌شود؛ decorator، generic و حالت strict را هر روز می‌بینی.",
            whyEn: "Angular is not written without TypeScript; decorators, generics and strict mode are daily fare.",
            items: ["Classes & access modifiers", "Interfaces & generics", "Decorators", "strict mode", "Union types & narrowing"],
            tracks: ["42-typescript"],
          },
          {
            fa: "Angular CLI و Node", en: "Angular CLI and Node", kind: "hard",
            whyFa: "همه‌چیز از CLI می‌گذرد: ساختن، تولید کد، build و ارتقای نسخه.",
            whyEn: "Everything goes through the CLI: creating, generating code, building and upgrading.",
            items: ["Node.js LTS", "npm", "ng new / serve / generate", "angular.json", "ng update"],
          },
          {
            fa: "Git", en: "Git", kind: "hard",
            whyFa: "پروژه‌های Angular معمولاً تیمی و بزرگ‌اند؛ شاخه و Pull Request روال روزانه است.",
            whyEn: "Angular projects are usually big team efforts; branches and pull requests are the daily routine.",
            items: ["Branching", "Pull requests", "Merge conflicts"],
            tracks: ["28-git"],
          },
          {
            fa: "خواندن مستندات رسمی", en: "Reading the official docs", kind: "soft",
            whyFa: "angular.dev مستندات جدید با آموزش تعاملی است؛ خیلی از مقاله‌های اینترنت هنوز NgModule و الگوهای قدیمی را نشان می‌دهند.",
            whyEn: "angular.dev holds the new docs with interactive tutorials; many articles online still show NgModules and old patterns.",
            items: ["angular.dev", "Update guide", "Roadmap & RFCs"],
          },
        ],
      },
      {
        id: "ng-core",
        fa: "مبانی کامپوننت",
        en: "Component fundamentals",
        outcomeFa: "کامپوننت standalone می‌سازی، داده را با قالب وصل می‌کنی و والد و فرزند را به هم مرتبط می‌کنی.",
        outcomeEn: "You build standalone components, bind data in templates and wire parents to children.",
        months: [1, 2],
        skills: [
          {
            fa: "کامپوننت standalone", en: "Standalone components", kind: "hard",
            whyFa: "از نسخهٔ ۱۷ پیش‌فرض است؛ هر کامپوننت وابستگی‌هایش را خودش import می‌کند و دیگر NgModule لازم نیست.",
            whyEn: "The default since v17; each component imports its own dependencies and NgModules are no longer needed.",
            items: ["@Component", "imports array", "Selector & template", "View encapsulation", "Lifecycle hooks"],
            tracks: ["17-angular"],
          },
          {
            fa: "قالب و اتصال داده", en: "Templates and data binding", kind: "hard",
            whyFa: "زبان قالب Angular چهار نوع اتصال دارد؛ بیشتر خطاهای تازه‌کارها قاطی کردن همین چهار تاست.",
            whyEn: "Angular's template language has four binding kinds; most beginner errors come from mixing them up.",
            items: ["Interpolation {{ }}", "Property binding [ ]", "Event binding ( )", "Two-way binding [( )]", "Template reference variables"],
            tracks: ["17-angular"],
          },
          {
            fa: "کنترل جریان جدید", en: "Built-in control flow", kind: "hard",
            whyFa: "نحو جدید جای ‎*ngIf‎ و ‎*ngFor‎ را گرفته، سریع‌تر است و track را اجباری می‌کند — همان کاری که key در React می‌کند.",
            whyEn: "The new syntax replaced *ngIf and *ngFor, is faster, and makes track mandatory — the job key does in React.",
            items: ["@if / @else", "@for with track", "@switch", "@defer", "@let"],
          },
          {
            fa: "ورودی و خروجی", en: "Inputs and outputs", kind: "hard",
            whyFa: "راه ارتباط والد و فرزند؛ نسخهٔ مبتنی بر signal آن‌ها ساده‌تر و تایپ‌دارتر است.",
            whyEn: "How parents and children talk; the signal-based versions are simpler and better typed.",
            items: ["input() / input.required()", "output()", "model()", "@Input / @Output (legacy)", "Content projection"],
          },
          {
            fa: "دایرکتیو و pipe", en: "Directives and pipes", kind: "hard",
            whyFa: "دایرکتیو به عنصر رفتار اضافه می‌کند و pipe داده را برای نمایش تبدیل می‌کند؛ هر دو جلوی تکرار در قالب را می‌گیرند.",
            whyEn: "Directives add behaviour to elements and pipes transform data for display; both stop repetition in templates.",
            items: ["Attribute directives", "Structural directives", "Built-in pipes", "Custom pipes", "Pure vs impure", "Host bindings"],
          },
        ],
      },
      {
        id: "ng-di",
        fa: "تزریق وابستگی و سرویس‌ها",
        en: "Dependency injection and services",
        outcomeFa: "منطق را در سرویس می‌گذاری و می‌دانی Angular هر وابستگی را از کدام سطح پیدا می‌کند.",
        outcomeEn: "You put logic in services and know which level Angular resolves each dependency from.",
        months: [1, 1],
        skills: [
          {
            fa: "سرویس و provider", en: "Services and providers", kind: "hard",
            whyFa: "تزریق وابستگی قلب Angular است؛ منطق از کامپوننت بیرون می‌رود و تست با جایگزین کردن یک سرویس ساده می‌شود.",
            whyEn: "DI is Angular's heart; logic moves out of components and testing becomes a matter of swapping a service.",
            items: ["@Injectable({ providedIn: 'root' })", "inject()", "providers array", "Singleton vs per component"],
            tracks: ["17-angular"],
          },
          {
            fa: "injectorهای سلسله‌مراتبی", en: "Hierarchical injectors", kind: "hard",
            whyFa: "وقتی بفهمی وابستگی از کدام سطح پیدا می‌شود، باگ «چرا دو نمونه از این سرویس دارم» حل می‌شود.",
            whyEn: "Once you know which level resolves a dependency, the “why do I have two instances” bug goes away.",
            items: ["Environment injector", "Element injector", "optional / self / skipSelf", "viewProviders"],
          },
          {
            fa: "Injection token", en: "Injection tokens", kind: "hard",
            whyFa: "برای تزریق پیکربندی و قرارداد (نه فقط کلاس) و برای ساختن کتابخانه‌های قابل تنظیم.",
            whyEn: "For injecting configuration and contracts (not just classes) and for building configurable libraries.",
            items: ["InjectionToken", "useValue / useClass / useFactory / useExisting", "Multi providers", "provideAppInitializer"],
          },
        ],
      },
      {
        id: "ng-reactive",
        fa: "Signals و RxJS",
        en: "Signals and RxJS",
        outcomeFa: "حالت را با Signals نگه می‌داری، جریان‌های ناهمگام را با RxJS مدیریت می‌کنی و نشت حافظه نداری.",
        outcomeEn: "You hold state in Signals, handle async streams with RxJS and leak no memory.",
        months: [2, 3],
        skills: [
          {
            fa: "Signals", en: "Signals", kind: "hard",
            whyFa: "مدل واکنشی جدید Angular؛ دقیقاً می‌داند چه چیزی عوض شده و فقط همان را به‌روز می‌کند.",
            whyEn: "Angular's new reactivity model; it knows exactly what changed and updates only that.",
            items: ["signal()", "computed()", "effect()", "linkedSignal()", "resource() / httpResource()", "toSignal / toObservable"],
            tracks: ["17-angular"],
          },
          {
            fa: "مبانی RxJS", en: "RxJS basics", kind: "hard",
            whyFa: "HttpClient، فرم‌ها و router هنوز Observable برمی‌گردانند؛ بدون RxJS نیمی از Angular را نمی‌فهمی.",
            whyEn: "HttpClient, forms and the router still return Observables; without RxJS you only understand half of Angular.",
            items: ["Observable & Observer", "subscribe / unsubscribe", "Subject / BehaviorSubject / ReplaySubject", "Hot vs cold", "async pipe"],
            tracks: ["48-state-management"],
          },
          {
            fa: "عملگرهای RxJS", en: "RxJS operators", kind: "hard",
            whyFa: "انتخاب mergeMap به‌جای switchMap یعنی درخواست تکراری یا پاسخ‌هایی که به ترتیب اشتباه می‌رسند.",
            whyEn: "Picking mergeMap instead of switchMap means duplicate requests or responses arriving in the wrong order.",
            items: ["map / filter / tap", "switchMap", "mergeMap", "concatMap", "exhaustMap", "debounceTime", "combineLatest / forkJoin", "catchError / retry"],
          },
          {
            fa: "پاک‌سازی و نشت حافظه", en: "Teardown and memory leaks", kind: "hard",
            whyFa: "subscription رهاشده رایج‌ترین نشت حافظه در اپ‌های Angular است.",
            whyEn: "Forgotten subscriptions are the most common memory leak in Angular apps.",
            items: ["takeUntilDestroyed", "DestroyRef", "async pipe auto-unsubscribe", "take(1)"],
          },
        ],
      },
      {
        id: "ng-app",
        fa: "مسیریابی، فرم و HTTP",
        en: "Routing, forms and HTTP",
        outcomeFa: "یک اپ چندصفحه‌ای با بارگذاری تنبل، فرم‌های اعتبارسنجی‌شده و فراخوانی API می‌سازی.",
        outcomeEn: "You build a multi-page app with lazy loading, validated forms and API calls.",
        months: [1, 2],
        skills: [
          {
            fa: "Router", en: "The router", kind: "hard",
            whyFa: "بارگذاری تنبل مسیرها بزرگ‌ترین اهرم کوچک کردن بار اول است.",
            whyEn: "Lazy-loading routes is the biggest lever for shrinking the first load.",
            items: ["provideRouter", "Route & query params", "loadComponent / loadChildren", "Guards: canActivate, canMatch", "Resolvers", "withComponentInputBinding"],
            tracks: ["17-angular"],
          },
          {
            fa: "فرم‌های واکنشی", en: "Reactive forms", kind: "hard",
            whyFa: "برای فرم‌های واقعی — پویا، چندمرحله‌ای، با اعتبارسنجی پیچیده — استاندارد است و کاملاً تست‌پذیر.",
            whyEn: "The standard for real forms — dynamic, multi-step, with complex validation — and fully testable.",
            items: ["FormControl / FormGroup / FormArray", "Typed forms", "Built-in validators", "Custom & async validators", "valueChanges"],
          },
          {
            fa: "فرم‌های مبتنی بر قالب", en: "Template-driven forms", kind: "hard", level: "alt",
            whyFa: "برای فرم ساده سریع‌تر است؛ ولی منطق در قالب پخش می‌شود.",
            whyEn: "Quicker for a simple form, but the logic spreads into the template.",
            items: ["ngModel", "FormsModule", "Template validation"],
          },
          {
            fa: "Signal Forms", en: "Signal Forms", kind: "hard", level: "opt",
            whyFa: "نسل بعدی فرم‌های Angular بر پایهٔ Signals؛ وضعیت پایداری‌اش را در مستندات نسخهٔ خودت بررسی کن.",
            whyEn: "The next generation of Angular forms, built on Signals; check its stability status for your version.",
            items: ["form() with signals", "Schema validation", "Stability status"],
          },
          {
            fa: "HttpClient", en: "HttpClient", kind: "hard",
            whyFa: "interceptor جای درست توکن احراز هویت، لاگ و مدیریت خطای سراسری است.",
            whyEn: "Interceptors are the right place for auth tokens, logging and global error handling.",
            items: ["provideHttpClient", "Typed requests", "Functional interceptors", "Error handling", "withFetch"],
          },
        ],
      },
      {
        id: "ng-state",
        fa: "مدیریت حالت",
        en: "State management",
        outcomeFa: "برای اندازهٔ پروژه، سبک مدیریت حالت درست را انتخاب می‌کنی — از یک سرویس ساده تا NgRx.",
        outcomeEn: "You pick the right state approach for the project's size — from a plain service to NgRx.",
        months: [1, 2],
        skills: [
          {
            fa: "سرویس + Signals", en: "Services with signals", kind: "hard",
            whyFa: "برای بیشتر اپ‌ها یک سرویس با چند signal کافی است؛ کتابخانه را وقتی بیاور که دردش را حس کرده‌ای.",
            whyEn: "For most apps one service with a few signals is enough; bring in a library once you have felt the pain.",
            items: ["Signal-based store service", "Read-only signals", "computed selectors"],
            tracks: ["48-state-management"],
          },
          {
            fa: "NgRx Store", en: "NgRx Store", kind: "hard", level: "alt",
            whyFa: "الگوی Redux در Angular؛ در پروژه‌های سازمانی بزرگ رایج است و ردگیری هر تغییر را ممکن می‌کند.",
            whyEn: "The Redux pattern for Angular; common in large enterprise projects and makes every change traceable.",
            items: ["Actions", "Reducers", "Selectors", "Effects", "Entity", "Store DevTools"],
            tracks: ["48-state-management"],
          },
          {
            fa: "NgRx SignalStore", en: "NgRx SignalStore", kind: "hard", level: "alt",
            whyFa: "نسخهٔ سبک و مبتنی بر Signal از NgRx، با کد تکراری بسیار کمتر از Store کلاسیک.",
            whyEn: "The lightweight, Signal-based NgRx, with far less boilerplate than the classic Store.",
            items: ["signalStore()", "withState / withComputed / withMethods", "rxMethod", "withEntities"],
            tracks: ["48-state-management"],
          },
          {
            fa: "NGXS و Elf", en: "NGXS and Elf", kind: "hard", level: "opt",
            whyFa: "در کدهای موجود می‌بینی‌شان؛ Akita دیگر نگه‌داری نمی‌شود.",
            whyEn: "You will meet them in existing code; Akita is no longer maintained.",
            items: ["NGXS", "Elf", "Akita (unmaintained)"],
          },
        ],
      },
      {
        id: "ng-perf",
        fa: "تشخیص تغییر و کارایی",
        en: "Change detection and performance",
        outcomeFa: "می‌دانی Angular کِی صفحه را به‌روز می‌کند و کندی را از ریشه برطرف می‌کنی.",
        outcomeEn: "You know when Angular updates the page and fix slowness at the root.",
        months: [1, 2],
        skills: [
          {
            fa: "تشخیص تغییر", en: "Change detection", kind: "hard",
            whyFa: "بیشتر کندی‌های Angular از تشخیص تغییری است که بی‌دلیل روی کل درخت کامپوننت اجرا می‌شود.",
            whyEn: "Most Angular slowness comes from change detection running needlessly over the whole component tree.",
            items: ["Zone.js", "Default vs OnPush", "markForCheck", "Zoneless change detection"],
          },
          {
            fa: "Deferrable views", en: "Deferrable views", kind: "hard",
            whyFa: "بخش‌های سنگین را تا وقتی لازم نشده‌اند بار نمی‌کند — بدون نوشتن کد بارگذاری تنبل دستی.",
            whyEn: "Heavy parts load only when needed — with no hand-written lazy loading.",
            items: ["@defer (on viewport / idle / interaction)", "@placeholder / @loading", "prefetch"],
          },
          {
            fa: "بودجهٔ حجم و build", en: "Bundle budgets and the builder", kind: "hard",
            whyFa: "بودجهٔ حجم در angular.json جلوی بزرگ شدن بی‌صدای bundle را در CI می‌گیرد.",
            whyEn: "Size budgets in angular.json stop the bundle silently growing — in CI.",
            items: ["esbuild application builder", "Bundle budgets", "source-map-explorer", "Tree shaking"],
          },
          {
            fa: "تصویر و قالب بهینه", en: "Images and lean templates", kind: "hard",
            whyFa: "صدا زدن متد در قالب یعنی اجرای آن در هر دور تشخیص تغییر.",
            whyEn: "Calling a method in a template means running it on every change-detection pass.",
            items: ["NgOptimizedImage", "track in @for", "Pure pipes instead of methods", "CDK virtual scroll"],
            tracks: ["49-rendering-pwa"],
          },
        ],
      },
      {
        id: "ng-ssr",
        fa: "SSR، هیدریشن و PWA",
        en: "SSR, hydration and PWA",
        outcomeFa: "اپ را سمت سرور رندر می‌کنی تا سریع بار شود و موتور جستجو بخواندش.",
        outcomeEn: "You render the app on the server so it loads fast and search engines can read it.",
        months: [1, 2],
        skills: [
          {
            fa: "Angular SSR", en: "Angular SSR", kind: "hard",
            whyFa: "برای SEO و بار اول سریع لازم است؛ از نسخهٔ ۱۷ داخل خود CLI آمده است.",
            whyEn: "Needed for SEO and a fast first load; since v17 it ships inside the CLI itself.",
            items: ["ng add @angular/ssr", "Prerendering (SSG)", "Server routes & render modes", "HTTP transfer cache"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "هیدریشن", en: "Hydration", kind: "hard",
            whyFa: "بدون هیدریشن، اپ بعد از SSR کل DOM را دور می‌ریزد و دوباره می‌سازد — و صفحه چشمک می‌زند.",
            whyEn: "Without hydration the app throws away the server-rendered DOM and rebuilds it — and the page flickers.",
            items: ["Full hydration", "Incremental hydration", "Event replay", "Hydration mismatches"],
          },
          {
            fa: "PWA", en: "PWA", kind: "hard", level: "opt",
            whyFa: "برای اپ‌هایی که باید آفلاین کار کنند یا روی گوشی نصب شوند.",
            whyEn: "For apps that must work offline or be installable on a phone.",
            items: ["@angular/pwa", "Service worker config", "Offline caching", "SwUpdate"],
            tracks: ["49-rendering-pwa"],
          },
        ],
      },
      {
        id: "ng-test",
        fa: "تست",
        en: "Testing",
        outcomeFa: "سرویس، کامپوننت و مسیرهای حیاتی را تست می‌کنی و تست‌ها در CI اجرا می‌شوند.",
        outcomeEn: "You test services, components and critical paths, and the tests run in CI.",
        months: [1, 2],
        skills: [
          {
            fa: "تست واحد", en: "Unit tests", kind: "hard",
            whyFa: "TestBed محیط تزریق وابستگی را برای تست می‌سازد؛ با آن سرویس واقعی را با نسخهٔ جعلی جایگزین می‌کنی.",
            whyEn: "TestBed builds a DI environment for tests; with it you swap real services for fakes.",
            items: ["TestBed", "Component harnesses", "Vitest", "Jasmine / Karma (legacy)", "Jest"],
          },
          {
            fa: "تست HTTP و سرویس", en: "Testing HTTP and services", kind: "hard",
            whyFa: "بیشتر منطق در سرویس‌هاست؛ تستشان ساده‌تر و ارزشمندتر از تست قالب است.",
            whyEn: "Most logic lives in services; testing them is simpler and worth more than testing templates.",
            items: ["provideHttpClientTesting", "HttpTestingController", "Spies", "fakeAsync / tick"],
          },
          {
            fa: "تست سرتاسری", en: "End-to-end tests", kind: "hard",
            whyFa: "چند سناریوی کامل روی مرورگر واقعی، باگ‌هایی را می‌گیرد که تست واحد هرگز نمی‌بیند.",
            whyEn: "A few complete scenarios in a real browser catch bugs unit tests never see.",
            items: ["Playwright", "Cypress", "CI runs"],
            tracks: ["04-devops"],
          },
        ],
      },
      {
        id: "ng-ui",
        fa: "رابط کاربری و اکوسیستم",
        en: "UI and ecosystem",
        outcomeFa: "با کتابخانه‌های رابط کاربری کار می‌کنی و اپ دوزبانهٔ راست‌به‌چپ می‌سازی.",
        outcomeEn: "You work with UI libraries and build a bilingual right-to-left app.",
        months: [1, 2],
        skills: [
          {
            fa: "Angular Material و CDK", en: "Angular Material and the CDK", kind: "hard",
            whyFa: "CDK رفتارهای سخت — پوپ‌آپ، کشیدن و رها کردن، دسترس‌پذیری — را بدون ظاهر خاص می‌دهد؛ روی آن هر طراحی‌ای می‌سازی.",
            whyEn: "The CDK gives you the hard behaviours — overlays, drag-and-drop, accessibility — without a look; you build any design on top.",
            items: ["Material components", "CDK overlay", "CDK drag-drop", "CDK a11y", "Material 3 theming"],
          },
          {
            fa: "کیت‌های رابط کاربری", en: "Third-party UI kits", kind: "hard", level: "alt",
            whyFa: "برای پنل‌های سازمانی پر از جدول و فرم، زمان زیادی صرفه‌جویی می‌کنند.",
            whyEn: "They save a lot of time on enterprise panels full of tables and forms.",
            items: ["PrimeNG", "NG-ZORRO", "Taiga UI", "Spartan"],
          },
          {
            fa: "استایل‌دهی", en: "Styling", kind: "hard", level: "alt",
            whyFa: "Angular استایل را به کامپوننت محدود می‌کند؛ ‎::ng-deep‎ این مرز را می‌شکند و منسوخ شده است.",
            whyEn: "Angular scopes styles to the component; ::ng-deep breaks that boundary and is deprecated.",
            items: ["Component SCSS", "Tailwind CSS", ":host", "Avoiding ::ng-deep"],
            tracks: ["68-sass", "69-tailwind"],
          },
          {
            fa: "چندزبانگی و راست‌به‌چپ", en: "i18n and RTL", kind: "hard", level: "opt",
            whyFa: "اپ فارسی‌وانگلیسی هم ترجمه می‌خواهد و هم جهت راست‌به‌چپ.",
            whyEn: "A Persian–English app needs both translation and right-to-left direction.",
            items: ["@angular/localize", "Transloco", "ngx-translate", "CDK Directionality"],
          },
        ],
      },
      {
        id: "ng-arch",
        fa: "معماری سازمانی",
        en: "Enterprise architecture",
        outcomeFa: "ساختاری طراحی می‌کنی که چند تیم بتوانند بدون شکستن کار هم روی یک اپ بزرگ کار کنند.",
        outcomeEn: "You design a structure where several teams can work on one large app without breaking each other.",
        months: [2, 4],
        skills: [
          {
            fa: "ساختار پروژه", en: "Project structure", kind: "hard",
            whyFa: "Angular برای تیم‌های بزرگ ساخته شده؛ ساختار خوب یعنی هر تیم بخش خودش را بدون شکستن بقیه عوض کند.",
            whyEn: "Angular is built for big teams; good structure lets each team change its part without breaking the rest.",
            items: ["Feature-based folders", "Smart vs presentational components", "core / shared / features", "Path aliases"],
            tracks: ["07-architecture"],
          },
          {
            fa: "Nx monorepo", en: "Nx monorepos", kind: "hard", level: "alt",
            whyFa: "در سازمان‌هایی با چند اپ Angular رایج است و مرز وابستگی بین کتابخانه‌ها را اجباری می‌کند.",
            whyEn: "Common in organisations with several Angular apps; it enforces dependency boundaries between libraries.",
            items: ["Nx workspace", "Libraries & boundaries", "Affected builds", "Generators"],
            tracks: ["36-packaging"],
          },
          {
            fa: "Micro-frontends", en: "Micro-frontends", kind: "hard", level: "opt",
            whyFa: "فقط وقتی تیم‌ها واقعاً مستقل منتشر می‌کنند، ارزش هزینه‌اش را دارد.",
            whyEn: "Only worth the cost when teams truly release independently.",
            items: ["Native Federation", "Module Federation", "Shell & remotes"],
            tracks: ["08-microservices"],
          },
          {
            fa: "ارتقای نسخه", en: "Upgrades", kind: "hard",
            whyFa: "Angular هر شش ماه یک نسخهٔ اصلی می‌دهد؛ تیمی که عقب بماند، دو سال بعد با مهاجرت دردناکی روبه‌روست.",
            whyEn: "Angular ships a major version every six months; a team that falls behind faces a painful migration two years later.",
            items: ["ng update", "Deprecation policy", "Automatic migrations", "Release schedule"],
          },
          {
            fa: "مستندسازی تصمیم‌ها", en: "Documenting decisions", kind: "soft",
            whyFa: "در پروژهٔ بزرگ، «چرا این‌طور ساختیم» زودتر از خود کد فراموش می‌شود.",
            whyEn: "In a large project, “why we built it this way” is forgotten faster than the code itself.",
            items: ["ADRs", "README per library", "Diagrams"],
            tracks: ["64-docs-writing"],
          },
        ],
      },
    ],
  },

  /* ══════════════════════════════ Next.js ══════════════════════════════ */
  {
    id: "nextjs",
    field: "tech",
    accent: "#0070F3",
    ico: '<circle cx="12" cy="12" r="9.2"/><path d="M9.2 16.4V7.8l6.9 9.4M14.8 7.8v5.2" stroke-linecap="round" stroke-linejoin="round"/>',
    after: ["react"],
    next: ["devops", "backend"],
    fa: {
      name: "Next.js",
      role: "Next.js Developer",
      intro:
        "Next.js فریم‌ورکی بر پایهٔ React است که رندر سمت سرور، مسیریابی مبتنی بر فایل، کش و بهینه‌سازی تصویر و فونت را یک‌جا می‌دهد. با App Router و Server Components، مرز سرور و کلاینت داخل یک درخت کامپوننت جابه‌جا می‌شود — و بیشتر سختی یادگیری‌اش همین‌جاست: بدانی هر تکه کجا اجرا می‌شود و چه چیزی کش می‌شود.",
    },
    en: {
      name: "Next.js",
      role: "Next.js Developer",
      intro:
        "Next.js is a React framework that bundles server rendering, file-based routing, caching and image and font optimisation. With the App Router and Server Components, the server–client boundary moves inside one component tree — and that is where most of the learning curve lies: knowing where each piece runs and what gets cached.",
    },
    stages: [
      {
        id: "nx-pre",
        fa: "پیش‌نیاز: React و وب",
        en: "Prerequisites: React and the web",
        outcomeFa: "React را بلدی و می‌دانی یک درخواست HTTP از مرورگر تا سرور و برگشت، از کجاها می‌گذرد.",
        outcomeEn: "You know React and can trace an HTTP request from the browser to the server and back.",
        months: [1, 2],
        skills: [
          {
            fa: "مبانی React", en: "React fundamentals", kind: "hard",
            whyFa: "Next روی React ساخته شده؛ اگر هوک‌ها و ترکیب کامپوننت را بلد نباشی، هر خطای Next شبیه معما می‌شود.",
            whyEn: "Next is built on React; without hooks and composition, every Next error looks like a riddle.",
            items: ["Components & props", "State & effects", "Composition", "Suspense"],
            tracks: ["15-react"],
          },
          {
            fa: "TypeScript", en: "TypeScript", kind: "hard",
            whyFa: "Next پروژهٔ TypeScript را خودش پیکربندی می‌کند و نوع params و metadata را آماده دارد.",
            whyEn: "Next configures TypeScript itself and ships types for params and metadata.",
            items: ["Typing props", "async functions & Promises", "Generics"],
            tracks: ["42-typescript"],
          },
          {
            fa: "HTTP و وب", en: "HTTP and the web", kind: "hard",
            whyFa: "Next یک فریم‌ورک سرور است؛ بدون فهم کش HTTP و کوکی، رفتار کش خود Next را هم نمی‌فهمی.",
            whyEn: "Next is a server framework; without HTTP caching and cookies you will not understand its own caching.",
            items: ["Request / Response", "Headers & cookies", "Status codes", "Cache-Control", "CDN"],
            tracks: ["26-web-foundations"],
          },
          {
            fa: "مبانی Node.js", en: "Node.js basics", kind: "hard",
            whyFa: "کد سرور Next روی Node اجرا می‌شود؛ باید بدانی process.env و ماژول‌های سروری کجا مجازند.",
            whyEn: "Next's server code runs on Node; you need to know where process.env and server-only modules are allowed.",
            items: ["Node runtime", "Environment variables", "npm scripts", "Edge vs Node runtime"],
            tracks: ["29-nodejs"],
          },
        ],
      },
      {
        id: "nx-routing",
        fa: "App Router",
        en: "The App Router",
        outcomeFa: "ساختار مسیرها، layoutها و حالت‌های بارگذاری و خطا را با فایل‌ها می‌سازی.",
        outcomeEn: "You build routes, layouts, and loading and error states out of files.",
        months: [1, 2],
        skills: [
          {
            fa: "مسیریابی مبتنی بر فایل", en: "File-based routing", kind: "hard",
            whyFa: "ساختار پوشه همان ساختار URL است؛ یک نگاه به درخت فایل، کل نقشهٔ سایت را نشان می‌دهد.",
            whyEn: "The folder structure is the URL structure; one glance at the file tree shows the whole site map.",
            items: ["app/ directory", "page.tsx", "Dynamic segments [id]", "Catch-all [...slug]", "Route groups (group)"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "Layout و template", en: "Layouts and templates", kind: "hard",
            whyFa: "layout بین ناوبری‌ها دوباره رندر نمی‌شود؛ هدر و سایدبار حالتشان را نگه می‌دارند.",
            whyEn: "Layouts do not re-render across navigations; headers and sidebars keep their state.",
            items: ["Root layout", "Nested layouts", "template.tsx", "Preserved state"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "فایل‌های ویژه", en: "Special files", kind: "hard",
            whyFa: "حالت بارگذاری و خطا را با یک فایل برای کل یک بخش تعریف می‌کنی، نه در تک‌تک کامپوننت‌ها.",
            whyEn: "You define loading and error states once per segment with a file, not in every component.",
            items: ["loading.tsx", "error.tsx", "not-found.tsx", "global-error.tsx", "default.tsx"],
          },
          {
            fa: "ناوبری", en: "Navigation", kind: "hard",
            whyFa: "Link صفحه‌های بعدی را از قبل می‌گیرد؛ از نسخهٔ ۱۵، params و searchParams در سرور Promise هستند و باید await شوند.",
            whyEn: "Link prefetches the next pages; since v15, params and searchParams on the server are Promises you must await.",
            items: ["<Link>", "Prefetching", "useRouter / redirect()", "usePathname / useSearchParams", "Async params"],
          },
          {
            fa: "مسیریابی پیشرفته", en: "Advanced routing", kind: "hard", level: "opt",
            whyFa: "برای الگوهای پیچیده، مثل مودالی که نشانی خودش را دارد و با رفرش به صفحهٔ کامل تبدیل می‌شود.",
            whyEn: "For complex patterns, such as a modal with its own URL that becomes a full page on refresh.",
            items: ["Parallel routes @slot", "Intercepting routes (.)", "Route-based modals"],
          },
        ],
      },
      {
        id: "nx-rsc",
        fa: "Server و Client Components",
        en: "Server and Client Components",
        outcomeFa: "می‌دانی هر کامپوننت کجا اجرا می‌شود و مرز سرور و کلاینت را آگاهانه جای می‌گذاری.",
        outcomeEn: "You know where each component runs and place the server–client boundary deliberately.",
        months: [1, 2],
        skills: [
          {
            fa: "Server Components", en: "Server Components", kind: "hard",
            whyFa: "پیش‌فرض App Router؛ داده را همان‌جا که لازم است می‌گیری و کد سنگین هرگز به مرورگر نمی‌رسد.",
            whyEn: "The App Router default; you fetch data right where it is needed and heavy code never reaches the browser.",
            items: ["Server by default", "async components", "Direct database access", "Zero client JS", "server-only package"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "Client Components", en: "Client Components", kind: "hard",
            whyFa: "'use client' مرز است، نه برچسب؛ هر چه زیرش import شود هم به مرورگر می‌رود.",
            whyEn: "'use client' is a boundary, not a label; everything imported below it ships to the browser too.",
            items: ["'use client' boundary", "Hooks & event handlers", "Browser APIs", "Keep the boundary low"],
          },
          {
            fa: "الگوهای ترکیب", en: "Composition patterns", kind: "hard",
            whyFa: "رایج‌ترین خطای Next: پاس دادن تابع یا کلاس از سرور به کلاینت. قاعده‌اش را که بفهمی، تمام می‌شود.",
            whyEn: "Next's most common error: passing a function or class from server to client. Understand the rule and it is gone.",
            items: ["Server components as children", "Serialisable props", "Providers in client wrappers", "Third-party components"],
          },
          {
            fa: "Streaming و Suspense", en: "Streaming and Suspense", kind: "hard",
            whyFa: "صفحه تکه‌تکه می‌رسد: بخش سریع فوراً دیده می‌شود و بخش کند بعداً جا می‌افتد.",
            whyEn: "The page arrives in pieces: the fast part shows immediately, the slow part slots in later.",
            items: ["<Suspense> boundaries", "Streaming HTML", "Waterfalls vs parallel fetches"],
          },
        ],
      },
      {
        id: "nx-data",
        fa: "داده، کش و بازاعتبارسنجی",
        en: "Data, caching and revalidation",
        outcomeFa: "داده را می‌خوانی و تغییر می‌دهی، و دقیقاً می‌دانی چه چیزی کش شده و کِی تازه می‌شود.",
        outcomeEn: "You read and change data and know exactly what is cached and when it refreshes.",
        months: [2, 3],
        skills: [
          {
            fa: "دریافت داده", en: "Data fetching", kind: "hard",
            whyFa: "در Server Component مستقیماً await می‌کنی؛ دیگر useEffect و API واسط برای خواندن داده لازم نیست.",
            whyEn: "In a Server Component you just await; no useEffect or intermediate API is needed to read data.",
            items: ["fetch in Server Components", "Promise.all for parallel fetches", "Request memoisation", "Database calls on the server"],
            tracks: ["16-nextjs"],
          },
          {
            fa: "راهبردهای رندر", en: "Rendering strategies", kind: "hard",
            whyFa: "هر مسیر بسته به داده‌اش ایستا یا پویا ساخته می‌شود؛ باید بدانی چه چیزی آن را پویا می‌کند: cookies، headers یا searchParams.",
            whyEn: "Each route is built static or dynamic depending on its data; you need to know what makes it dynamic: cookies, headers or searchParams.",
            items: ["Static (SSG)", "Dynamic (SSR)", "ISR & revalidate", "generateStaticParams", "Partial Prerendering"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "Cache Components", en: "Cache Components", kind: "hard",
            whyFa: "مدل کش Next در نسخه‌های اخیر صریح شده: فقط چیزی کش می‌شود که خودت با 'use cache' علامت بزنی. مهم‌ترین تغییر نسخهٔ ۱۶ همین است.",
            whyEn: "Next's caching model became explicit in recent versions: only what you mark with 'use cache' is cached. This is the headline change of v16.",
            items: ["cacheComponents config", "'use cache'", "cacheLife", "cacheTag", "revalidateTag / updateTag", "revalidatePath"],
          },
          {
            fa: "Server Actions و فرم", en: "Server Actions and forms", kind: "hard",
            whyFa: "تغییر داده بدون نوشتن API جدا؛ ولی هر Server Action یک endpoint عمومی است و باید مثل API ایمنش کنی.",
            whyEn: "Mutations without a separate API; but every Server Action is a public endpoint and must be secured like one.",
            items: ["'use server'", "<form action>", "useActionState", "useOptimistic", "Zod validation", "Auth check in every action"],
          },
          {
            fa: "Route handler", en: "Route handlers", kind: "hard",
            whyFa: "برای API عمومی، webhook و هر کلاینتی غیر از خود React.",
            whyEn: "For public APIs, webhooks and any client other than React itself.",
            items: ["route.ts", "GET / POST", "NextRequest / NextResponse", "Webhooks", "Streaming responses"],
          },
        ],
      },
      {
        id: "nx-edge",
        fa: "Proxy، احراز هویت و امنیت",
        en: "Proxy, authentication and security",
        outcomeFa: "ورود کاربر را پیاده می‌کنی و می‌دانی کجا بررسی دسترسی کافی نیست.",
        outcomeEn: "You implement sign-in and know where an access check is not enough.",
        months: [1, 2],
        skills: [
          {
            fa: "proxy.ts", en: "proxy.ts", kind: "hard",
            whyFa: "در نسخهٔ ۱۶ middleware به proxy تغییر نام داد تا روشن باشد مرز شبکه است؛ برای ریدایرکت، تشخیص زبان و بررسی سبک ورود.",
            whyEn: "In v16 middleware was renamed proxy to make clear it is the network boundary; use it for redirects, locale detection and lightweight auth checks.",
            items: ["proxy.ts (formerly middleware.ts)", "matcher", "Redirects & rewrites", "Headers & cookies"],
          },
          {
            fa: "احراز هویت", en: "Authentication", kind: "hard",
            whyFa: "بررسی ورود فقط در proxy کافی نیست؛ باید کنار داده هم تکرار شود، وگرنه یک Server Action دورش می‌زند.",
            whyEn: "Checking auth only in the proxy is not enough; repeat it next to the data, or a Server Action can bypass it.",
            items: ["Auth.js", "Better Auth", "httpOnly session cookies", "JWT vs database sessions", "Data access layer checks"],
          },
          {
            fa: "امنیت", en: "Security", kind: "hard",
            whyFa: "هر متغیری که با NEXT_PUBLIC_ شروع شود به bundle مرورگر می‌رود؛ کلید API را این‌طور لو نده.",
            whyEn: "Any variable starting with NEXT_PUBLIC_ lands in the browser bundle; do not leak an API key that way.",
            items: ["NEXT_PUBLIC_ variables", "server-only", "Content-Security-Policy", "DTOs for client data", "Rate limiting"],
          },
        ],
      },
      {
        id: "nx-ui",
        fa: "بهینه‌سازی و SEO",
        en: "Optimisation and SEO",
        outcomeFa: "هر صفحه عنوان، توضیح و تصویر اشتراک خودش را دارد و Core Web Vitals سبز است.",
        outcomeEn: "Every page has its own title, description and share image, and Core Web Vitals are green.",
        months: [1, 1],
        skills: [
          {
            fa: "Metadata API", en: "The Metadata API", kind: "hard",
            whyFa: "SEO یکی از دلایل اصلی انتخاب Next است؛ عنوان، توضیح و تصویر اشتراک هر صفحه را از داده‌اش می‌سازی.",
            whyEn: "SEO is a main reason to choose Next; you generate each page's title, description and share image from its data.",
            items: ["metadata export", "generateMetadata", "Open Graph", "opengraph-image.tsx", "sitemap.ts & robots.ts", "JSON-LD"],
          },
          {
            fa: "تصویر، فونت و اسکریپت", en: "Images, fonts and scripts", kind: "hard",
            whyFa: "این سه، بزرگ‌ترین علت LCP بد و جابه‌جایی صفحه‌اند و Next برای هر سه ابزار آماده دارد.",
            whyEn: "These three are the biggest causes of poor LCP and layout shift, and Next has a ready tool for each.",
            items: ["next/image", "sizes & priority", "next/font", "next/script strategies"],
            tracks: ["49-rendering-pwa"],
          },
          {
            fa: "استایل‌دهی", en: "Styling", kind: "hard", level: "alt",
            whyFa: "همهٔ روش‌ها کار می‌کنند، به‌جز CSS-in-JS زمان اجرا که با Server Components جور نیست.",
            whyEn: "Every approach works except runtime CSS-in-JS, which does not fit Server Components.",
            items: ["CSS Modules", "Sass", "Tailwind CSS", "Global styles"],
            tracks: ["67-css", "68-sass", "69-tailwind"],
          },
          {
            fa: "چندزبانگی", en: "Internationalisation", kind: "hard", level: "opt",
            whyFa: "برای سایت دوزبانه؛ Next مسیر را می‌دهد و ترجمه با یک کتابخانه است.",
            whyEn: "For bilingual sites; Next provides the routing and a library does the translation.",
            items: ["[locale] segment", "next-intl", "Locale detection in proxy", "dir=\"rtl\""],
          },
        ],
      },
      {
        id: "nx-db",
        fa: "پایگاه‌داده و کار پس‌زمینه",
        en: "Database and background work",
        outcomeFa: "اپ را به پایگاه‌داده وصل می‌کنی، مهاجرت می‌نویسی و کار طولانی را از مسیر پاسخ بیرون می‌بری.",
        outcomeEn: "You connect the app to a database, write migrations and move long work out of the request path.",
        months: [1, 2],
        skills: [
          {
            fa: "مبانی SQL", en: "SQL fundamentals", kind: "hard",
            whyFa: "ORM جای فهم SQL را نمی‌گیرد؛ کندترین صفحه‌ها معمولاً یک کوئری N+1 پنهان دارند.",
            whyEn: "An ORM does not replace understanding SQL; the slowest pages usually hide an N+1 query.",
            items: ["Relational modelling", "Indexes", "Transactions", "N+1 queries"],
            tracks: ["05-sql"],
          },
          {
            fa: "Prisma", en: "Prisma", kind: "hard", level: "alt",
            whyFa: "پرکاربردترین ORM این اکوسیستم، با طرح‌وارهٔ خوانا و مهاجرت خودکار.",
            whyEn: "The ecosystem's most used ORM, with a readable schema and automatic migrations.",
            items: ["schema.prisma", "Migrations", "Prisma Client", "Connection pooling"],
          },
          {
            fa: "Drizzle", en: "Drizzle", kind: "hard", level: "alt",
            whyFa: "نزدیک به SQL و سبک؛ برای کسی که SQL بلد است طبیعی‌تر است.",
            whyEn: "Close to SQL and lightweight; more natural if you already know SQL.",
            items: ["SQL-like TypeScript", "drizzle-kit", "Edge-friendly drivers"],
          },
          {
            fa: "کار پس‌زمینه", en: "Background work", kind: "hard", level: "opt",
            whyFa: "کار طولانی نباید پاسخ کاربر را معطل کند؛ بعد از پاسخ یا در صف انجامش بده.",
            whyEn: "Long work should not hold the user's response; run it after the response or on a queue.",
            items: ["after()", "Job queues", "Cron jobs", "Idempotent webhooks"],
          },
        ],
      },
      {
        id: "nx-test",
        fa: "تست و کیفیت",
        en: "Testing and quality",
        outcomeFa: "منطق را جدا تست می‌کنی و رفتار واقعی را روی build تولیدی می‌سنجی.",
        outcomeEn: "You test logic in isolation and verify real behaviour against a production build.",
        months: [1, 1],
        skills: [
          {
            fa: "تست واحد و کامپوننت", en: "Unit and component tests", kind: "hard",
            whyFa: "Server Componentهای async را هنوز همهٔ ابزارها پشتیبانی نمی‌کنند؛ منطق را در تابع جدا بگذار و آن را تست کن.",
            whyEn: "Not every tool supports async Server Components yet; keep logic in plain functions and test those.",
            items: ["Vitest", "React Testing Library", "MSW", "Testing pure functions"],
          },
          {
            fa: "تست سرتاسری", en: "End-to-end tests", kind: "hard",
            whyFa: "رفتار واقعی Next — کش، ریدایرکت، استریم — فقط در build تولیدی دیده می‌شود.",
            whyEn: "Next's real behaviour — caching, redirects, streaming — only shows up in a production build.",
            items: ["Playwright", "next build && next start", "Visual checks"],
            tracks: ["04-devops"],
          },
          {
            fa: "Lint و نوع", en: "Linting and types", kind: "hard",
            whyFa: "مسیرهای تایپ‌دار، لینک شکسته را قبل از انتشار می‌گیرند.",
            whyEn: "Typed routes catch broken links before release.",
            items: ["ESLint", "TypeScript strict", "typedRoutes", "Bundle analyzer"],
          },
        ],
      },
      {
        id: "nx-deploy",
        fa: "استقرار و عملیات",
        en: "Deployment and operations",
        outcomeFa: "اپ را روی سرور خودت یا یک پلتفرم منتشر می‌کنی و می‌بینی در تولید چه می‌گذرد.",
        outcomeEn: "You ship the app to your own server or a platform and can see what happens in production.",
        months: [1, 2],
        skills: [
          {
            fa: "میزبانی روی سرور خودت", en: "Self-hosting", kind: "hard", level: "alt",
            whyFa: "جایی که پلتفرم‌های میزبانی در دسترس نیستند، گزینهٔ اصلی است؛ خروجی standalone یک پوشهٔ کوچک می‌سازد که با یک دستور node اجرا می‌شود.",
            whyEn: "The main option where hosted platforms are unavailable; standalone output produces a small folder that runs with one node command.",
            items: ["output: 'standalone'", "Docker image", "Nginx reverse proxy", "systemd / PM2", "Shared cache handler"],
            tracks: ["01-docker", "02-nginx"],
          },
          {
            fa: "Vercel", en: "Vercel", kind: "hard", level: "alt",
            whyFa: "ساده‌ترین مسیر؛ ولی هزینه در ترافیک بالا و دسترسی در منطقهٔ خودت را بسنج.",
            whyEn: "The simplest path; but weigh cost at high traffic and availability in your region.",
            items: ["Git integration", "Preview deployments", "Edge network", "Usage limits"],
          },
          {
            fa: "خروجی ایستا", en: "Static export", kind: "hard", level: "opt",
            whyFa: "برای سایت کاملاً ایستا بدون سرور؛ ولی Server Action و ISR را از دست می‌دهی.",
            whyEn: "For a fully static site with no server — at the cost of Server Actions and ISR.",
            items: ["output: 'export'", "No server features", "Any CDN"],
          },
          {
            fa: "مشاهده‌پذیری", en: "Observability", kind: "hard",
            whyFa: "بدون لاگ و ردیابی نمی‌فهمی کدام کوئری صفحه را کند کرده است.",
            whyEn: "Without logs and tracing you cannot tell which query slowed a page down.",
            items: ["instrumentation.ts", "OpenTelemetry", "Error tracking", "Web Vitals reporting"],
          },
          {
            fa: "CI/CD", en: "CI/CD", kind: "hard",
            whyFa: "هر ادغام در شاخهٔ اصلی باید خودکار build، تست و منتشر شود.",
            whyEn: "Every merge to main should build, test and ship automatically.",
            items: ["GitHub Actions / GitLab CI", "Build cache", "Environment per branch", "Zero-downtime deploys"],
            tracks: ["04-devops"],
          },
        ],
      },
      {
        id: "nx-senior",
        fa: "نگاه ارشد",
        en: "The senior view",
        outcomeFa: "می‌دانی کِی Next انتخاب درستی است، معماری‌اش را برای تیم می‌چینی و با تغییرات سریعش همراه می‌مانی.",
        outcomeEn: "You know when Next is the right choice, lay out its architecture for a team and keep up with its fast pace.",
        months: [1, 3],
        skills: [
          {
            fa: "معماری در مقیاس", en: "Architecture at scale", kind: "hard",
            whyFa: "لایهٔ دسترسی به داده و مرز سرور/کلاینت را یک بار درست طراحی کن، وگرنه بررسی دسترسی و کش در کل کد پخش می‌شود.",
            whyEn: "Design the data-access layer and the server/client boundary once, or access checks and caching spread through the whole codebase.",
            items: ["Feature folders in app/", "Data access layer", "Boundary design", "Multi-zones"],
            tracks: ["07-architecture"],
          },
          {
            fa: "انتخاب ابزار با دلیل", en: "Choosing tools with reasons", kind: "soft",
            whyFa: "Next برای هر پروژه‌ای لازم نیست؛ یک SPA پشت صفحهٔ ورود یا یک صفحهٔ فرود ساده، ابزار سبک‌تری می‌خواهد. دفاع از انتخاب، مهارت ارشد است.",
            whyEn: "Not every project needs Next; a SPA behind a login or a simple landing page wants something lighter. Defending the choice is a senior skill.",
            items: ["Trade-off tables", "ADRs"],
            tracks: ["64-docs-writing"],
          },
          {
            fa: "همراه ماندن با تغییرات", en: "Keeping up with changes", kind: "soft",
            whyFa: "Next سریع عوض می‌شود و خیلی از آموزش‌ها منسوخ‌اند؛ یادداشت انتشار و راهنمای ارتقا را بخوان.",
            whyEn: "Next changes fast and many tutorials are out of date; read the release notes and upgrade guides.",
            items: ["Release notes", "@next/codemod", "Upgrade guides"],
          },
        ],
      },
    ],
  },
];
