/* ============================================================================
   رودمپ تکنولوژی‌های .NET: C# و ASP.NET Core

   جاهایی که ویژگی به نسخهٔ خاصی بسته است (C# 12، C# 14، .NET 9 و …)
   در خود موضوع آمده، چون در کد موجود شرکت‌ها نسخه‌های قدیمی‌تر زیاد است.
   ========================================================================== */
import type { Roadmap } from "./types";

export const TECH_DOTNET_ROADMAPS: Roadmap[] = [
  /* ════════════════════════════════ C# ════════════════════════════════ */
  {
    id: "csharp",
    field: "tech",
    accent: "#512BD4",
    ico: '<path d="M12 2.6 20.2 7.3v9.4L12 21.4 3.8 16.7V7.3z" stroke-linejoin="round"/><path d="M12.6 9.3a3.3 3.3 0 1 0 0 5.4" stroke-linecap="round"/><path d="M14.8 10.8h3.4M14.8 13.2h3.4M15.9 9.6v4.8M17.1 9.6v4.8" stroke-linecap="round"/>',
    after: ["foundations"],
    next: ["aspnet-core", "backend"],
    fa: {
      name: "C#",
      role: "C# / .NET Developer",
      intro:
        "C# زبانی چندمنظوره، ایمن از نظر نوع و بسیار سریع است که روی .NET اجرا می‌شود — از وب و بازی (Unity) تا دسکتاپ، موبایل و ابر. چیزی که C# را خاص می‌کند ترکیبی نادر است: نحو ساده برای شروع، و ابزارهای سطح پایین مثل Span و کنترل حافظه برای وقتی که کارایی حرف اول را می‌زند. این رودمپ از پایه تا درونیات زبان و ران‌تایم می‌رود.",
    },
    en: {
      name: "C#",
      role: "C# / .NET Developer",
      intro:
        "C# is a general-purpose, type-safe and very fast language that runs on .NET — from web and games (Unity) to desktop, mobile and the cloud. What makes it special is a rare combination: simple syntax to start with, and low-level tools like Span and memory control for when performance is everything. This roadmap goes from the basics to the internals of the language and runtime.",
    },
    stages: [
      {
        id: "cs-start",
        fa: "شروع: .NET و ابزار",
        en: "Getting started: .NET and tooling",
        outcomeFa: "پروژه می‌سازی، اجرا و دیباگ می‌کنی و می‌دانی کد C# چطور به کد ماشین می‌رسد.",
        outcomeEn: "You create, run and debug projects and know how C# code becomes machine code.",
        months: [1, 1],
        skills: [
          {
            fa: "SDK و dotnet CLI", en: ".NET SDK and the dotnet CLI", kind: "hard",
            whyFa: "dotnet CLI روی ویندوز، لینوکس و مک یکسان است و هر IDE هم زیر کاپوت همین را صدا می‌زند.",
            whyEn: "The dotnet CLI is the same on Windows, Linux and macOS, and every IDE calls it under the hood.",
            items: ["dotnet new / build / run / test", "SDK vs runtime", ".csproj", "LTS vs STS releases", "global.json"],
            tracks: ["09-csharp"],
          },
          {
            fa: "IDE و دیباگر", en: "IDE and debugger", kind: "hard", level: "alt",
            whyFa: "دیباگر خوب نیمی از یادگیری است؛ breakpoint و watch را از روز اول به کار ببر.",
            whyEn: "A good debugger is half of learning; use breakpoints and watches from day one.",
            items: ["Visual Studio", "JetBrains Rider", "VS Code + C# Dev Kit", "Breakpoints, watch, call stack"],
          },
          {
            fa: "‏.NET کد را چطور اجرا می‌کند", en: "How .NET runs code", kind: "hard",
            whyFa: "فهم IL، JIT و GC توضیح می‌دهد چرا برنامه کند شروع می‌شود و بعد سریع می‌شود.",
            whyEn: "Understanding IL, the JIT and the GC explains why a program starts slow and then speeds up.",
            items: ["C# → IL", "CLR", "JIT & tiered compilation", "Native AOT", "Garbage collector"],
          },
          {
            fa: "Git", en: "Git", kind: "hard",
            whyFa: "هر پروژهٔ .NET واقعی روی Git است؛ ‎.gitignore‎ درست جلوی رفتن پوشه‌های bin و obj به مخزن را می‌گیرد.",
            whyEn: "Every real .NET project lives in Git; a correct .gitignore keeps bin and obj out of the repository.",
            items: ["commit / branch", ".gitignore for .NET", "Pull requests"],
            tracks: ["28-git"],
          },
        ],
      },
      {
        id: "cs-basics",
        fa: "مبانی زبان",
        en: "Language basics",
        outcomeFa: "برنامهٔ خط فرمان کامل با ورودی، شرط، حلقه و مدیریت خطا می‌نویسی.",
        outcomeEn: "You write complete console programs with input, conditions, loops and error handling.",
        months: [1, 2],
        skills: [
          {
            fa: "نوع‌ها و متغیرها", en: "Types and variables", kind: "hard",
            whyFa: "تمایز نوع مقداری و ارجاعی ریشهٔ نیمی از رفتارهای «عجیب» C# است: کپی شدن struct یا تغییر یک شیء از دو جا.",
            whyEn: "The value/reference split is behind half of C#'s “strange” behaviour: a struct being copied, or one object changed from two places.",
            items: ["int, double, decimal, bool, char, string", "var", "Value vs reference types", "Nullable value types (int?)", "const & readonly"],
            tracks: ["09-csharp"],
          },
          {
            fa: "کنترل جریان", en: "Control flow", kind: "hard",
            whyFa: "پایه‌ای‌ترین بخش؛ ولی switch expression نسخهٔ امروزی و خواناتر آن است.",
            whyEn: "The most basic part — though the switch expression is its modern, more readable form.",
            items: ["if / switch", "Switch expressions", "for / foreach / while", "break / continue", "?: and ??"],
          },
          {
            fa: "متدها", en: "Methods", kind: "hard",
            whyFa: "ref و out را باید بشناسی، چون APIهای .NET مثل TryParse همه‌جا از آن‌ها استفاده می‌کنند.",
            whyEn: "You need ref and out, because .NET APIs such as TryParse use them everywhere.",
            items: ["ref, out, in", "Optional & named arguments", "params", "Overloading", "Expression-bodied members", "Local functions"],
          },
          {
            fa: "رشته‌ها", en: "Strings", kind: "hard",
            whyFa: "string تغییرناپذیر است؛ الحاق در حلقه یعنی هزاران شیء دورریختنی. برای ساختن رشتهٔ بلند StringBuilder هست.",
            whyEn: "Strings are immutable; concatenating in a loop means thousands of throwaway objects. StringBuilder exists for building long strings.",
            items: ["String interpolation", "Raw string literals", "StringBuilder", "Comparison & culture", "Formatting numbers & dates"],
          },
          {
            fa: "مدیریت خطا", en: "Exceptions", kind: "hard",
            whyFa: "‏throw ex ردپای خطا را پاک می‌کند و throw تنها نگهش می‌دارد؛ همین یک کلمه ساعت‌ها دیباگ را صرفه‌جویی می‌کند.",
            whyEn: "throw ex wipes the stack trace while a bare throw keeps it; that one word saves hours of debugging.",
            items: ["try / catch / finally", "throw vs throw ex", "Custom exceptions", "Exception filters (when)", "using & IDisposable"],
          },
        ],
      },
      {
        id: "cs-oop",
        fa: "شیءگرایی و طراحی نوع",
        en: "OOP and type design",
        outcomeFa: "برای یک مسئلهٔ واقعی نوع‌های درست طراحی می‌کنی: کلاس، رکورد، رابط — و می‌دانی کدام کِی.",
        outcomeEn: "You design the right types for a real problem — classes, records, interfaces — and know which to use when.",
        months: [1, 2],
        skills: [
          {
            fa: "کلاس و شیء", en: "Classes and objects", kind: "hard",
            whyFa: "واحد اصلی سازمان‌دهی کد در C#؛ سازندهٔ اولیه (C# 12) کد تکراری سازنده‌ها را حذف کرده است.",
            whyEn: "C#'s main unit of code organisation; primary constructors (C# 12) removed a lot of constructor boilerplate.",
            items: ["Fields, properties, methods", "Constructors", "Primary constructors", "Static members", "Object initialisers"],
            tracks: ["47-oop"],
          },
          {
            fa: "ارث‌بری و چندریختی", en: "Inheritance and polymorphism", kind: "hard",
            whyFa: "ارث‌بری ابزاری قوی ولی خطرناک است؛ بیشتر وقت‌ها ترکیب اشیا انتخاب بهتری است.",
            whyEn: "Inheritance is powerful but dangerous; most of the time composition is the better choice.",
            items: ["virtual / override", "abstract classes", "sealed", "base", "Composition over inheritance"],
            tracks: ["47-oop"],
          },
          {
            fa: "رابط‌ها", en: "Interfaces", kind: "hard",
            whyFa: "رابط پایهٔ تزریق وابستگی و تست‌پذیری در کل اکوسیستم .NET است.",
            whyEn: "Interfaces are the foundation of dependency injection and testability across .NET.",
            items: ["Contracts", "Explicit implementation", "Default interface methods", "Static abstract members"],
          },
          {
            fa: "record، struct و enum", en: "Records, structs and enums", kind: "hard",
            whyFa: "record برای داده‌ای ساخته شده که فقط حمل می‌شود — DTO، رویداد — و برابری مقداری را مجانی می‌دهد.",
            whyEn: "Records are made for data that is just carried around — DTOs, events — and give you value equality for free.",
            items: ["record / record struct", "with expressions", "Value equality", "readonly struct", "Enums & [Flags]"],
          },
          {
            fa: "کپسوله‌سازی و دسترسی", en: "Encapsulation and access", kind: "hard",
            whyFa: "هر چه public باشد، قرارداد است و تغییرش کسی را می‌شکند؛ پیش‌فرض را خصوصی بگذار.",
            whyEn: "Everything public is a contract, and changing it breaks someone; make private the default.",
            items: ["public / private / protected / internal", "init accessors", "required members", "file-scoped types"],
          },
          {
            fa: "SOLID", en: "SOLID", kind: "hard",
            whyFa: "زبان مشترک بازبینی کد در تیم‌های .NET؛ قانون نیست، ابزار فکر کردن است.",
            whyEn: "The shared vocabulary of code review on .NET teams; not laws, but tools for thinking.",
            items: ["Single responsibility", "Open/closed", "Liskov substitution", "Interface segregation", "Dependency inversion"],
            tracks: ["47-oop", "07-architecture"],
          },
        ],
      },
      {
        id: "cs-collections",
        fa: "Generics، مجموعه‌ها و LINQ",
        en: "Generics, collections and LINQ",
        outcomeFa: "دادهٔ واقعی را با مجموعهٔ درست نگه می‌داری و با LINQ پرس‌وجو می‌کنی — بی‌آنکه ناخواسته دو بار اجرا شود.",
        outcomeEn: "You hold real data in the right collection and query it with LINQ — without accidentally running it twice.",
        months: [1, 2],
        skills: [
          {
            fa: "Generics", en: "Generics", kind: "hard",
            whyFa: "بدون generic، هر مجموعه‌ای یا object برمی‌گرداند یا باید برای هر نوع دوباره نوشته شود.",
            whyEn: "Without generics, every collection either returns object or must be rewritten for each type.",
            items: ["Generic types & methods", "Constraints (where T : …)", "Covariance & contravariance", "Generic math"],
          },
          {
            fa: "مجموعه‌ها", en: "Collections", kind: "hard",
            whyFa: "مجموعهٔ درست یعنی O(1) به‌جای O(n)؛ یک Dictionary در جای درست، یک حلقهٔ کند را حذف می‌کند.",
            whyEn: "The right collection means O(1) instead of O(n); a Dictionary in the right place removes a slow loop.",
            items: ["List<T>", "Dictionary<TKey, TValue>", "HashSet<T>", "Queue / Stack", "Immutable & frozen collections", "Collection expressions"],
            tracks: ["58-algorithms"],
          },
          {
            fa: "delegate، lambda و رویداد", en: "Delegates, lambdas and events", kind: "hard",
            whyFa: "LINQ، async و رویدادهای رابط کاربری همه روی delegate ساخته شده‌اند.",
            whyEn: "LINQ, async and UI events are all built on delegates.",
            items: ["Func / Action / Predicate", "Lambdas & closures", "Events & EventHandler", "Captured variable pitfalls"],
          },
          {
            fa: "LINQ", en: "LINQ", kind: "hard",
            whyFa: "قوی‌ترین ابزار روزمرهٔ C#؛ ولی اجرای تأخیری یعنی یک کوئری ممکن است چند بار اجرا شود.",
            whyEn: "C#'s most powerful everyday tool; but deferred execution means a query may run several times.",
            items: ["Where / Select / OrderBy", "GroupBy / Join", "First vs Single", "Deferred execution", "IEnumerable vs IQueryable", "Aggregate"],
            tracks: ["09-csharp"],
          },
          {
            fa: "Iterator", en: "Iterators", kind: "hard",
            whyFa: "دنبالهٔ تنبل می‌سازی بدون اینکه کل فهرست را در حافظه بسازی.",
            whyEn: "You produce lazy sequences without building the whole list in memory.",
            items: ["yield return", "IEnumerable<T>", "IAsyncEnumerable<T>"],
          },
        ],
      },
      {
        id: "cs-async",
        fa: "ناهمگامی و همروندی",
        en: "Async and concurrency",
        outcomeFa: "کد ناهمگام بدون قفل‌شدگی می‌نویسی، کار را لغوپذیر می‌کنی و داده را بین نخ‌ها امن نگه می‌داری.",
        outcomeEn: "You write async code without deadlocks, make work cancellable and keep data safe across threads.",
        months: [2, 3],
        skills: [
          {
            fa: "async و await", en: "async and await", kind: "hard",
            whyFa: "مهم‌ترین مهارت C# سمت سرور. یک ‎.Result‎ در جای اشتباه کل برنامه را قفل می‌کند.",
            whyEn: "The most important server-side C# skill. One .Result in the wrong place deadlocks the whole program.",
            items: ["Task & Task<T>", "ValueTask", "Async all the way", "Avoid async void", "ConfigureAwait", "Task.WhenAll / WhenAny"],
            tracks: ["09-csharp"],
          },
          {
            fa: "لغو و مهلت", en: "Cancellation and timeouts", kind: "hard",
            whyFa: "درخواستی که کاربر رهایش کرده، نباید تا آخر پایگاه‌داده را مشغول نگه دارد.",
            whyEn: "A request the user abandoned should not keep the database busy to the end.",
            items: ["CancellationToken", "CancellationTokenSource", "Timeouts", "Linked tokens"],
          },
          {
            fa: "نخ‌ها و همگام‌سازی", en: "Threads and synchronisation", kind: "hard",
            whyFa: "شرایط رقابتی فقط زیر بار واقعی ظاهر می‌شود؛ باید قبل از تولید بشناسی‌اش.",
            whyEn: "Race conditions only appear under real load; you must recognise them before production.",
            items: ["ThreadPool", "lock / Lock (C# 13)", "Interlocked", "SemaphoreSlim", "Concurrent collections", "Race conditions"],
          },
          {
            fa: "Channels و Parallel", en: "Channels and Parallel", kind: "hard",
            whyFa: "الگوی تولیدکننده و مصرف‌کننده بدون قفل دستی؛ پایهٔ صف‌های داخلی سرویس‌ها.",
            whyEn: "Producer/consumer without manual locks; the basis of in-process queues in services.",
            items: ["System.Threading.Channels", "Parallel.ForEachAsync", "PLINQ", "Producer/consumer"],
          },
        ],
      },
      {
        id: "cs-modern",
        fa: "C# مدرن",
        en: "Modern C#",
        outcomeFa: "کد C# امروزی را می‌خوانی و می‌نویسی و NullReferenceException را پیش از اجرا می‌گیری.",
        outcomeEn: "You read and write today's C# and catch NullReferenceException before it runs.",
        months: [1, 2],
        skills: [
          {
            fa: "تطبیق الگو", en: "Pattern matching", kind: "hard",
            whyFa: "شاخه‌های if تودرتو را به یک عبارت خوانا تبدیل می‌کند.",
            whyEn: "Turns nested ifs into one readable expression.",
            items: ["is patterns", "Property patterns", "Relational & logical patterns", "List patterns", "Switch expressions"],
          },
          {
            fa: "نوع‌های ارجاعی nullable", en: "Nullable reference types", kind: "hard",
            whyFa: "رایج‌ترین خطای تاریخ .NET، یعنی NullReferenceException، را به هشدار زمان کامپایل تبدیل می‌کند.",
            whyEn: "Turns .NET's most common error, NullReferenceException, into a compile-time warning.",
            items: ["<Nullable>enable</Nullable>", "? and !", "Null-state analysis", "[NotNullWhen]", "Null-conditional assignment (C# 14)"],
          },
          {
            fa: "نحو جدید", en: "New syntax", kind: "hard",
            whyFa: "C# امروزی کوتاه‌تر و روشن‌تر از ده سال پیش است؛ نسخه‌های جدید را باید بخوانی و بنویسی.",
            whyEn: "Today's C# is shorter and clearer than ten years ago; you should read and write the newer forms.",
            items: ["Primary constructors", "Collection expressions", "Raw string literals", "required & init", "Extension members (C# 14)", "field keyword (C# 14)"],
          },
          {
            fa: "Reflection و attribute", en: "Reflection and attributes", kind: "hard", level: "opt",
            whyFa: "پایهٔ ORMها، سریال‌سازها و فریم‌ورک‌های تست؛ ولی کند است و با AOT سازگاری محدودی دارد.",
            whyEn: "The basis of ORMs, serialisers and test frameworks; but it is slow and has limited AOT compatibility.",
            items: ["Type & reflection", "Custom attributes", "Expression trees"],
          },
          {
            fa: "Source generator", en: "Source generators", kind: "hard", level: "opt",
            whyFa: "کاری که reflection در زمان اجرا می‌کرد، در زمان کامپایل انجام می‌شود — سریع‌تر و سازگار با AOT.",
            whyEn: "What reflection did at run time happens at compile time — faster and AOT-friendly.",
            items: ["Incremental generators", "Roslyn", "System.Text.Json source gen", "Regex source gen"],
          },
        ],
      },
      {
        id: "cs-memory",
        fa: "حافظه و کارایی",
        en: "Memory and performance",
        outcomeFa: "کندی را با اندازه‌گیری پیدا می‌کنی و تخصیص حافظهٔ اضافه را از مسیرهای داغ حذف می‌کنی.",
        outcomeEn: "You find slowness by measuring and remove extra allocations from hot paths.",
        months: [1, 3],
        skills: [
          {
            fa: "زباله‌روب (GC)", en: "The garbage collector", kind: "hard",
            whyFa: "بیشتر مشکل‌های کارایی .NET از تخصیص زیاد حافظه است، نه از محاسبهٔ کند.",
            whyEn: "Most .NET performance problems come from allocating too much, not from slow computation.",
            items: ["Generations 0 / 1 / 2", "Large object heap", "Workstation vs server GC", "Allocation is not free", "GC.Collect is almost always wrong"],
          },
          {
            fa: "Span و Memory", en: "Span and Memory", kind: "hard",
            whyFa: "کار روی بخشی از آرایه یا رشته بدون کپی؛ دلیل اصلی سرعت Kestrel و System.Text.Json.",
            whyEn: "Working on part of an array or string without copying; the main reason Kestrel and System.Text.Json are fast.",
            items: ["Span<T>", "ReadOnlySpan<T>", "Memory<T>", "stackalloc", "ref struct", "ArrayPool<T>"],
          },
          {
            fa: "IDisposable و منابع", en: "IDisposable and resources", kind: "hard",
            whyFa: "اتصال پایگاه‌داده یا فایلی که بسته نشود، سرور را بعد از چند ساعت از پا می‌اندازد.",
            whyEn: "A database connection or file left open brings a server down after a few hours.",
            items: ["using declarations", "IAsyncDisposable", "Dispose pattern", "Finalizers (avoid)"],
          },
          {
            fa: "بنچمارک و پروفایل", en: "Benchmarking and profiling", kind: "hard",
            whyFa: "بدون BenchmarkDotNet، اندازه‌گیری کارایی در .NET تقریباً همیشه غلط است: JIT، گرم شدن و GC نتیجه را به هم می‌ریزند.",
            whyEn: "Without BenchmarkDotNet, .NET performance measurements are almost always wrong: the JIT, warm-up and GC skew them.",
            items: ["BenchmarkDotNet", "dotnet-counters", "dotnet-trace", "PerfView / dotMemory"],
          },
        ],
      },
      {
        id: "cs-test",
        fa: "تست و کیفیت کد",
        en: "Testing and code quality",
        outcomeFa: "برای منطق کسب‌وکار تست واحد می‌نویسی و تحلیلگرها کیفیت کد را خودکار کنترل می‌کنند.",
        outcomeEn: "You write unit tests for business logic and analyzers enforce code quality automatically.",
        months: [1, 2],
        skills: [
          {
            fa: "تست واحد", en: "Unit testing", kind: "hard",
            whyFa: "تست، مستندی است که دروغ نمی‌گوید؛ و تنها چیزی که به تو جرئت بازآرایی کد را می‌دهد.",
            whyEn: "Tests are documentation that cannot lie — and the only thing that gives you the nerve to refactor.",
            items: ["xUnit", "NUnit", "MSTest", "Arrange-Act-Assert", "Theory & InlineData"],
          },
          {
            fa: "Test double", en: "Test doubles", kind: "hard",
            whyFa: "برای جدا کردن منطق از پایگاه‌داده، شبکه و زمان؛ TimeProvider (از .NET 8) تست کد وابسته به زمان را ساده کرده است.",
            whyEn: "To isolate logic from the database, the network and time; TimeProvider (.NET 8+) made time-dependent code easy to test.",
            items: ["NSubstitute", "Moq", "Fakes vs mocks", "TimeProvider"],
          },
          {
            fa: "کتابخانهٔ assertion", en: "Assertion libraries", kind: "hard", level: "alt",
            whyFa: "پیام خطای خوانا وقت دیباگ را کم می‌کند؛ FluentAssertions از نسخهٔ ۸ مجوز تجاری دارد و Shouldly جایگزین آزاد است.",
            whyEn: "Readable failure messages cut debugging time; FluentAssertions has a commercial licence from v8, and Shouldly is a free alternative.",
            items: ["Shouldly", "FluentAssertions (commercial from v8)", "Built-in Assert"],
          },
          {
            fa: "تحلیلگر و سبک کد", en: "Analyzers and style", kind: "hard",
            whyFa: "تحلیلگرها نیمی از بازبینی کد را خودکار می‌کنند و بحث‌های سلیقه‌ای را حذف می‌کنند.",
            whyEn: "Analyzers automate half of code review and end arguments about taste.",
            items: [".editorconfig", "Roslyn analyzers", "TreatWarningsAsErrors", "dotnet format", "SonarQube"],
          },
        ],
      },
      {
        id: "cs-eco",
        fa: "اکوسیستم و مسیرهای تخصصی",
        en: "Ecosystem and specialisations",
        outcomeFa: "کتابخانه منتشر می‌کنی، الگوهای طراحی را به‌جا به کار می‌بری و مسیر تخصصی بعدی‌ات را انتخاب می‌کنی.",
        outcomeEn: "You publish libraries, apply design patterns where they fit and choose your next specialisation.",
        months: [2, 6],
        skills: [
          {
            fa: "NuGet", en: "NuGet", kind: "hard",
            whyFa: "مخزن پکیج .NET؛ مدیریت متمرکز نسخه‌ها جلوی جهنم نسخه‌های ناهمخوان در راه‌حل‌های بزرگ را می‌گیرد.",
            whyEn: ".NET's package registry; central package management prevents version hell in large solutions.",
            items: ["PackageReference", "Central package management", "Creating a package", "Private feeds"],
            tracks: ["36-packaging"],
          },
          {
            fa: "الگوهای طراحی", en: "Design patterns", kind: "hard",
            whyFa: "زبان مشترک طراحی؛ ولی الگو را برای حل یک مشکل واقعی بیاور، نه برای نمایش.",
            whyEn: "The shared language of design; bring a pattern to solve a real problem, not to show off.",
            items: ["Factory", "Strategy", "Decorator", "Observer", "Repository (with care)"],
            tracks: ["47-oop", "07-architecture"],
          },
          {
            fa: "ASP.NET Core", en: "ASP.NET Core", kind: "hard",
            whyFa: "رایج‌ترین کاربرد C# در بازار کار؛ رودمپ جدای خودش را دارد.",
            whyEn: "C#'s most common use in the job market; it has its own roadmap.",
            items: ["Web APIs", "Minimal APIs", "Razor Pages / Blazor"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "دسکتاپ و موبایل", en: "Desktop and mobile", kind: "hard", level: "opt",
            whyFa: "بازار نرم‌افزارهای سازمانی ویندوزی هنوز بزرگ است؛ MAUI و Avalonia چندسکویی‌اند.",
            whyEn: "The market for enterprise Windows software is still large; MAUI and Avalonia are cross-platform.",
            items: [".NET MAUI", "WPF", "WinForms", "Avalonia"],
          },
          {
            fa: "بازی‌سازی با Unity", en: "Game development with Unity", kind: "hard", level: "opt",
            whyFa: "Unity با C# نوشته می‌شود؛ یکی از بزرگ‌ترین درهای ورود به بازی‌سازی.",
            whyEn: "Unity uses C#; one of the biggest doors into game development.",
            items: ["Unity editor", "MonoBehaviour", "Coroutines", "ScriptableObjects"],
          },
          {
            fa: "خواندن کد دیگران", en: "Reading other people's code", kind: "soft",
            whyFa: "کد منبع .NET باز است؛ خواندن پیاده‌سازی List یا Dictionary بهترین کلاس درس C# است.",
            whyEn: "The .NET source is open; reading how List or Dictionary is implemented is the best C# class there is.",
            items: ["dotnet/runtime on GitHub", "Source Link", "ILSpy"],
          },
        ],
      },
    ],
  },

  /* ═══════════════════════════ ASP.NET Core ═══════════════════════════ */
  {
    id: "aspnet-core",
    field: "tech",
    accent: "#7C3AED",
    ico: '<rect x="3" y="4" width="18" height="16" rx="2.4"/><path d="M3 9h18"/><path d="m9.4 12.6-2 2 2 2M14.6 12.6l2 2-2 2" stroke-linecap="round" stroke-linejoin="round"/>',
    after: ["csharp"],
    next: ["backend", "architect", "devops"],
    fa: {
      name: "ASP.NET Core",
      role: "ASP.NET Core Backend Developer",
      intro:
        "ASP.NET Core فریم‌ورک وب متن‌باز و چندسکویی مایکروسافت است و در بنچمارک‌ها جزو سریع‌ترین‌هاست. ستون فقرات بسیاری از سامانه‌های بانکی، سازمانی و دولتی است. این رودمپ از HTTP و خط لولهٔ middleware شروع می‌کند، از EF Core و احراز هویت می‌گذرد و به معماری، پیام‌رسانی، مشاهده‌پذیری و استقرار در تولید می‌رسد.",
    },
    en: {
      name: "ASP.NET Core",
      role: "ASP.NET Core Backend Developer",
      intro:
        "ASP.NET Core is Microsoft's open-source, cross-platform web framework and one of the fastest in benchmarks. It is the backbone of many banking, enterprise and government systems. This roadmap starts from HTTP and the middleware pipeline, passes through EF Core and authentication, and arrives at architecture, messaging, observability and production deployment.",
    },
    stages: [
      {
        id: "an-pre",
        fa: "پیش‌نیازها",
        en: "Prerequisites",
        outcomeFa: "C# را راحت می‌نویسی و می‌دانی یک درخواست HTTP دقیقاً چه چیزهایی دارد.",
        outcomeEn: "You write C# comfortably and know exactly what an HTTP request contains.",
        months: [1, 2],
        skills: [
          {
            fa: "C#", en: "C#", kind: "hard",
            whyFa: "هر خط ASP.NET Core، C# است؛ async، LINQ و رابط‌ها را روزانه به کار می‌بری.",
            whyEn: "Every line of ASP.NET Core is C#; you use async, LINQ and interfaces daily.",
            items: ["async/await", "LINQ", "Generics", "Interfaces", "Records"],
            tracks: ["09-csharp"],
          },
          {
            fa: "HTTP", en: "HTTP", kind: "hard",
            whyFa: "فریم‌ورک فقط HTTP را برایت راحت می‌کند؛ اگر کد وضعیت و هدر را نشناسی، API بدی می‌سازی.",
            whyEn: "A framework only makes HTTP convenient; if you do not know status codes and headers, you will build a bad API.",
            items: ["Methods & status codes", "Headers", "Cookies", "HTTPS / TLS", "REST principles"],
            tracks: ["26-web-foundations"],
          },
          {
            fa: "مبانی SQL", en: "SQL basics", kind: "hard",
            whyFa: "تقریباً هر API پشتش یک پایگاه‌داده دارد؛ ORM بدون فهم SQL کوئری‌های کند می‌سازد.",
            whyEn: "Almost every API has a database behind it; an ORM without SQL knowledge produces slow queries.",
            items: ["SELECT / JOIN", "Indexes", "Transactions"],
            tracks: ["05-sql"],
          },
          {
            fa: "Git و خط فرمان", en: "Git and the command line", kind: "hard",
            whyFa: "ساخت، اجرا و مهاجرت پایگاه‌داده همه از خط فرمان انجام می‌شود، و کد همیشه در Git است.",
            whyEn: "Building, running and database migrations all happen on the command line, and code always lives in Git.",
            items: ["dotnet CLI", "dotnet ef", "Git"],
            tracks: ["28-git"],
          },
        ],
      },
      {
        id: "an-core",
        fa: "هستهٔ فریم‌ورک",
        en: "Framework fundamentals",
        outcomeFa: "می‌دانی یک درخواست از لحظهٔ رسیدن به Kestrel تا پاسخ از کجاها می‌گذرد و سرویس‌ها با چه طول عمری ساخته می‌شوند.",
        outcomeEn: "You know every stop a request makes from Kestrel to the response, and the lifetime each service is created with.",
        months: [1, 2],
        skills: [
          {
            fa: "میزبانی و Kestrel", en: "Hosting and Kestrel", kind: "hard",
            whyFa: "Program.cs نقطهٔ شروع همه‌چیز است؛ محیط Development و Production رفتار متفاوتی دارند و باید بدانی کجا.",
            whyEn: "Program.cs is where everything starts; Development and Production behave differently and you need to know where.",
            items: ["WebApplication builder", "Generic host", "Kestrel", "Program.cs", "Environments"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "تزریق وابستگی", en: "Dependency injection", kind: "hard",
            whyFa: "سرویس Scoped که داخل یک Singleton تزریق شود، باگی می‌سازد که فقط زیر بار دیده می‌شود.",
            whyEn: "A Scoped service injected into a Singleton creates a bug that only shows under load.",
            items: ["AddSingleton / AddScoped / AddTransient", "Captive dependencies", "Keyed services", "IServiceScopeFactory"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "پیکربندی و Options", en: "Configuration and options", kind: "hard",
            whyFa: "رمز عبور در appsettings.json که به Git برود، یعنی نشت اطلاعات؛ باید لایه‌های پیکربندی را بشناسی.",
            whyEn: "A password in appsettings.json that reaches Git is a leak; you need to know the configuration layers.",
            items: ["appsettings.json", "Environment variables", "User secrets", "IOptions / IOptionsSnapshot / IOptionsMonitor", "Options validation"],
          },
          {
            fa: "خط لولهٔ middleware", en: "The middleware pipeline", kind: "hard",
            whyFa: "ترتیب middleware مهم است: اگر UseAuthorization قبل از UseAuthentication بیاید، دسترسی پیش از شناختن کاربر بررسی می‌شود و همه‌چیز ۴۰۱ می‌گیرد.",
            whyEn: "Middleware order matters: put UseAuthorization before UseAuthentication and access is checked before the user is known — everything returns 401.",
            items: ["Pipeline order", "Use / Map / Run", "Custom middleware", "Exception handling", "Short-circuiting"],
          },
          {
            fa: "لاگ", en: "Logging", kind: "hard",
            whyFa: "در تولید تنها چشم تو لاگ است؛ لاگ ساخت‌یافته قابل جستجوست، لاگ متنی نه.",
            whyEn: "In production your only eyes are logs; structured logs are searchable, plain text is not.",
            items: ["ILogger<T>", "Log levels", "Structured logging", "Serilog", "Log scopes"],
          },
        ],
      },
      {
        id: "an-api",
        fa: "ساخت API",
        en: "Building APIs",
        outcomeFa: "یک API مستند، اعتبارسنجی‌شده و نسخه‌بندی‌شده می‌سازی که خطاهایش هم استاندارد است.",
        outcomeEn: "You build a documented, validated, versioned API whose errors are standard too.",
        months: [1, 2],
        skills: [
          {
            fa: "Minimal API", en: "Minimal APIs", kind: "hard", level: "alt",
            whyFa: "سبک پیش‌فرض پروژه‌های جدید؛ کد کمتر، سرعت بیشتر و از .NET 10 اعتبارسنجی داخلی.",
            whyEn: "The default style for new projects; less code, more speed and, from .NET 10, built-in validation.",
            items: ["MapGet / MapPost", "Route groups", "Endpoint filters", "TypedResults", "Built-in validation (.NET 10)"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "Controller", en: "Controllers", kind: "hard", level: "alt",
            whyFa: "در بیشتر کدهای سازمانی موجود همین را می‌بینی.",
            whyEn: "What you will see in most existing enterprise code.",
            items: ["[ApiController]", "Attribute routing", "Action filters", "ModelState"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "مسیریابی و model binding", en: "Routing and model binding", kind: "hard",
            whyFa: "بیشتر خطاهای ۴۰۰ و ۴۱۵ از این است که داده از جایی خوانده می‌شود که فکرش را نمی‌کنی.",
            whyEn: "Most 400 and 415 errors come from data being read from a place you did not expect.",
            items: ["Route templates & constraints", "[FromBody] / [FromQuery] / [FromRoute]", "Custom binders", "Content negotiation"],
          },
          {
            fa: "اعتبارسنجی", en: "Validation", kind: "hard",
            whyFa: "هیچ ورودی‌ای را باور نکن؛ FluentValidation قاعده‌های پیچیده را خوانا و تست‌پذیر نگه می‌دارد.",
            whyEn: "Trust no input; FluentValidation keeps complex rules readable and testable.",
            items: ["Data annotations", "FluentValidation", "ProblemDetails for errors", "Validation in minimal APIs"],
          },
          {
            fa: "طراحی API", en: "API design", kind: "hard",
            whyFa: "API یک قرارداد عمومی است؛ تغییر شکستنی در آن یعنی کلاینت‌هایی که بی‌خبر از کار می‌افتند.",
            whyEn: "An API is a public contract; a breaking change means clients that stop working without warning.",
            items: ["Resource naming", "Meaningful status codes", "Pagination & filtering", "Versioning (Asp.Versioning)", "Idempotency keys"],
            tracks: ["07-architecture"],
          },
          {
            fa: "OpenAPI", en: "OpenAPI", kind: "hard",
            whyFa: "از .NET 9 تولید سند OpenAPI داخل خود فریم‌ورک است و Swashbuckle دیگر در قالب پیش‌فرض نیست.",
            whyEn: "Since .NET 9, OpenAPI generation is built into the framework and Swashbuckle is no longer in the default template.",
            items: ["Microsoft.AspNetCore.OpenApi", "Scalar / Swagger UI", "Client generation (NSwag, Kiota)"],
          },
          {
            fa: "مدیریت خطا", en: "Error handling", kind: "hard",
            whyFa: "کلاینت باید خطا را بفهمد نه stack trace ببیند؛ ProblemDetails قالب استاندارد آن است.",
            whyEn: "Clients should understand errors, not see stack traces; ProblemDetails is the standard shape.",
            items: ["IExceptionHandler", "ProblemDetails (RFC 9457)", "UseExceptionHandler", "Status code pages"],
          },
        ],
      },
      {
        id: "an-data",
        fa: "دسترسی به داده",
        en: "Data access",
        outcomeFa: "با EF Core مدل می‌سازی، مهاجرت می‌نویسی و SQL تولیدی را می‌خوانی؛ و می‌دانی کِی Dapper بهتر است.",
        outcomeEn: "You model with EF Core, write migrations and read the generated SQL — and know when Dapper is better.",
        months: [2, 3],
        skills: [
          {
            fa: "مبانی EF Core", en: "EF Core basics", kind: "hard",
            whyFa: "ORM استاندارد .NET؛ مهاجرت‌ها طرح‌وارهٔ پایگاه‌داده را همراه کد نسخه‌بندی می‌کنند.",
            whyEn: ".NET's standard ORM; migrations version the database schema alongside the code.",
            items: ["DbContext", "Migrations", "Relationships (1-1, 1-n, n-n)", "Fluent API", "Seeding"],
            tracks: ["10-aspnet-core", "05-sql"],
          },
          {
            fa: "کوئری درست با EF", en: "Querying well with EF", kind: "hard",
            whyFa: "EF Core کند نیست؛ کوئری‌ای که بدون دیدن SQL تولیدی نوشته شده، کند است.",
            whyEn: "EF Core is not slow; queries written without looking at the generated SQL are.",
            items: ["Tracking vs AsNoTracking", "Include & split queries", "Projection with Select", "N+1 problem", "Compiled queries", "ToQueryString"],
          },
          {
            fa: "همروندی و تراکنش", en: "Concurrency and transactions", kind: "hard",
            whyFa: "دو کاربر که هم‌زمان یک رکورد را ویرایش می‌کنند، بدون کنترل همروندی تغییر هم را پاک می‌کنند.",
            whyEn: "Two users editing one record at the same time overwrite each other without concurrency control.",
            items: ["Optimistic concurrency (RowVersion)", "Transactions", "Execution strategies & retries", "ExecuteUpdate / ExecuteDelete"],
          },
          {
            fa: "Dapper", en: "Dapper", kind: "hard", level: "alt",
            whyFa: "برای کوئری‌های گزارشی سنگین یا وقتی SQL دست‌نویس لازم است؛ خیلی از تیم‌ها EF و Dapper را کنار هم دارند.",
            whyEn: "For heavy reporting queries or when hand-written SQL is needed; many teams run EF and Dapper side by side.",
            items: ["Query<T>", "Parameters", "Multi-mapping", "When to choose Dapper"],
          },
          {
            fa: "SQL Server یا PostgreSQL", en: "SQL Server or PostgreSQL", kind: "hard", level: "alt",
            whyFa: "یکی را عمیق یاد بگیر: ایندکس، برنامهٔ اجرا و pooling اتصال را باید در موتور واقعی دیده باشی.",
            whyEn: "Learn one deeply: you must have seen indexes, execution plans and connection pooling in a real engine.",
            items: ["SQL Server", "PostgreSQL (Npgsql)", "Execution plans", "Connection pooling"],
            tracks: ["05-sql"],
          },
          {
            fa: "NoSQL و جستجو", en: "NoSQL and search", kind: "hard", level: "opt",
            whyFa: "برای کش، جستجوی متنی و داده‌های بدون طرح‌وارهٔ ثابت.",
            whyEn: "For caching, full-text search and schemaless data.",
            items: ["MongoDB driver", "Redis", "Elasticsearch"],
            tracks: ["51-mongodb", "52-redis", "19-elasticsearch"],
          },
        ],
      },
      {
        id: "an-security",
        fa: "احراز هویت و امنیت",
        en: "Authentication and security",
        outcomeFa: "ورود با کوکی یا JWT و ورود یکپارچه با OpenID Connect را پیاده می‌کنی و دسترسی را با policy کنترل می‌کنی.",
        outcomeEn: "You implement cookie or JWT sign-in and single sign-on with OpenID Connect, and control access with policies.",
        months: [2, 3],
        skills: [
          {
            fa: "احراز هویت", en: "Authentication", kind: "hard",
            whyFa: "کوکی برای اپ وب هم‌دامنه، JWT برای API و موبایل؛ انتخاب اشتباه یعنی مشکل امنیتی یا تجربهٔ بد.",
            whyEn: "Cookies for same-site web apps, JWT for APIs and mobile; the wrong choice means a security hole or a bad experience.",
            items: ["Cookie auth", "JWT bearer", "ASP.NET Core Identity", "Refresh tokens", "External logins"],
            tracks: ["10-aspnet-core"],
          },
          {
            fa: "OAuth2 و OpenID Connect", en: "OAuth2 and OpenID Connect", kind: "hard",
            whyFa: "برای چند اپ یا ورود یکپارچه، احراز هویت را به یک سرور هویت جدا بسپار، نه به تک‌تک سرویس‌ها.",
            whyEn: "For several apps or single sign-on, delegate authentication to a dedicated identity server, not to each service.",
            items: ["Authorization code + PKCE", "Access vs ID tokens", "Keycloak", "OpenIddict", "Duende IdentityServer (commercial)"],
          },
          {
            fa: "مجوزدهی", en: "Authorization", kind: "hard",
            whyFa: "نقش (role) زود از کار می‌افتد؛ policy و claim قاعدهٔ واقعی کسب‌وکار را بیان می‌کنند.",
            whyEn: "Roles break down quickly; policies and claims express the real business rules.",
            items: ["[Authorize] & policies", "Claims", "Roles vs policies", "Resource-based authorization", "Requirement handlers"],
          },
          {
            fa: "امنیت وب", en: "Web security", kind: "hard",
            whyFa: "بیشتر نفوذها از خطاهای شناخته‌شده‌اند؛ OWASP Top 10 فهرست همان‌هاست.",
            whyEn: "Most breaches come from well-known mistakes; the OWASP Top 10 is the list of them.",
            items: ["OWASP Top 10", "HTTPS & HSTS", "CORS", "Anti-forgery (CSRF)", "Rate limiting", "Data Protection API", "Secrets management"],
          },
        ],
      },
      {
        id: "an-perf",
        fa: "کش و کارایی",
        en: "Caching and performance",
        outcomeFa: "بار پایگاه‌داده را با کش درست کم می‌کنی و فراخوانی سرویس‌های بیرونی را در برابر خطا مقاوم می‌کنی.",
        outcomeEn: "You cut database load with the right caching and make calls to external services resilient to failure.",
        months: [1, 2],
        skills: [
          {
            fa: "کش", en: "Caching", kind: "hard",
            whyFa: "HybridCache (از .NET 9) کش حافظه و توزیع‌شده را یکی می‌کند و جلوی هجوم هم‌زمان به پایگاه‌داده را می‌گیرد.",
            whyEn: "HybridCache (from .NET 9) unifies in-memory and distributed caching and prevents stampedes on the database.",
            items: ["IMemoryCache", "IDistributedCache (Redis)", "HybridCache", "Output caching", "ETags", "Cache invalidation"],
            tracks: ["52-redis"],
          },
          {
            fa: "HttpClient و تاب‌آوری", en: "HttpClient and resilience", kind: "hard",
            whyFa: "ساختن HttpClient جدید برای هر درخواست، سوکت‌ها را تمام می‌کند — از قدیمی‌ترین باگ‌های .NET.",
            whyEn: "Creating a new HttpClient per request exhausts sockets — one of .NET's oldest bugs.",
            items: ["IHttpClientFactory", "Typed clients", "Microsoft.Extensions.Http.Resilience", "Retry, timeout, circuit breaker (Polly)"],
          },
          {
            fa: "کارایی", en: "Performance", kind: "hard",
            whyFa: "اول با ابزار بار واقعی اندازه بگیر؛ بعد بهینه کن. Native AOT زمان شروع و حافظه را برای APIهای کوچک کم می‌کند.",
            whyEn: "Measure under real load first, then optimise. Native AOT cuts start-up time and memory for small APIs.",
            items: ["Response compression", "Object pooling", "Load testing (k6)", "Native AOT for APIs"],
          },
        ],
      },
      {
        id: "an-bg",
        fa: "کار پس‌زمینه، بلادرنگ و ارتباط سرویس‌ها",
        en: "Background work, real-time and service communication",
        outcomeFa: "کار زمان‌بندی‌شده اجرا می‌کنی، به کلاینت پیام بلادرنگ می‌فرستی و سرویس‌ها را با صف پیام به هم وصل می‌کنی.",
        outcomeEn: "You run scheduled jobs, push real-time messages to clients and connect services with message queues.",
        months: [2, 3],
        skills: [
          {
            fa: "سرویس پس‌زمینه", en: "Background services", kind: "hard",
            whyFa: "کار طولانی نباید درخواست کاربر را معطل کند؛ و خاموش شدن امن یعنی کار نیمه‌کاره گم نمی‌شود.",
            whyEn: "Long work should not hold up the user's request; graceful shutdown means half-done work is not lost.",
            items: ["IHostedService", "BackgroundService", "Hangfire", "Quartz.NET", "Graceful shutdown"],
          },
          {
            fa: "SignalR", en: "SignalR", kind: "hard",
            whyFa: "اعلان، چت و داشبورد زنده بدون polling؛ برای چند سرور به backplane نیاز داری.",
            whyEn: "Notifications, chat and live dashboards without polling; several servers need a backplane.",
            items: ["Hubs", "Groups", "Redis backplane", "Auth in hubs"],
            tracks: ["20-realtime"],
          },
          {
            fa: "gRPC", en: "gRPC", kind: "hard", level: "opt",
            whyFa: "برای ارتباط داخلی سرویس‌به‌سرویس، سریع‌تر و تایپ‌دارتر از REST است.",
            whyEn: "Faster and more strongly typed than REST for internal service-to-service calls.",
            items: ["Protobuf contracts", "Unary & streaming", "gRPC-Web", "Deadlines"],
            tracks: ["08-microservices"],
          },
          {
            fa: "پیام‌رسانی", en: "Messaging", kind: "hard",
            whyFa: "صف پیام سرویس‌ها را از هم جدا می‌کند؛ ولی بدون الگوی Outbox پیام گم می‌شود یا دو بار ارسال می‌شود.",
            whyEn: "A message queue decouples services; but without the Outbox pattern, messages get lost or sent twice.",
            items: ["RabbitMQ", "Kafka", "MassTransit (commercial from v9)", "Wolverine", "Outbox pattern"],
            tracks: ["08-microservices"],
          },
        ],
      },
      {
        id: "an-test",
        fa: "تست",
        en: "Testing",
        outcomeFa: "منطق را با تست واحد و کل API را با تست یکپارچه روی پایگاه‌دادهٔ واقعی می‌سنجی.",
        outcomeEn: "You check logic with unit tests and the whole API with integration tests against a real database.",
        months: [1, 2],
        skills: [
          {
            fa: "تست واحد", en: "Unit tests", kind: "hard",
            whyFa: "منطق کسب‌وکار را جدا از HTTP و پایگاه‌داده تست کن؛ سریع‌اند و دقیق می‌گویند کجا خراب شده.",
            whyEn: "Test business logic apart from HTTP and the database; these tests are fast and pinpoint what broke.",
            items: ["xUnit", "NSubstitute / Moq", "Testing handlers & services"],
          },
          {
            fa: "تست یکپارچه", en: "Integration tests", kind: "hard",
            whyFa: "تست یکپارچه با پایگاه‌دادهٔ واقعی در کانتینر، باگ‌هایی را می‌گیرد که EF InMemory هرگز نمی‌بیند.",
            whyEn: "Integration tests against a real database in a container catch bugs EF InMemory never sees.",
            items: ["WebApplicationFactory", "Testcontainers", "Respawn", "Real vs in-memory database"],
            tracks: ["01-docker"],
          },
          {
            fa: "تست قرارداد و بار", en: "Contract and load tests", kind: "hard", level: "opt",
            whyFa: "وقتی چند تیم به API تو وابسته‌اند یا ترافیک بالاست، این دو جلوی غافلگیری را می‌گیرند.",
            whyEn: "When several teams depend on your API or traffic is high, these two prevent surprises.",
            items: ["Pact", "k6", "NBomber"],
          },
        ],
      },
      {
        id: "an-arch",
        fa: "معماری",
        en: "Architecture",
        outcomeFa: "برای اندازهٔ پروژه، سبک معماری مناسب را انتخاب می‌کنی و از آن دفاع می‌کنی.",
        outcomeEn: "You choose the right architectural style for the project's size and can defend it.",
        months: [2, 4],
        skills: [
          {
            fa: "معماری لایه‌ای و Clean", en: "Layered and Clean Architecture", kind: "hard",
            whyFa: "قاعدهٔ وابستگی — هستهٔ کسب‌وکار به هیچ فریم‌ورکی وابسته نیست — تست و تعویض زیرساخت را ممکن می‌کند.",
            whyEn: "The dependency rule — business core depends on no framework — makes testing and swapping infrastructure possible.",
            items: ["Layered architecture", "Clean Architecture", "Onion", "Dependency rule"],
            tracks: ["07-architecture"],
          },
          {
            fa: "Vertical slice", en: "Vertical slices", kind: "hard", level: "alt",
            whyFa: "هر قابلیت یک پوشه و یک handler؛ انتزاع کمتر و تغییر ساده‌تر برای بیشتر APIها.",
            whyEn: "One folder and one handler per feature; less abstraction and simpler change for most APIs.",
            items: ["Feature folders", "One handler per use case", "Less abstraction"],
            tracks: ["07-architecture"],
          },
          {
            fa: "DDD", en: "Domain-Driven Design", kind: "hard",
            whyFa: "وقتی پیچیدگی در قواعد کسب‌وکار است نه در فناوری، DDD زبان و ابزار مدل کردنش را می‌دهد.",
            whyEn: "When complexity lives in the business rules rather than the technology, DDD gives you the language and tools to model it.",
            items: ["Entities & value objects", "Aggregates", "Domain events", "Bounded contexts"],
            tracks: ["50-ddd"],
          },
          {
            fa: "CQRS و mediator", en: "CQRS and mediators", kind: "hard", level: "opt",
            whyFa: "جدا کردن خواندن از نوشتن در دامنه‌های پیچیده مفید است؛ MediatR مجوز تجاری گرفته و نوشتن یک dispatcher ساده هم کافی است.",
            whyEn: "Separating reads from writes helps in complex domains; MediatR now has a commercial licence, and a simple hand-written dispatcher is often enough.",
            items: ["Commands vs queries", "MediatR (commercial)", "Hand-rolled dispatcher", "Pipeline behaviours"],
          },
          {
            fa: "مونولیت ماژولار و میکروسرویس", en: "Modular monoliths and microservices", kind: "hard",
            whyFa: "بیشتر تیم‌ها باید با مونولیت ماژولار شروع کنند؛ میکروسرویس هزینهٔ عملیاتی سنگینی دارد که فقط در مقیاس سازمانی می‌ارزد.",
            whyEn: "Most teams should start with a modular monolith; microservices carry a heavy operational cost that only pays off at organisational scale.",
            items: ["Modular monolith", "Microservices", "API gateway (YARP)", "Service boundaries"],
            tracks: ["08-microservices"],
          },
        ],
      },
      {
        id: "an-ops",
        fa: "استقرار و مشاهده‌پذیری",
        en: "Deployment and observability",
        outcomeFa: "API را در کانتینر پشت پراکسی منتشر می‌کنی و با لاگ، متریک و ردیابی می‌بینی در تولید چه می‌گذرد.",
        outcomeEn: "You ship the API in a container behind a proxy and see what happens in production through logs, metrics and traces.",
        months: [1, 3],
        skills: [
          {
            fa: "Docker", en: "Docker", kind: "hard",
            whyFa: "ایمیج چندمرحله‌ای کوچک و امن است؛ SDK فقط برای build لازم است نه برای اجرا.",
            whyEn: "A multi-stage image is small and safe; the SDK is needed to build, not to run.",
            items: ["Multi-stage Dockerfile", "Chiseled images", "dotnet publish container support", "Health checks"],
            tracks: ["01-docker"],
          },
          {
            fa: "پراکسی معکوس و میزبانی", en: "Reverse proxy and hosting", kind: "hard",
            whyFa: "پشت پراکسی، بدون ForwardedHeaders برنامه آی‌پی واقعی کاربر و https بودن درخواست را نمی‌بیند.",
            whyEn: "Behind a proxy, without ForwardedHeaders the app never sees the user's real IP or that the request was https.",
            items: ["Nginx", "IIS", "Forwarded headers", "Kestrel limits", "YARP"],
            tracks: ["02-nginx"],
          },
          {
            fa: "مشاهده‌پذیری", en: "Observability", kind: "hard",
            whyFa: "وقتی کاربر می‌گوید «کند است»، ردیابی توزیع‌شده دقیقاً نشان می‌دهد کدام کوئری یا سرویس مقصر است.",
            whyEn: "When a user says “it's slow”, distributed tracing shows exactly which query or service is to blame.",
            items: ["OpenTelemetry", "Traces, metrics, logs", "Health checks", "Grafana / Jaeger / Seq", "Correlation IDs"],
          },
          {
            fa: "Aspire", en: "Aspire", kind: "hard", level: "opt",
            whyFa: "توسعهٔ محلی سامانهٔ چندسرویسه با یک دستور، همراه داشبورد لاگ و ردیابی.",
            whyEn: "Local development of a multi-service system with one command, with a dashboard for logs and traces.",
            items: ["AppHost", "Service defaults", "Dashboard", "Integrations"],
          },
          {
            fa: "CI/CD و Kubernetes", en: "CI/CD and Kubernetes", kind: "hard",
            whyFa: "مهاجرت پایگاه‌داده باید بخشی از خط انتشار باشد، نه کاری دستی ساعت دو نیمه‌شب.",
            whyEn: "Database migrations should be part of the pipeline, not a manual job at 2 a.m.",
            items: ["GitHub Actions / GitLab CI", "Migrations in pipelines", "Kubernetes deployments", "Rolling & blue-green"],
            tracks: ["04-devops", "06-kubernetes"],
          },
          {
            fa: "حواست به مجوزها باشد", en: "Licence awareness", kind: "soft",
            whyFa: "چند کتابخانهٔ محبوب .NET — MediatR، AutoMapper، MassTransit نسخهٔ ۹، FluentAssertions نسخهٔ ۸، Duende IdentityServer — مجوز تجاری دارند؛ پیش از استفاده در شرکت، مجوز را بخوان.",
            whyEn: "Several popular .NET libraries — MediatR, AutoMapper, MassTransit v9, FluentAssertions v8, Duende IdentityServer — carry commercial licences; read the licence before using them at work.",
            items: ["Licence review", "Open-source alternatives", "Pinning versions"],
          },
          {
            fa: "مستندسازی برای مصرف‌کنندهٔ API", en: "Docs for API consumers", kind: "soft",
            whyFa: "API بی‌مستند، تیم‌های دیگر را مجبور می‌کند مدام از تو بپرسند؛ changelog و اعلام منسوخ شدن، اعتماد می‌سازد.",
            whyEn: "An undocumented API forces other teams to keep asking you; changelogs and deprecation notices build trust.",
            items: ["API guides", "Changelogs", "Deprecation notices"],
            tracks: ["64-docs-writing"],
          },
        ],
      },
    ],
  },
];
